### ISSUE TITLE
A few odd occurrences /spawn /help and EssentialsChat-Antibuild

### ISSUE THREAD

**Issue by th2000125** [EssentialsX/Essentials#1006]
So the overall specs. I like running on Paperspigot (Paperclip) But I have been clicking between the two getting the same errors in MC 1.11.  I have made sure that they are all the same build version of essentials. 

So I have tried to keep as much as a track as possible on whats happening as possible to try and help. First of all, essentials chat was not working it was saying something about Async errors https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/AsyncPlayerChatEvent.html And commands that have worked for years seem to have suddenly broken. (It is probably me poorly configuring it) but I have added all permissions even given .* and the errors persist. Antibuild has been previously reported but hopefully more data will help solve the problem.

I would like to end by saying thank you to the developer for the continued support and maintenance of these fantastic plugins! I wish I would have done more than report these issues that I am having but I am unfortunately no expert on Java or Minecraft.

## Chat Error (players could still talk but console would not be passed the chatlog)
> [00:03:01] [Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.0.1-b450
java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/CalculableType
	at net.milkbowl.vault.chat.plugins.Chat_bPermissions2.getPlayerPrefix(Chat_bPermissions2.java:97) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:67) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getPrefix(AbstractVaultHandler.java:48) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getPrefix(PermissionsHandler.java:68) ~[?:?]
	at com.earth2me.essentials.User.getNick(User.java:306) ~[?:?]
	at com.earth2me.essentials.User.getNick(User.java:275) ~[?:?]
	at com.earth2me.essentials.User.setDisplayNick(User.java:335) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:88) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor45.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.jar:git-Paper-953]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1288) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1203) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.11.jar:git-Paper-953]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
[00:03:01] [Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.0.1-b450
java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/CalculableType
	at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPlayerGroups(Permission_bPermissions2.java:172) ~[?:?]
	at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPrimaryGroup(Permission_bPermissions2.java:177) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]
	at com.earth2me.essentials.User.getGroup(User.java:618) ~[?:?]
	at com.earth2me.essentials.chat.EssentialsChatPlayerListenerLowest.onPlayerChat(EssentialsChatPlayerListenerLowest.java:42) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor80.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.jar:git-Paper-953]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.jar:git-Paper-953]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PlayerConnection.chat(PlayerConnection.java:1288) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1203) [patched_1.11.jar:git-Paper-953]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [patched_1.11.jar:git-Paper-953]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
> 

## Antibuild Error
>
04:26:40] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.0.1-b453
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/CalculableType
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPlayerGroups(Permission_bPermissions2.java:172) ~[?:?]
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPrimaryGroup(Permission_bPermissions2.java:177) ~[?:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]
at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]
at com.earth2me.essentials.User.getGroup(User.java:619) ~[?:?]
at com.earth2me.essentials.User.canBuild(User.java:640) ~[?:?]
at com.earth2me.essentials.antibuild.EssentialsAntiBuildListener.onPlayerInteract(EssentialsAntiBuildListener.java:184) ~[?:?]
at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
... 17 more
>

## Player Joining
>
[10:42:38] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Vault v1.5.6-b49
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:334) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/CalculableType
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.playerHas(Permission_bPermissions2.java:119) ~[?:?]
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.has(Permission_bPermissions2.java:95) ~[?:?]
at net.milkbowl.vault.Vault$VaultListener.onPlayerJoin(Vault.java:584) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
... 14 more
Caused by: java.lang.ClassNotFoundException: de.bananaco.bpermissions.api.CalculableType
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_112]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_112]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_112]
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.playerHas(Permission_bPermissions2.java:119) ~[?:?]
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.has(Permission_bPermissions2.java:95) ~[?:?]
at net.milkbowl.vault.Vault$VaultListener.onPlayerJoin(Vault.java:584) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
... 14 more
[10:42:38] [Server thread/INFO]: Zaoby[/31.48.68.53:61309] logged in with entity id 70 at ([Zaobia]1338.9582069151359, 68.0, 912.9685151289153)
>
## Random Essentials Error
>
**[10:42:38] [Craft Scheduler Thread - 4/WARN]: [Essentials] Plugin Essentials v2.0.1-b453 generated an exception while executing task 48
java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/CalculableType
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPlayerGroups(Permission_bPermissions2.java:172) ~[?:?]
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPrimaryGroup(Permission_bPermissions2.java:177) ~[?:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]
at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]
at com.earth2me.essentials.User.getGroup(User.java:619) ~[?:?]
at com.earth2me.essentials.textreader.TextInput.(TextInput.java:28) ~[?:?]
at com.earth2me.essentials.EssentialsPlayerListener.delayedJoin(EssentialsPlayerListener.java:209) ~[?:?]
at com.earth2me.essentials.EssentialsPlayerListener$1.run(EssentialsPlayerListener.java:179) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
>
## /spawn error
>
[10:46:58] [Server thread/INFO]: Zaoby issued server command: /spawn
[10:46:58] [Server thread/ERROR]: Command spawn failed:
java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/CalculableType
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPlayerGroups(Permission_bPermissions2.java:172) ~[Vault.jar:?]
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPrimaryGroup(Permission_bPermissions2.java:177) ~[Vault.jar:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[Vault.jar:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[Vault.jar:?]
at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.User.getGroup(User.java:619) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.spawn.Commandspawn.respawn(Commandspawn.java:51) ~[EssentialsXSpawn-2.0.1.jar:?]
at com.earth2me.essentials.spawn.Commandspawn.run(Commandspawn.java:33) ~[EssentialsXSpawn-2.0.1.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:466) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.spawn.EssentialsSpawn.onCommand(EssentialsSpawn.java:64) [EssentialsXSpawn-2.0.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
>
## Help command error
>
[10:48:01] [Server thread/INFO]: Zaoby issued server command: /help
[10:48:01] [Server thread/ERROR]: Command help failed:
java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/CalculableType
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPlayerGroups(Permission_bPermissions2.java:172) ~[Vault.jar:?]
at net.milkbowl.vault.permission.plugins.Permission_bPermissions2.getPrimaryGroup(Permission_bPermissions2.java:177) ~[Vault.jar:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[Vault.jar:?]
at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[Vault.jar:?]
at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.User.getGroup(User.java:619) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.textreader.TextInput.(TextInput.java:28) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.commands.Commandhelp.run(Commandhelp.java:25) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:466) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:376) [EssentialsX-2.0.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigotmc-1.11-R0.1.jar:git-Spigot-f950f8e-a710176]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
>

**Comment by mdcfe** [comment]
Have you tried updating bPermissions? Alternatively, use another permissions plugin.

**Comment by th2000125** [comment]
I'm sorry to say I have never used bpermissions. I use groupmanager. At the time of these consistent errors even without a permissions plugin and the errors are identical.

**Comment by mdcfe** [comment]
First of all, don't use GroupManager. Have you tried updating Vault and EssentialsX to [thr latest build](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild)?

**Comment by th2000125** [comment]
Vault is already latest and Essentials is the same story. I have just started something called lord-permissions seems good however. Same errors.

**Comment by mdcfe** [comment]
Does that plugin support Vault? If not, it won't work with EssentialsX. Could you also paste the plugins you have installed?

**Comment by th2000125** [comment]
WorldEdit, LordPermissions, NoNetherRoof, Vault, WorldGuard, Essentials, EssentialsGeoIP, EssentialsAntiBuild, ShopChest, EssentialsExtras, EssentialsSpawn, EssentialsProtect. I do not believe it does. will swap to yet another permissions plugin, which one do you recommend? (please anything but PermissionsEX)

**Comment by Kakifrucht** [comment]
I use bPermissions, works well for me.

**Comment by mdcfe** [comment]
For whatever reason, bPermissions' Vault handler was being called. I have no idea why or how.

If this is still an issue, could you swap to LuckPerms and see if it still occurs?

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.
