### ISSUE TITLE
/enchant error 1.8 EssentialsX Jenkins Lastest update

### ISSUE THREAD

**Issue by Beatzey** [EssentialsX/Essentials#1015]
Having problem with /enchant so here is my report.

[23:28:43] [Server thread/ERROR]: Command enchant failed:
java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.setItemInMainHand(Lorg/bukkit/inventory/ItemStack;)V
at com.earth2me.essentials.craftbukkit.InventoryWorkaround.setItemInMainHand(InventoryWorkaround.java:190) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.commands.Commandenchant.run(Commandenchant.java:59) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:466) [EssentialsX-2.0.1.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:376) [EssentialsX-2.0.1.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_112]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_112]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigotmc-1.8.8-R0.1.jar:git-Spigot-e4d4710-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by mdcfe** [comment]
@vemacs shouldn't this be dealt with by the InventoryWorkaround class?

**Comment by mdcfe** [comment]
Get the latest build from [here](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by CheatSupport** [comment]
@md678685 works for 1.8.8? "builds of EssentialsX above #440 require Minecraft 1.11+ for full /spawnmob functionality." it states on the ci

**Comment by CheatSupport** [comment]
@vemacs since this was a 1.8 issue on the latest build, does that mean latest builds can be used for 1.8 servers now?

**Comment by vemacs** [comment]
Spawn mob won't have full functionality, but yeah, exactly as it says...?
