### ISSUE TITLE
Spawner Place Exception on 1.8

### ISSUE THREAD

**Issue by ygtdmn** [EssentialsX/Essentials#1022]
When i place Iron Golem or Item Spawner im taking this error:
Version: 1.8 PaperSpigot Essentialsx b439
```

[22:55:23 ERROR]: Could not pass event BlockPlaceEvent to Essentials v2.0.1-b439
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:125) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.ItemStack.placeItem(ItemStack.java:157) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:503) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:725) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:748) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:320) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:686) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:589) [spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
Caused by: java.lang.IllegalArgumentException
        at net.ess3.nms.v1_8_R1.v1_8_R1SpawnerProvider.getEntityType(v1_8_R1SpawnerProvider.java:36) ~[?:?]
        at com.earth2me.essentials.EssentialsBlockListener.onBlockPlace(EssentialsBlockListener.java:39) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-PaperSpigot-9b05d00-33d5de3]
        ... 17 more

```

**Comment by SupaHam** [comment]
Update your version. https://ci.drtshock.net/job/EssentialsX/

Edit: Ignore the b440 warning message, I just removed it.
