### ISSUE TITLE
Error (latest EssentialsX build - PaperSpigot 1.7)

### ISSUE THREAD

**Issue by RikoDEV** [EssentialsX/Essentials#1028]
Hi, when player use command /killall mobs in the console throws Error:
```
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getCustomName()Ljava/lang/String;
	at com.earth2me.essentials.commands.Commandremove.removeHandler(Commandremove.java:132) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandremove.parseCommand(Commandremove.java:82) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandremove.run(Commandremove.java:43) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:466) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:376) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [paperclip.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [paperclip.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:765) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1047) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:884) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:795) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [paperclip.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [paperclip.jar:git-PaperSpigot-1f7d532]
```

**Comment by mdcfe** [comment]
~~Could you update to the latest build?~~

**Comment by RikoDEV** [comment]
I have latest build

**Comment by mdcfe** [comment]
@vemacs @SupaHam Is this related to 1.11 changes?

**Comment by mdcfe** [comment]
1.7.10 is no longer supported.
