### ISSUE TITLE
Problem with GroupManagerX

### ISSUE THREAD

**Issue by NorthWestTrees** [EssentialsX/Essentials#1079]
2017-01-17 08-36
=============================== GM ERROR LOG ===============================
= ERROR REPORT START - GMBuildVer (Phoenix)+1 =

java.lang.IllegalArgumentException: The following file couldn't pass on Parser.
plugins\GroupManagerX\globalgroups.yml
	at org.anjocaido.groupmanager.GlobalGroups.load(GlobalGroups.java:119)
	at org.anjocaido.groupmanager.GlobalGroups.<init>(GlobalGroups.java:44)
	at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:161)
	at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:91)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376)
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326)
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419)
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380)
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335)
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
	at java.lang.Thread.run(Unknown Source)
Caused by: while scanning a simple key
 in 'reader', line 302, column 3:
      g:residence_staff
      ^
could not find expected ':'
 in 'reader', line 303, column 16:
        permissions:
                   ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:465)
	at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:280)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:225)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntry.produce(ParserImpl.java:529)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:393)
	at org.anjocaido.groupmanager.GlobalGroups.load(GlobalGroups.java:116)
	... 14 more

It told me to post to one of you developers in error at start up, its just one of the problems I am having I am trying to locate which of the few plugins are causing conflict with SignShops but I have a feeling it may be either group manager or your plugin, could you add support for both of these plugins below thanks.
https://www.spigotmc.org/resources/signshop.10997/
https://www.spigotmc.org/resources/groupmanagerx.32280/

I also have the fallowing plugins but I am not sure or not if you have support for them.
https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-11.11480/
https://www.spigotmc.org/resources/dynmap.274/
https://dev.bukkit.org/projects/simplechatchannels
https://dev.bukkit.org/projects/vault
https://dev.bukkit.org/projects/lockette

**Comment by Kakifrucht** [comment]
Why would you report that issue here?
GroupManagerX is not supported and the "maintained" version you linked has a) nothing to do with this repository, and b) is still a terrible and buggy plugin that shouldn't be used.
