### ISSUE TITLE
Essentials Timer Error?

### ISSUE THREAD

**Issue by NorthWestTrees** [EssentialsX/Essentials#1084]
Hello, I have two questions the first question may have to do with the second question but I will start with the title of the post.

I have had this error pop up in the console saying Essentials Timer Error.
It started after I got a warning saying that essentials were generating an exception for task 4749 whatever that means.

I was wondering if that has to do with something on my end or coding in the plugin either way on to the next question.

I posted an error a day ago because this "terrible and buggy plugin" as someone posted on the topic said that GroupManagerX had problems, **_I was hoping if you could direct me to a plugin that works with Essentials, not buggy and fairly easy to set up or at the bare minimum that they keep it up to date._**
I am unsure if that will fix my problem with essentials but I am willing to convert the permissions over to something that has better support.

This is the Task 4749 Error Log:

> [12:40:37] [pool-3-thread-41/WARN]: [Essentials] Plugin Essentials v2.0.1-b463 generated an exception while executing task 4749
java.lang.NullPointerException
	at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:327) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]
	at com.earth2me.essentials.User.getGroup(User.java:622) ~[?:?]
	at com.earth2me.essentials.textreader.TextInput.<init>(TextInput.java:28) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.delayedJoin(EssentialsPlayerListener.java:209) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener$1.run(EssentialsPlayerListener.java:179) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_111]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

This is the fallowing repetitive errors that fallowed.

> [14:06:01] [Server thread/WARN]: [Essentials] EssentialsTimer Error:
java.lang.NullPointerException
	at net.milkbowl.vault.chat.plugins.Chat_GroupManager.getPlayerPrefix(Chat_GroupManager.java:271) ~[Vault.jar:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:67) ~[Vault.jar:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91) ~[Vault.jar:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getPrefix(AbstractVaultHandler.java:48) ~[EssentialsX.jar:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getPrefix(PermissionsHandler.java:68) ~[EssentialsX.jar:?]
	at com.earth2me.essentials.User.getNick(User.java:310) ~[EssentialsX.jar:?]
	at com.earth2me.essentials.User.getNick(User.java:279) ~[EssentialsX.jar:?]
	at com.earth2me.essentials.User.setDisplayNick(User.java:339) ~[EssentialsX.jar:?]
	at com.earth2me.essentials.User.checkActivity(User.java:584) ~[EssentialsX.jar:?]
	at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:58) [EssentialsX.jar:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:53) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:689) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[14:07:28] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Essentials v2.0.1-b463
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:602) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying.a(SourceFile:126) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at net.milkbowl.vault.chat.plugins.Chat_GroupManager.getPlayerPrefix(Chat_GroupManager.java:271) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:67) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getPrefix(AbstractVaultHandler.java:48) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getPrefix(PermissionsHandler.java:68) ~[?:?]
	at com.earth2me.essentials.User.getNick(User.java:310) ~[?:?]
	at com.earth2me.essentials.User.getNick(User.java:279) ~[?:?]
	at com.earth2me.essentials.User.setDisplayNick(User.java:339) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:548) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerMove(EssentialsPlayerListener.java:128) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.11.2.jar:git-Bukkit-775f1e1]
	... 15 more

Below is the link the the other post.
https://github.com/drtshock/Essentials/issues/1079

**Comment by vemacs** [comment]
[zPermissions](https://www.spigotmc.org/resources/zpermissions.11736/) is relatively easy to set up, although it's stable enough to basically not need any changes. PEX 1.x is also a reasonably popular plugin, but isn't really maintained anymore. Both are more stable and better maintained than GroupManager.

**Comment by NorthWestTrees** [comment]
thank you for your reply.
