### ISSUE TITLE
Error message with Silktouchspawner

### ISSUE THREAD

**Issue by julien1721** [EssentialsX/Essentials#1112]
Hi.

When I put a spawner, i have a error message in my console (I use Silkspawners).

[Server thread/WARN]: Skipping BlockEntity with id
[00:55:58] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to Essentials v2.0.1-b463
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:146) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.ItemStack.placeItem(ItemStack.java:186) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:490) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:897) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
at org.bukkit.craftbukkit.v1_11_R1.block.CraftCreatureSpawner.getSpawnedType(CraftCreatureSpawner.java:27) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
at net.ess3.nms.updatedmeta.BlockMetaSpawnerProvider.getEntityType(BlockMetaSpawnerProvider.java:25) ~[?:?]
at com.earth2me.essentials.EssentialsBlockListener.onBlockPlace(EssentialsBlockListener.java:39) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.jar:git-Spigot-d60de0a-a951a88]
... 18 more

What is the problem ?

Thanks for your help.
Julien.

**Comment by vemacs** [comment]
That spawner probably has corrupt data. I'll add a nullcheck sometime.

**Comment by julien1721** [comment]
Hi.

And what do I need to do ...

**Comment by mdcfe** [comment]
@julien1721 Apologies for than late response, but does this issue still occur?

**Comment by pop4959** [comment]
Feel free to let us know if the issue still occurs. Closing since there has been no response for quite some time.
