### ISSUE TITLE
EssentialsX isn't loading the plugin?

### ISSUE THREAD

**Issue by djcammo** [EssentialsX/Essentials#1141]
Heres the only log it gives me, I am also using the latest version of EssentialsX on 1.11.2 Spigot. I contacted the GetBukkit team and they couldnt solve it, ive tried other versions of essentialsX and other spigot versions, still get the exact same log. Any ideas?

[16:29:23 INFO]: Starting Minecraft server on *:25565
[16:29:23 INFO]: Using default channel type
[16:29:23 ERROR]: Could not load 'plugins/EssentialsX-2.0.1 (7).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/earth2me/essentials/Essentials : Unsupported major.minor version 51.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-65a0347-1a71021]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-65a0347-1a71021]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-65a0347-1a71021]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-65a0347-1a71021]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-65a0347-1a71021]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-65a0347-1a71021]
	at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
Caused by: java.lang.UnsupportedClassVersionError: com/earth2me/essentials/Essentials : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-65a0347-1a71021]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-65a0347-1a71021]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-65a0347-1a71021]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-65a0347-1a71021]
	... 6 more
[16:29:23 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[16:29:23 INFO]: Preparing level "world"

**Comment by Kakifrucht** [comment]
You are running an outdated version of Java.

**Comment by djcammo** [comment]
Im using the latest version

**Comment by mdcfe** [comment]
> Unsupported major.minor version 51.0

As @Kakifrucht said, you need to update Java. Otherwise, the plugin will not load.
