### ISSUE TITLE
killall command does not work

### ISSUE THREAD

**Issue by TomberWolf** [EssentialsX/Essentials#1161]
The topic says it. It's completely without function.

**Comment by mdcfe** [comment]
* What server version are you running? `/version`
* What EssentialsX version are you running? `/essentials`
* What appears in the console when you run the command? `/killall`

**Comment by TomberWolf** [comment]
We're on Thermos 1.7.10
EssentialsX version 2.0.1-b468

And the console output:

`[15:43:31] [Server thread/INFO]: Tom issued server command: /killall all
[15:43:31] [Server thread/ERROR]: Befehl killall scheiterte:
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getCustomName()Ljava/lang/String;
	at com.earth2me.essentials.commands.Commandremove.removeHandler(Commandremove.java:132) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandremove.parseCommand(Commandremove.java:82) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandremove.run(Commandremove.java:43) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:471) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:381) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
`

**Comment by mdcfe** [comment]
It might be worth downgrading to a non-1.11 version to see if the 1.11 changes are the issue.

**Comment by TomberWolf** [comment]
Could you provide me a link for a pre-1.11 build?

**Comment by mdcfe** [comment]
Try [build 439](https://ci.drtshock.net/job/EssentialsX/439/). If the error still happens, 1.11 changes can be ruled out.

Edit: I think this is a duplicate, but I can't remember which issue it was.

**Comment by TomberWolf** [comment]
I tried that build.

`[08:16:42] [Server thread/INFO]: Tom issued server command: /killall all
[08:16:42] [Server thread/ERROR]: Befehl killall scheiterte:
java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getCustomName()Ljava/lang/String;
	at com.earth2me.essentials.commands.Commandremove.removeHandler(Commandremove.java:132) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandremove.parseCommand(Commandremove.java:82) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.Commandremove.run(Commandremove.java:43) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:467) [EssentialsX-2.0.1.jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:377) [EssentialsX-2.0.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.58]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
`

**Comment by mdcfe** [comment]
1.7.10 is no longer supported.
