### ISSUE TITLE
Errors every time a player logs on, also random kicks

### ISSUE THREAD

**Issue by gerardvanschip** [EssentialsX/Essentials#1169]
I recently swapped Essentials TeamCity for EssentialsX and while staying afk for hours worked fine before I noticed that I now lose the connection. I get the following error in my console. I also get this error every time a player logs on. I hope its something simple as I like the little fixes that x has over the teamcity version. Performance I have seen little change.

```
[06:04:56] [Server thread/INFO]: KaizenWorlds[/115.177.46.62:50075] logged in with entity id 5222 at ([Sekai]87.21192845436119, 79.13345583373835, -3186.470638322075)
[06:04:56] [Craft Scheduler Thread - 14/INFO]: [GAListener] Player: KaizenWorlds has 129 votes
[06:04:56] [Craft Scheduler Thread - 14/WARN]: [Essentials] Plugin Essentials v2.0.1-b370 generated an exception while executing task 681
java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.getSpawnOnJoinGroups()Ljava/util/List;
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75) ~[?:?]
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:67) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_65]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
```

And another user
```
[06:05:02] [User Authenticator #2/INFO]: UUID of player elf_erik is 5bbb1f78-df75-4515-97d0-49c5dbc4dc5d
[06:05:02] [Server thread/INFO]: elf_erik[/68.118.139.42:52098] logged in with entity id 5578 at ([Sekai]2164.3802749132346, 74.0, -4421.48195589283)
[06:05:02] [Craft Scheduler Thread - 14/INFO]: [GAListener] Player: elf_erik has 25 votes
[06:05:02] [Craft Scheduler Thread - 14/WARN]: [Essentials] Plugin Essentials v2.0.1-b370 generated an exception while executing task 775
java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.getSpawnOnJoinGroups()Ljava/util/List;
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75) ~[?:?]
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:67) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[custom.jar:git-Spigot-d4f98a3-cb61ac0]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [custom.jar:git-Spigot-d4f98a3-cb61ac0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_65]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
```

**Comment by mdcfe** [comment]
Can you update to the [latest version](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild)?

@drtshock Is there a chance the Spigot page could point users to the latest version, rather than a version which is nearly 100 builds old?

**Comment by gerardvanschip** [comment]
Thanks md678685, as you could see I already had the newer versions of the other essentials plugins but indeed grabbed the main one from the Spigot page. No errors now.
