### ISSUE TITLE
Error pass BlockPlaceEvent to AntiBuild

### ISSUE THREAD

**Issue by KorDum** [EssentialsX/Essentials#1170]
Errors caused with Thaumcraft golems. Last version of Thermos server (Bukkit 1.7.9).

```
[10:01:35 ERROR]: Could not pass event BlockPlaceEvent to EssentialsAntiBuild v2.0.1-b468
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.58]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:145) [CraftEventFactory.class:1.7.10-1614.58]
        at net.minecraftforge.event.world.BlockEvent$PlaceEvent.<init>(BlockEvent.java:152) [BlockEvent$PlaceEvent.class:1.7.10-1614.58]
        at net.minecraftforge.event.world.BlockEvent$MultiPlaceEvent.<init>(BlockEvent.java:178) [BlockEvent$MultiPlaceEvent.class:1.7.10-1614.58]
        at net.minecraftforge.event.ForgeEventFactory.onPlayerMultiBlockPlace(ForgeEventFactory.java:63) [ForgeEventFactory.class:1.7.10-1614.58]
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:599) [ForgeHooks.class:1.7.10-1614.58]
        at net.minecraft.item.ItemStack.func_77943_a(Unknown Source) [add.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) [mx.class:?]
        at thaumcraft.common.entities.ai.interact.AIUseItem.click(AIUseItem.java:158) [AIUseItem.class:?]
        at thaumcraft.common.entities.ai.interact.AIUseItem.func_75246_d(AIUseItem.java:99) [AIUseItem.class:?]
        at net.minecraft.entity.ai.EntityAITasks.func_75774_a(EntityAITasks.java:122) [uj.class:?]
        at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:582) [sw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2121) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:388) [sw.class:?]
        at thaumcraft.common.entities.golems.EntityGolemBase.func_70636_d(EntityGolemBase.java:354) [EntityGolemBase.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1954) [sv.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:213) [sw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:2740) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877) [mt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:2678) [ahb.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2480) [ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673) [mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
```

**Comment by SupaHam** [comment]
Not enough information.
