### ISSUE TITLE
Essentials Warn from version TeamCity is not compatible with Spigot last build ? Or Java 8 incompatible ?

### ISSUE THREAD

**Issue by comonier** [EssentialsX/Essentials#1183]
https://hub.spigotmc.org/jenkins/job/spigot-essentials/20/

`[00:45:05] [Server thread/WARN]: [Essentials] Task #139 for Essentials vTeamCity generated an exception
java.lang.NullPointerException
	at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:176) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:123) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:35) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]`

**Comment by comonier** [comment]
all time someone do login our logout ?
`[01:13:16] [Server thread/WARN]: [Essentials] Task #229 for Essentials vTeamCity generated an exception
java.lang.NullPointerException
	at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:171) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:123) ~[?:?]
	at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$2.run(EssentialsXMPPPlayerListener.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot111-java8.jar:git-Spigot-625bc00-d09304e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]`

**Comment by mdcfe** [comment]
This isn't support for the original Essentials plugin (2.14), nor Spigot Essentials, however it looks like you are running different versions of the plugin. For the latest builds of EssentialsX, [click here](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by comonier** [comment]
already discovery, it was from XMPP already remove it and it stop to warns... same after i change to EssentialsX - no problem just removed XMPP jar
