### ISSUE TITLE
Server crash on teleporting to unloaded chunks (/home)

### ISSUE THREAD

**Issue by soluciones-ya** [EssentialsX/Essentials#1185]
I don't speak english but i will try to explain.

I have the latest EssentialsX build. Tested with PaperSpigot, Spigot and Bukkit (all version 1.8.8)

The server crash occurs when a player uses /home to teleport to an unloaded (and possibly corrupted) chunk.

---->> force-disable-teleport-safety: true

if i set force-disable-teleport-safety to false, the crash is fixed.

Error:

[21:15:14] [Server thread/INFO]: Dominiq_Evans issued server command: /home casa
[21:15:17] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_121]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_121]
	at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:175) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:863) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by pop4959** [comment]
Let us know if this still happens on the latest version of Essentials in a new issue. I believe all crash bugs with home have been fixed by now.
