### ISSUE TITLE
/spawnmob giving error

### ISSUE THREAD

**Issue by SrEdqe** [EssentialsX/Essentials#1209]
Have got this error when doing command /spawnmob.

[18:59:39 ERROR]: Command spawnmob failed:
java.lang.NoClassDefFoundError: Could not initialize class com.earth2me.essentials.Mob
        at com.earth2me.essentials.SpawnMob.spawnmob(SpawnMob.java:109) ~[Essentials.jar:?]
        at com.earth2me.essentials.SpawnMob.spawnmob(SpawnMob.java:93) ~[Essentials.jar:?]
        at com.earth2me.essentials.commands.Commandspawnmob.run(Commandspawnmob.java:50) ~[Essentials.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) ~[Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:526) [Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:401) [Essentials.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_05]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_05]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_05]

**Server Version:** This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Pokechu22** [comment]
`Mob` is supposed to be version-compatible.  Unfortunately that error message doesn't describe _why_ it failed to load, only that it did fail - is there a second exception near that one?

Also, if possible you should update to 1.11.2 - 1.8.8 hasn't been updated in years and there are a number of bugfixes to the vanilla server, craftbukkit, and spigot that you're missing (some of which are fairly important).

**Comment by SrEdqe** [comment]
Updating to newer spigot version other guys will not be able to connect with older versions ( using viaVersions ). I fixed the problem downloading other Essentials plugin from not-trusted web-page, not the Jenkins one, and it worked.
