### ISSUE TITLE
/createkit causing error

### ISSUE THREAD

**Issue by NABrr** [EssentialsX/Essentials#1214]
I'm unable to update or create kits and receive the following error in console when I run the command, sorry for the length:

```
[15:06:29] [pool-91-thread-1/WARN]: javax.net.ssl.SSLException: Received fatal alert: internal_error
[15:06:29] [pool-91-thread-1/WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
[15:06:29] [pool-91-thread-1/WARN]: at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
[15:06:29] [pool-91-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
[15:06:29] [pool-91-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
[15:06:29] [pool-91-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[15:06:29] [pool-91-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[15:06:29] [pool-91-thread-1/WARN]: at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[15:06:29] [pool-91-thread-1/WARN]: at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[15:06:29] [pool-91-thread-1/WARN]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[15:06:29] [pool-91-thread-1/WARN]: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
[15:06:29] [pool-91-thread-1/WARN]: at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
[15:06:29] [pool-91-thread-1/WARN]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
[15:06:29] [pool-91-thread-1/WARN]: at com.earth2me.essentials.commands.Commandcreatekit$1.run(Commandcreatekit.java:137)
[15:06:29] [pool-91-thread-1/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:06:29] [pool-91-thread-1/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:06:29] [pool-91-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:06:29] [pool-91-thread-1/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:06:29] [pool-91-thread-1/WARN]: at java.lang.Thread.run(Thread.java:745)
```

I'd really like to be able to use the in-game command because the starter kit I'm using for new isn't good enough and required a major retweak to get it balanced with the server and I'm not entirely sure how to edit the kit manually and get the result I have made.

**Comment by Pokechu22** [comment]
Sounds like something's not correct with SSL certificates on the server.  If you have access to the command line on the server, can you run `curl --head https://gist.github.com` and paste the response?

You may also be able to work around this by setting `pastebin-createkit` to `false`, but do note that that *WILL* delete all of the comments in the config, so use it with caution.

**Comment by NABrr** [comment]
Unknown command, there's also no setting for pastebin anywhere. Do I need to reset the config?

**Comment by Pokechu22** [comment]
By the command line, I meant via ssh or similar, not in the place where you enter game commands (it's a bit confusing).

The pastebin setting was added in july 2016.  If you haven't created a new config since then, it won't be there, but you can still manually set it (just put `pastebin-createkit: false` somewhere at the top level).  You'll probably want to backup your config beforehand.

**Comment by NABrr** [comment]
I'm afraid it's a hosted server using a panel. I only have access to the server's console and files. I've tried adding the pastebin setting you mention, still gives the same error. I'm running `git-Spigot-54ec0b6-be9ef98` MC 1.11.2 with API 1.11.2-R0.1-Snapshot

**Comment by mdcfe** [comment]
Closing due to inactivity.

As far as I know, there isn't anything we can do about this issue, since the SSL error is down to your host.

If you need further assistance, feel free to respond to this issue and we'll reopen it.
