### ISSUE TITLE
Essentials is Erroring

### ISSUE THREAD

**Issue by Techno3600** [EssentialsX/Essentials#1224]
Look at this

29.04 17:32:39 [Server] WARN [Essentials] Task #1152 for Essentials v2.0.1-b469 generated an exception
29.04 17:32:39 [Server] INFO java.lang.NullPointerException
29.04 17:32:39 [Server] INFO at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:144) ~[?:?]
29.04 17:32:39 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?]
29.04 17:32:39 [Server] INFO at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$2.run(EssentialsXMPPPlayerListener.java:51) ~[?:?]
29.04 17:32:39 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.jar:git-Spigot-a3f6ea5-a2af8f0]
29.04 17:32:39 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-a3f6ea5-a2af8f0]
29.04 17:32:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.jar:git-Spigot-a3f6ea5-a2af8f0]
29.04 17:32:39 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-a3f6ea5-a2af8f0]
29.04 17:32:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.jar:git-Spigot-a3f6ea5-a2af8f0]
29.04 17:32:39 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.jar:git-Spigot-a3f6ea5-a2af8f0]
29.04 17:32:39 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Techno3600** [comment]
Someone better fix this

**Comment by Techno3600** [comment]
https://imgur.com/gallery/AhYVY

**Comment by Techno3600** [comment]
Also I need help with my player tab list
I can't seem to get my tab names to update with the prefixes in chat. I have my nickname limit set 25, the update-display (or whatever it is) true, and ignoring colors is set to true. Do you know why the display name is still not updating with my prefixes?

Thanks
Techno3600

**Comment by Techno3600** [comment]
And I still need help with my first problem

**Comment by iBurkeMC** [comment]
First problem: delete EssentialsXMPP.jar unless you're actually using XMPP (which if you are, I won't be able to help)

Second problem: change-playerlist: false needs to be true in the config.yml

**Comment by Techno3600** [comment]
It is true

**Comment by iBurkeMC** [comment]
Can you paste your plugins list?

**Comment by Techno3600** [comment]
04.05 02:44:29 [Server] INFO Plugins (34): WorldEdit, TitleAnnouncer, HealthBar, OfflineTeleporter, OpenInv, PlaceholderAPI, AdvancedBan, Broadcast, Modifyworld, EasyCarts, ProtocolLib, WorldGuard, iDisguise, UltraBar, PermissionsEx, MaintenanceMode, CreeperHeal, ItemJoin, Vault, StaffPlus, Boobah-PunishGUI, UndineMailer, MassiveCore, Essentials, CreativeGates, InfoBoardReborn, ChestCommands, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, HorseTpWithMe, AddLight, EssentialsSpawn

**Comment by iBurkeMC** [comment]
You'll need an additional plugin such as NameManager

**Comment by Techno3600** [comment]
I see that is a completley separate plugin which I have to manually change. Does it hook into Essentials or PEX?

And should I still have change-playerlist: true in my Config?

**Comment by iBurkeMC** [comment]
I don't believe it hooks into them specifically, but you can set up prefixes in the groups.yml file and set your own permission nodes to give to each group.

Keep in mind anyone opped or with the '*' node will have to manually be edited either in game, or in the players.yml file

**Comment by Techno3600** [comment]
Awesome. Do you know why it I sent erroring still!

**Comment by iBurkeMC** [comment]
The XMPP error? If you don't use XMPP, I would just recommend removing it.

**Comment by mdcfe** [comment]
Closing due to inactivity. If you need further assistance, feel free to respond to this issue and we'll reopen it.
