### ISSUE TITLE
Heeeey

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#1229]
```
[2017-05-04 14:43:51] Error calling the command /tpdeny
[2017-05-04 14:43:51] java.lang.NullPointerException
[2017-05-04 14:43:51] 	at com.earth2me.essentials.UserMap.getUser(UserMap.java:111)
[2017-05-04 14:43:51] 	at com.earth2me.essentials.Essentials.getUser(Essentials.java:583)
[2017-05-04 14:43:51] 	at com.earth2me.essentials.commands.Commandtpdeny.run(Commandtpdeny.java:16)
[2017-05-04 14:43:51] 	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146)
[2017-05-04 14:43:51] 	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:471)
[2017-05-04 14:43:51] 	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:381)
[2017-05-04 14:43:51] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[2017-05-04 14:43:51] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151)
[2017-05-04 14:43:51] 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:675)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1393)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1198)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[2017-05-04 14:43:51] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[2017-05-04 14:43:51] 	at java.util.concurrent.FutureTask.run(Unknown Source)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:830)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[2017-05-04 14:43:51] 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[2017-05-04 14:43:51] 	at java.lang.Thread.run(Unknown Source)
```

Ess v.2.0.1-b467, debug: true, Paper(Spigot) 1.11.2.
If player joins the server and then perform /tpdeny, in chat will "null".

**Comment by SupaHam** [comment]
This has been fixed in 4bfabaa. You can grab the fix from [build 470](https://ci.drtshock.net/job/EssentialsX/) on the CI server.
