### ISSUE TITLE
Exception error

### ISSUE THREAD

**Issue by Metisuneatn** [EssentialsX/Essentials#1240]
`[23:44:52] [Craft Scheduler Thread - 841/WARN]: [Essentials] Plugin Essentials v2.0.1-b370 generated an exception while executing task 100363821
java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.getSpawnOnJoinGroups()Ljava/util/List;
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75) ~[?:?]
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:67) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_latest.jar:git-Spigot-a3f6ea5-2453830]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot_latest.jar:git-Spigot-a3f6ea5-2453830]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

1.11.2 Not sure if this is related to a server crash at all but I dont think so

**Comment by Metisuneatn** [comment]
`[23:55:35] [Craft Scheduler Thread - 12/WARN]: [Essentials] Plugin Essentials v2.0.1-b370 generated an exception while executing task 3749
java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.getSpawnOnJoinGroups()Ljava/util/List;
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75) ~[?:?]
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:67) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_latest.jar:git-Spigot-a3f6ea5-2453830]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot_latest.jar:git-Spigot-a3f6ea5-2453830]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

A second one as well. I'm assuming it has something to do with the set spawns so I redid them and still the errors
