### ISSUE TITLE
EssentialsXSpawn throwing an error having something to do with getting the spawn for players on join.

### ISSUE THREAD

**Issue by The-Unnamed-Engineer** [EssentialsX/Essentials#1244]
So lately on my server I have noticed the console throwing a "NoSuchMethodError" every time a player joins.
Here is the entire error that the server throws
```
java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.getSpawnOnJoinGroups()Ljava/util/List;
at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75) ~[?:?]
at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:67) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar:git-Spigot-3fb9445-2b6c9f4]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by mdcfe** [comment]
What version of EssentialsX are you running? `/ess`

**Comment by DisTrugator** [comment]
2.0.1 - b472

**Comment by The-Unnamed-Engineer** [comment]
I am running 2.0.1-b469 I think.

**Comment by SupaHam** [comment]
Please download the latest EssentialsX from the [ci server](https://ci.drtshock.net).
