### ISSUE TITLE
change color

### ISSUE THREAD

**Issue by KeendyS** [EssentialsX/Essentials#1260]
[17:26:18 INFO]: Keendy issued server command: /nick &dsa
[17:26:18 WARN]: Missing translation key "nickNamesOnlyColorChanges" in translation file ru
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key nickNamesOnlyColorChanges
        at java.util.ResourceBundle.getObject(ResourceBundle.java:450) ~[?:1.8.0_101]
        at java.util.ResourceBundle.getObject(ResourceBundle.java:444) ~[?:1.8.0_101]
        at java.util.ResourceBundle.getString(ResourceBundle.java:407) ~[?:1.8.0_101]
        at com.earth2me.essentials.I18n.translate(I18n.java:64) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.I18n.tl(I18n.java:77) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.Commandnick.formatNickname(Commandnick.java:83) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.Commandnick.run(Commandnick.java:35) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:466) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:376) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-3fb9445-fecf4b4]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
>

**Comment by jaroslawjanas** [comment]
there must be an error in messages_ru.properties
[17:26:18 WARN]: Missing translation key "nickNamesOnlyColorChanges" in translation file ru
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key nickNamesOnlyColorChanges
Make sure you changed the lang file in config from en to ru. Check the file for any errors.

**Comment by pop4959** [comment]
The error doesn't help us. Please tell us exactly how to reproduce the problem, so we can replicate it and identify it properly. Create a new issue if you are still having this in the latest version of Essentials.
