### ISSUE TITLE
Herochat 6.0.0 premium error, cant use /msg without essentials error / conflict.

### ISSUE THREAD

**Issue by Jamesfle** [EssentialsX/Essentials#1296]
Always used Herochat with essentials before, but their new premium update something goes wrong with a /msg and a Essentials error is mentioned. Their DEV said come here, u are probably going to say go there, so...? xD

    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:435) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) [EssentialsX-2.0.1.jar:?]

Full paste here : [https://pastebin.com/Pj1iBiPY](https://pastebin.com/Pj1iBiPY)

**Comment by mdcfe** [comment]
```
Caused by: java.util.regex.PatternSyntaxException: Unmatched closing ')' near index 8
(\{\w+)\})
        ^
    at java.util.regex.Pattern.error(Pattern.java:1955) ~[?:1.8.0_91]
    at java.util.regex.Pattern.compile(Pattern.java:1700) ~[?:1.8.0_91]
    at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_91]
    at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_91]
    at com.dthielke.herochat.ConversationChannel.applyFormat(ConversationChannel.java:59) ~[?:?]
    at com.dthielke.herochat.ConversationChannel.processChat(ConversationChannel.java:181) ~[?:?]
    at com.dthielke.herochat.MessageHandler.handle(MessageHandler.java:160) ~[?:?]
    at com.dthielke.herochat.command.commands.MsgCommand.execute(MsgCommand.java:94) ~[?:?]
    at com.dthielke.herochat.command.CommandHandler.dispatch(CommandHandler.java:54) ~[?:?]
    at com.dthielke.herochat.Herochat.onCommand(Herochat.java:69) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-7d78b81-270755d]
    ... 18 more
```

This is the actual error - it's not related to EssentialsX.

**Comment by Jamesfle** [comment]
ok, i will go shove that back at him then lol xD
