### ISSUE TITLE
Essential Spawn error

### ISSUE THREAD

**Issue by Kiwis2451** [EssentialsX/Essentials#1302]
[21:57:40] [Craft Scheduler Thread - 25/WARN]: [Essentials] Plugin Essentials v2.0.1-b370 generated an exception while executing task 1632
java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.getSpawnOnJoinGroups()Ljava/util/List;
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75) ~[?:?]
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:67) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-3fb9445-6e3cec8]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_131]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by mdcfe** [comment]
Update to the latest EssentialsX and EssentialsXSpawn versions from [here](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).
