### ISSUE TITLE
Error message on Essentials Chat

### ISSUE THREAD

**Issue by ApertureDevelopment** [EssentialsX/Essentials#1342]
Version: CB 1.12
When does the error Happen?: Always when someone types something

Error:

pool-3-thread-2/WARN]: [Essentials] Plugin Essentials v2.0.1-b491 generated an exception while executing task 17
java.lang.NullPointerException: null
	at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:327) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]
	at com.earth2me.essentials.User.getGroup(User.java:624) ~[?:?]
	at com.earth2me.essentials.textreader.TextInput.<init>(TextInput.java:28) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.delayedJoin(EssentialsPlayerListener.java:209) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener$1.run(EssentialsPlayerListener.java:179) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[22:05:26] [Netty Epoll Server IO #1/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.0.1-b491
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:480) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1251) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1200) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:117) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:317) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:1) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.milkbowl.vault.chat.plugins.Chat_GroupManager.getPlayerPrefix(Chat_GroupManager.java:271) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:67) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getPrefix(AbstractVaultHandler.java:48) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getPrefix(PermissionsHandler.java:68) ~[?:?]
	at com.earth2me.essentials.User.getNick(User.java:312) ~[?:?]
	at com.earth2me.essentials.User.getNick(User.java:281) ~[?:?]
	at com.earth2me.essentials.User.setDisplayNick(User.java:341) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:88) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	... 54 more
[22:05:26] [Netty Epoll Server IO #1/ERROR]: Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.0.1-b491
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:480) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1251) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1200) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:117) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:317) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at net.minecraft.server.v1_12_R1.NetworkManager.channelRead0(NetworkManager.java:1) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:327) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]
	at com.earth2me.essentials.User.getGroup(User.java:624) ~[?:?]
	at com.earth2me.essentials.chat.EssentialsChatPlayerListenerLowest.onPlayerChat(EssentialsChatPlayerListenerLowest.java:42) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.jar:git-Bukkit-0481ae9]
	... 54 more

**Comment by ApertureDevelopment** [comment]
Wrong Developer. I meant to sent this to the GroupManagerX developers
