### ISSUE TITLE
Essentials generate error when I use luckperms

### ISSUE THREAD

**Issue by RikoDEV** [EssentialsX/Essentials#1350]
When I install LuckPerms and latest essentialsx build I see this error in console:

LuckPerms: https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/

```
[15:53:08] [Server thread/WARN]: [Essentials] Task #4619662 for Essentials v2.0.1-b491 generated an exception
java.lang.NullPointerException: null
	at me.lucko.luckperms.bukkit.model.LPPermissible.calculateContexts(LPPermissible.java:132) ~[?:?]
	at me.lucko.luckperms.bukkit.model.LPPermissible.hasPermission(LPPermissible.java:159) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:112) ~[patched_1.12.jar:git-Paper-1129]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcast(CraftServer.java:1312) ~[patched_1.12.jar:git-Paper-1129]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcastMessage(CraftServer.java:453) ~[patched_1.12.jar:git-Paper-1129]
	at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:260) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.jar:git-Paper-1129]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356) [patched_1.12.jar:git-Paper-1129]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832) [patched_1.12.jar:git-Paper-1129]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) [patched_1.12.jar:git-Paper-1129]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766) [patched_1.12.jar:git-Paper-1129]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664) [patched_1.12.jar:git-Paper-1129]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by Shivelight** [comment]
Might be related.. 

```
[14:55:47] [Paper Watchdog Thread/ERROR]: The server has stopped responding!
[15:02:14] [Paper Watchdog Thread/ERROR]: Please report this to https://aquifermc.org/
[15:02:14] [Paper Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports
[15:02:14] [Paper Watchdog Thread/ERROR]: Paper version: git-Paper-1132 (MC: 1.12)
[15:02:14] [Paper Watchdog Thread/ERROR]: ------------------------------
[15:02:14] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[15:02:14] [Paper Watchdog Thread/ERROR]: ------------------------------
[15:02:14] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[15:02:14] [Async Chat Thread - #220/INFO]: [GriefPrevention] Muted repeat message.
[15:02:14] [Paper Watchdog Thread/ERROR]: 	PID: 18 | Suspended: false | Native: false | State: RUNNABLE
[15:02:14] [Paper Watchdog Thread/ERROR]: 	Stack:
[15:02:14] [Paper Watchdog Thread/ERROR]: 		sun.misc.Unsafe.unpark(Native Method)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1649)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:976)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:815)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1868)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		me.lucko.luckperms.common.caching.UserCache.getPermissionData(UserCache.java:94)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		me.lucko.luckperms.bukkit.model.LPPermissible.hasPermission(LPPermissible.java:159)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:112)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcast(CraftServer.java:1312)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.CraftServer.broadcastMessage(CraftServer.java:453)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:260)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:832)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:766)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:664)
[15:02:14] [Paper Watchdog Thread/ERROR]: 		java.lang.Thread.run(Thread.java:745)
```

**Comment by mdcfe** [comment]
The second report definitely looks like a LuckPerms issue. The first looks similar to another issue fixed by a PR that was submitted recently.

**Comment by lucko** [comment]
Both issues are LP, not Essentials. I'll reply on the other ticket.

**Comment by SupaHam** [comment]
I've made a recent commit that aims to terminate this issue for all other permission plugins to encourage the development of them. Please set `use-bukkit-permissions` to `true in your `Essentials/config.yml`.

Thank you and sorry for the inconvenience.
