### ISSUE TITLE
Unhandled exception executing command

### ISSUE THREAD

**Issue by tbonge** [EssentialsX/Essentials#1352]
All commands are giving an unhandled exception when executed. This is a new 1.12 install on Debian with no other extensions installed. 

[13:36:37] [Server thread/WARN]: Unexpected exception while parsing console command "broadcast test"
org.bukkit.command.CommandException: Unhandled exception executing command 'broadcast' in plugin Essentials v2.0.1-b493
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:644) ~[spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:630) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:443) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:431) ~[?:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.jar:git-Spigot-23b6354-0481ae9]
... 8 more

**Comment by tbonge** [comment]
Not an issue, silly me, permissions were set wrong on plugins folder.
