### ISSUE TITLE
Can't unban even as op'd

### ISSUE THREAD

**Issue by Metisuneatn** [EssentialsX/Essentials#1401]
Spigot 1.12

I had this before but couldn't find this error in time to fix it. This ONLY happens for this one single person I've been trying to unban. 

```java
[04:30:54] [Server thread/INFO]: KoKoBerry issued server command: /unban PhatTiddiesMcGee
[04:30:54] [Server thread/INFO]: [Essentials] checking if KoKoBerry has essentials.mail - true
[04:30:54] [Server thread/INFO]: [Essentials] checking if KoKoBerry has essentials.unban - true
[04:30:54] [Server thread/INFO]: [Essentials] checking if KoKoBerry can afford charge.
[04:30:54] [Server thread/INFO]: [Essentials] calculated command (unban) cost for KoKoBerry as 0
[04:30:55] [Server thread/INFO]: Error calling the command /unban
java.lang.NullPointerException: null
	at net.minecraft.server.v1_12_R1.GameProfileBanList.b(SourceFile:34) ~[spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.GameProfileBanList.a(SourceFile:8) ~[spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.JsonList.remove(JsonList.java:91) ~[spigot_latest.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.craftbukkit.v1_12_R1.CraftProfileBanList.pardon(CraftProfileBanList.java:97) ~[spigot_latest.jar:git-Spigot-7228328-af1c013]
	at com.earth2me.essentials.commands.Commandunban.run(Commandunban.java:29) ~[EssentialsX-2.0.1%20(4).jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:162) ~[EssentialsX-2.0.1%20(4).jar:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) ~[EssentialsX-2.0.1%20(4).jar:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:511) [EssentialsX-2.0.1%20(4).jar:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424) [EssentialsX-2.0.1%20(4).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot_latest.jar:git-Spigot-7228328-af1c013]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[04:30:55] [Server thread/WARN]: java.lang.NullPointerException
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.GameProfileBanList.b(SourceFile:34)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.GameProfileBanList.a(SourceFile:8)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.JsonList.remove(JsonList.java:91)
[04:30:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftProfileBanList.pardon(CraftProfileBanList.java:97)
[04:30:55] [Server thread/WARN]: 	at com.earth2me.essentials.commands.Commandunban.run(Commandunban.java:29)
[04:30:55] [Server thread/WARN]: 	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:162)
[04:30:55] [Server thread/WARN]: 	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157)
[04:30:55] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:511)
[04:30:55] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:424)
[04:30:55] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[04:30:55] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[04:30:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1385)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[04:30:55] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[04:30:55] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
[04:30:55] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
[04:30:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Metisuneatn** [comment]
Update: Now is happening for 3 players. One who was just recently banned

**Comment by CheatSupport** [comment]
@Metisuneatn try /minecraft:pardon (name) and /minecraft:pardon-ip (name)

**Comment by mdcfe** [comment]
What other plugins do you have installed?

**Comment by Metisuneatn** [comment]
/minecraft:pardon says "Could not unban player" for the player I posted in the error. It works on the other two I tried on.

Theres a large list of plugins but none involve themselves with banning/unbanning.

**Comment by Metisuneatn** [comment]
Now this is happening to several players on my server. We were able to recreate this with only EssentialsX, vault, and towny on the test server

**Comment by mdcfe** [comment]
In your `banned-players.json` file, do the entries for the players you can't unban look significantly different to the entries for the players you *can* unban?

**Comment by Metisuneatn** [comment]
Nope nothing stands out as different for these players

**Comment by Metisuneatn** [comment]
I'm now at 14 people I cannot unban. Tempbans and perm bans

**Comment by mdcfe** [comment]
Have you updated Spigot since this started happening?

**Comment by Metisuneatn** [comment]
Yep, going to do 1.12.1 soon as well

**Comment by mdcfe** [comment]
Closing due to inactivity. If you need further assistance, feel free to respond to this issue and we'll reopen it.

**Comment by C4K3** [comment]
In case anybody finds this from google: I just had the same problem, and it turned out to be because the player had changed their name since being banned.

So using /pardon on the current name gave the 'Could not unban player' message. But it worked when I instead used the name they had when they were banned (and which was listed in banned-players.json)

**Comment by ghost** [comment]
This is why you have to use UUIDs to unban people.

**Comment by Metisuneatn** [comment]
Its a shame the UUID doesnt work either
    On Wednesday, April 25, 2018, 1:12:54 PM EDT, Dan9er <notifications@github.com> wrote:  
 
 
This is why you have to use UUIDs to unban people.
