### ISSUE TITLE
Essentials error [Fixed]

### ISSUE THREAD

**Issue by teamAngelic** [EssentialsX/Essentials#1413]
[03:25:37 WARN]: org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b370 generated an exception while executing task 796509
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.getSpawnOnJoinGroups()Ljava/util/List;
        at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75)
        at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:67)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by mdcfe** [comment]
Update both EssentialsX and any other modules you have installed from [the CI server](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by teamAngelic** [comment]
Done, fixed thank you.
