### ISSUE TITLE
Console Errors For Banners

### ISSUE THREAD

**Issue by Ac3dUd3** [EssentialsX/Essentials#1439]
Contact drtshock of essentialsx and show him this:
at com.earth2me.essentials.MetaItemStack.addBannerMeta(MetaItemStack.java:494)
18:25:44 [WARN] at com.earth2me.essentials.MetaItemStack.addStringMeta(MetaItemStack.java:222)
18:25:44 [WARN] at com.earth2me.essentials.MetaItemStack.parseStringMeta(MetaItemStack.java:134)

Unfortunately this is a problem with essentials and not kitpreview :/ looks like something to do with banners?

EssentialsX version (`/essentials`): 20:25:28 [INFO] Essentials version 2.0.1-b488

Server software (`/version`): 20:25:41 [INFO] This server is running CraftBukkit version git-Spigot-596221b-57c323a (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

EssentialsX config (if applicable): N/A

**Comment by mdcfe** [comment]
Please paste the entire error as a Gist ~~of coffee~~ or code block - this doesn't tell us enough about what happened.

**Comment by Ac3dUd3** [comment]
```
18:25:37 [INFO] Tyrant1717 issued server command: /kit
18:25:44 [WARN] java.lang.NullPointerException
18:25:44 [WARN]         at org.bukkit.craftbukkit.v1_12_R1.block.CraftBanner.update(CraftBanner.java:103)
18:25:44 [WARN]         at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:150)
18:25:44 [WARN]         at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:146)
18:25:44 [WARN]         at com.earth2me.essentials.MetaItemStack.addBannerMeta(MetaItemStack.java:494)
18:25:44 [WARN]         at com.earth2me.essentials.MetaItemStack.addStringMeta(MetaItemStack.java:222)
18:25:44 [WARN]         at com.earth2me.essentials.MetaItemStack.parseStringMeta(MetaItemStack.java:134)
18:25:44 [WARN]         at com.songoda.kitpreview.sf9afu0afuas0fjasmerpoweja0eiuad08audas0fuafaduya98dayhsaonjenr398rha9f8ayhfas80fsfa0sfafaasfkasjfsdas89dasyd3wnldjhwopij120duj80d0ssjd.fasjdfhasds87shcsadfh8eaeaoijada0dusafafafduya98dayhsaonjenr398rha9f8ayhfas80fsfa0sfafaduya98dayhsaonjenr398rha9f8ayhfas80fsfa0sfafa.fasjdfhasds87shcsadfh8eaeaoijada0dusafafafduya98dayhsaonjenr398rha9f8ayhfas80fsfa0sfafaduya98dayhsaonjenr398rha9f8ayhfas80fsfa0sfafa(SourceFile:95)
18:25:44 [WARN]         at com.songoda.kitpreview.asfkasjfsdas89dasyd3wnldjhwopij120duj80d0ssjdasfkasjfsdas89dasyd3wnldjhwopij120duj80d0ssjdaxcxxxa0a9sdusa0duasfsfuas0ffys088fsa90s8fsaf.sa90s8fsaf08sayfa97dya9ydh92dyha987dya9sdysfaduya98dayhsaonjenr398rha9f8ayhfas80fsfa0sfafaaxcxxxa0a9sdusa0duasfsfuas0ffys088fsa90s8fsaf.fasjdfhasds87shcsadfh8eaeaoijada0dusafafafduya98dayhsaonjenr398rha9f8ayhfas80fsfa0sfafaduya98dayhsaonjenr398rha9f8ayhfas80fsfa0sfafa(SourceFile:174)
18:25:44 [WARN]         at com.songoda.kitpreview.Handlers.CommandHandler.onCommand(SourceFile:283)
18:25:44 [WARN]         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
18:25:44 [WARN]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
18:25:44 [WARN]         at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:641)
18:25:44 [WARN]         at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:574)
18:25:44 [WARN]         at me.clip.deluxemenus.DeluxeMenusConfig$1.onClick(DeluxeMenusConfig.java:1511)
18:25:44 [WARN]         at me.clip.deluxemenus.PlayerListener.onClick(PlayerListener.java:159)
18:25:44 [WARN]         at sun.reflect.GeneratedMethodAccessor295.invoke(Unknown Source)
18:25:44 [WARN]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:25:44 [WARN]         at java.lang.reflect.Method.invoke(Method.java:498)
18:25:44 [WARN]         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
18:25:44 [WARN]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
18:25:44 [WARN]         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
18:25:44 [WARN]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1877)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
18:25:44 [WARN]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18:25:44 [WARN]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
18:25:44 [WARN]         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
18:25:44 [WARN]         at java.lang.Thread.run(Thread.java:748)
18:26:32 [INFO] Tyrant1717 lost connection: Disconnected
```

**Comment by Ac3dUd3** [comment]
https://hastebin.com/peyojoxake.vbs

**Comment by mdcfe** [comment]
Unfortunately there's no way for us to know what caused the issue as we don't know with what `parseStringMeta` is called and I'm not prepared to debug an interaction with a closed source plugin, especially considering the fact it seems to be obfuscated. If the author of KitPreview can shed some light on why they think that this is an EssentialsX problem then it would be much appreciated.

**Comment by mdcfe** [comment]
Closing due to inactivity. If you need further assistance, feel free to respond and I'll reopen this.
