### ISSUE TITLE
Spade and air bug.

### ISSUE THREAD

**Issue by Xanusek** [EssentialsX/Essentials#1489]
EssentialsX version (`/essentials`): 
2.0.1-b488

Server software (`/version`): 
Paper version git-Paper-1188 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

It occurs when im using spade item at air block (nowhere):

`[21:23:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract(SignPlayerListener.java:41) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor247.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[paper112.jar:git-Paper-1188]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paper112.jar:git-Paper-1188]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paper112.jar:git-Paper-1188]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[paper112.jar:git-Paper-1188]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[paper112.jar:git-Paper-1188]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[paper112.jar:git-Paper-1188]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) ~[paper112.jar:git-Paper-1188]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) ~[paper112.jar:git-Paper-1188]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:987) ~[paper112.jar:git-Paper-1188]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[paper112.jar:git-Paper-1188]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[paper112.jar:git-Paper-1188]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[paper112.jar:git-Paper-1188]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [paper112.jar:git-Paper-1188]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [paper112.jar:git-Paper-1188]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [paper112.jar:git-Paper-1188]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [paper112.jar:git-Paper-1188]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [paper112.jar:git-Paper-1188]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`

**Comment by mdcfe** [comment]
This has already been fixed - grab the latest build from the [build server](https://ci.drtshock.net).
