### ISSUE TITLE
Getting error when player joins

### ISSUE THREAD

**Issue by Rukes** [EssentialsX/Essentials#1505]
```
[02:02:49 INFO]: UUID of player Mp4_SvK is 8aee17d5-9ccf-339e-87b5-aa7512ecb740
[02:02:49 INFO]: Mp4_SvK[/82.208.17.82:40566] logged in with entity id 48009 at ([SpawnWorld]-215.5, 58.5, 58.5)
[02:02:49 WARN]: [Essentials] Task #13299 for Essentials v2.0.1-b525 generated an exception
java.lang.NullPointerException: null
at com.earth2me.essentials.UserData.getHome(UserData.java:175) ~[?:?]
at com.earth2me.essentials.EssentialsPlayerListener.updateCompass(EssentialsPlayerListener.java:351) ~[?:?]
at com.earth2me.essentials.EssentialsPlayerListener.access$300(EssentialsPlayerListener.java:50) ~[?:?]
at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:234) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-65e8124-357b573]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [minecraft_server.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-65e8124-357b573]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-65e8124-357b573]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

EssentialsX version (`/essentials`): 2.0.1-b525 (latest build)

Server software (`/version`): This server is running CraftBukkit version git-Spigot-65e8124-357b573 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

EssentialsX config (if applicable): I think you don't need it

**Comment by mdcfe** [comment]
Could you paste your config on [Gist](https://gist.github.com) anyway?

Does this happen every single time a player joins?

**Comment by Rukes** [comment]
This happens when only one specified player joins, "Mp4_SvK", idk why O.o
Config: https://gist.github.com/Rukes/e98cdd36135f54b41eb19a0b680bf5eb

**Comment by LaxWasHere** [comment]
Go to plugins/Essentials/userdata folder, find 8aee17d5-9ccf-339e-87b5-aa7512ecb740.yml and delete it.

**Comment by mdcfe** [comment]
^ *after* copying it somewhere to back it up, in case you need to copy days back over for that player.

**Comment by Rukes** [comment]
Umm, if I try to open that folder via FTP client it will crash, cuz there are about 57000 files. Is there other way?

**Comment by mdcfe** [comment]
If you have SSH access, `cd` to that directory and `rm 8aee17d5-9ccf-339e-87b5-aa7512ecb740.yml`.

**Comment by Rukes** [comment]
No, I haven't :/

**Comment by LaxWasHere** [comment]
Create an empty 8aee17d5-9ccf-339e-87b5-aa7512ecb740.yml and put it in userdata.

**Comment by mdcfe** [comment]
Alternatively, try running `/essentials reset <player>`.

**Comment by Rukes** [comment]
Yup, @LaxWasHere worked, thanks :+1:
