### ISSUE TITLE
error enabling essentials

### ISSUE THREAD

**Issue by SliderKP** [EssentialsX/Essentials#1537]
[03:03:39 WARN]: [Essentials] Plugin Essentials v2.0.1-b488 generated an exception while executing task 99
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register com.earth2me.essentials.Jails$JailListener@3171be7b while not enabled
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:524) ~[overcraft.jar:git-Spigot-7d78b81-70bc70b]
        at com.earth2me.essentials.Jails.registerListeners(Jails.java:47) ~[?:?]
        at com.earth2me.essentials.Jails.checkRegister(Jails.java:75) ~[?:?]
        at com.earth2me.essentials.Jails.finishRead(Jails.java:60) ~[?:?]
        at com.earth2me.essentials.storage.AsyncStorageObjectHolder$StorageObjectDataReader.onSuccess(AsyncStorageObjectHolder.java:118) ~[?:?]
        at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:34) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[overcraft.jar:git-Spigot-7d78b81-70bc70b]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [overcraft.jar:git-Spigot-7d78b81-70bc70b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

spigot 1.11.2 (i try in 1.12 and not working)

i'm using essentials mysql storage this can be the problem?

**Comment by mdcfe** [comment]
Start your server, run the commands `plugins`, `essentials` and `version` **in your server console** (*not* in-game), then stop your server and paste the `logs/latest.log` file on [Gist](https://gist.github.com/).

**Comment by wyatt-herkamp** [comment]
@SliderKP please try using the latest build. Then get back to us.

**Comment by mdcfe** [comment]
Closing due to inactivity and a lack of response; if this is still a problem, feel free to reopen the issue.
