### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by kingdom84521** [EssentialsX/Essentials#1549]
EssentialsX version (`/essentials`): 2.0.1-b488

Server software (`/version`):1.12.1 

EssentialsX config (if applicable): 

log on server cmd: 
[12:07:21 WARN]: [Essentials] Task #14 for Essentials v2.0.1-b529 generated an exception
java.lang.NullPointerException: null
        at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:148) ~[?:?]
        at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?]
        at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:31) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[12:07:21 WARN]: File motd.txt does not exist. Creating one for you.
[12:07:21 INFO]: 創建空的配置:F:\GAMES\MINECRAFT\connect\server_1\plugins\Essentials\userdata\c2ecbc63-ffa9-3ff8-bdfe-0e630159a8dd.yml
[12:07:52 INFO]: YumekuiiNight lost connection: Disconnected
[12:07:53 INFO]: YumekuiiNight left the game
[12:07:53 WARN]: [Essentials] Task #18 for Essentials v2.0.1-b529 generated an exception
java.lang.NullPointerException: null
        at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:144) ~[?:?]
        at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?]
        at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$2.run(EssentialsXMPPPlayerListener.java:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.1.jar:git-Bukkit-876d22c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

explain:
when i login or logout， this warning will pop up。Although it is warning not error，i'm still wondering if it will do anything to server.

**Comment by mdcfe** [comment]
Are you using XMPP? If not, you don't need EssentialsXXMPP.

**Comment by Tsuser1** [comment]
@md678685 is correct, I've noticed that if you don't configure XMPP it causes strange errors like this. I suggest removing EssentialsXMPP if you don't know what it is/don't use it.

**Comment by mdcfe** [comment]
Closing due to lack of response. If this is still a problem, feel free to reopen the issue.
