### ISSUE TITLE
Boats cause errors and lag with Minecraft 1.12.2

### ISSUE THREAD

**Issue by DeathIsUndead** [EssentialsX/Essentials#1559]
Boats seem to cause errors on my server, and the console is spitting out errors about EssentialsX.
EssentialsX version : 2.0.1-b488

Server software : Spigot 7754231-94b0980 MC 1.12.2 Latest Release

EssentialsX config is added in the link below.

https://gist.github.com/DeathIsUndead/8df9c176fce621654cbbccfb84a7516b

**Comment by Kakifrucht** [comment]
What errors?

**Comment by DeathIsUndead** [comment]
Sorry, it's in the link as well. It said to post the console log in that,so I put the configs and the console log in there.

**Comment by DeathIsUndead** [comment]
```
19.09 17:35:36 [Server] ERROR Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488
19.09 17:35:36 [Server] INFO org.bukkit.event.EventException: null
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:989) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
19.09 17:35:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
19.09 17:35:36 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
19.09 17:35:36 [Server] INFO at com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract(SignPlayerListener.java:41) ~[?:?]
19.09 17:35:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?:?]
19.09 17:35:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
19.09 17:35:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO ... 18 more
19.09 17:35:36 [Server] ERROR Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488
19.09 17:35:36 [Server] INFO org.bukkit.event.EventException: null
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:989) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
19.09 17:35:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.jar:git-Spigot-7754231-94b0980]
19.09 17:35:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
19.09 17:35:36 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;

```

**Comment by mdcfe** [comment]
This was fixed in a newer version - update EssentialsX to the latest version from the [build server](https://ci.drtshock.net/job/EssentialsX/lastSuccessfulBuild).

**Comment by DeathIsUndead** [comment]
That fixed it, thanks!
