### ISSUE TITLE
PlayerInteractEvent

### ISSUE THREAD

**Issue by tyrus7141** [EssentialsX/Essentials#1618]
Getting this error:

[01:15:06 ERROR]: Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:955) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(SourceFile:32) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(SourceFile:9) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
        at com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract(SignPlayerListener.java:41) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit-1.12.2.jar:git-Bukkit-53fccdf]
        ... 18 more

Server software (`/version`): Craftbukkit 1.12.1 (git-Bukkit-53fccdf)

**Comment by mdcfe** [comment]
Update EssentialsX to the [latest version](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).
