### ISSUE TITLE
Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488

### ISSUE THREAD

**Issue by SilvanBaach** [EssentialsX/Essentials#1671]
EssentialsX version (`/essentials`):  v2.0.1-b488

Server software (`/version`):  Spigot 1.12.1

EssentialsX config (if applicable): 

Hi guys

My console is spamed by the following error:

[20:37:40] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Essentials v2.0.1-b488
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:234) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:201) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:197) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:983) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract(SignPlayerListener.java:41) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-edd0396-20ab5d3]
	... 18 more

My plugin list: 

Plugins (46): CleanroomGenerator, WorldEdit, EggCatcher, KeepItems, LogBlock, MythicLib, ArmorStandEditor, BukkitCompat, PowerElytra, NametagEdit, Votifier, ProtocolLib, WorldGuard, DeathMessages, PermissionsEx, SuperbVote, mcMMO, Tablist, AntiBotAttack, Vault, ZavAutoMessager, MyCommand, ButtonWarp, Essentials, CompatNoCheatPlus, LWC, NoCheatPlus, TreasureChest, ASkyBlock, EssentialsProtect, EssentialsChat, EssentialsSpawn, Statz, Autorank, Multiverse-Core, SkinsRestorer, MythicMobs, Multiverse-Inventories, Multiverse-Portals, AuthMe, MobArena, Jobs, HolographicDisplays, CommandSigns, MythicArtifacts, CreeperHeal

Can someone help me? If you need more Information just say it!

-navlis3

**Comment by Kakifrucht** [comment]
[Update to the latest version.](http://ci.ender.zone/job/EssentialsX/)
