### ISSUE TITLE
Failed to display NaN: null something to do with Mobhunting?

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1765]
EssentialsX is spamming the utter hell out of my console.

Both on the latest 
Paper Spigot 12.2 1298 (latest)
EssentialsX b570 (latest)

```
[17:37:39] [Server thread/WARN]: [Essentials] Failed to display NaN: null
java.lang.NumberFormatException: null
	at java.math.BigDecimal.<init>(BigDecimal.java:494) ~[?:1.8.0_151]
	at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[?:1.8.0_151]
	at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[?:1.8.0_151]
	at java.math.BigDecimal.valueOf(BigDecimal.java:1274) ~[?:1.8.0_151]
	at com.earth2me.essentials.api.Economy.format(Economy.java:330) ~[EssentialsX-2.0.1.jar:?]
	at net.milkbowl.vault.economy.plugins.Economy_Essentials.format(Economy_Essentials.java:207) ~[Vault.jar:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1383) ~[MobHunting.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.2.jar:git-Paper-1298]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1298]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1298]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1298]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1298]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:396) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.EntityLiving.die(EntityLiving.java:1137) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.EntityLiving.damageEntity(EntityLiving.java:979) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.EntityMonster.damageEntity(EntityMonster.java:44) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.EntityHuman.attack(EntityHuman.java:1021) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.EntityPlayer.attack(EntityPlayer.java:1352) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1703) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1298]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1298]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by LaxWasHere** [comment]
Try removing your mobhunting plugin?

**Comment by caojohnny** [comment]
This is not a problem with essentials.

**Comment by drtshock** [comment]
This is an error that we're throwing because we were passed an invalid value to the economy format method. Open a ticket with mob hunt or whichever plugin is hooking into essentials eco incorrectly.

https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/api/Economy.java#L328

**Comment by TomLewis** [comment]
I opened a ticket with the MobHunting plugin as I referenced above and it was fixed. Thank you.
