### ISSUE TITLE
Disposal improperly loaded

### ISSUE THREAD

**Issue by SlimeDog** [EssentialsX/Essentials#1791]
Spigot 1.12.2
EssentialsX 2.0.1-b582

```
/essentials:disposal
```
elicits
```
[05:36:41 INFO]: {player name elided} issued server command: /essentials:disposal
[05:36:41 ERROR]: Command essentials:disposal is improperly loaded.
java.lang.ClassNotFoundException: com.earth2me.essentials.commands.Commanddisposal
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:489) [EssentialsX-2.0.1-b582.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:432) [EssentialsX-2.0.1-b582.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar-2018-01-21-1724:git-Spigot-4bd94dc-bdcc7c7]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by mdcfe** [comment]
Just realise what causes this: `CommandDisposal.java` shouldn't have a capitalised `D` in the middle.

**Comment by mdcfe** [comment]
~~This has been fixed in build 584 - get the latest build from the [build server](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/).~~

**Comment by mdcfe** [comment]
Reopening until fixed properly.

**Comment by mdcfe** [comment]
This is [actually fixed](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/) now.

**Comment by SlimeDog** [comment]
Confirmed fixed in build 584.
