### ISSUE TITLE
org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer cannot be cast to com.earth2me.essentials.OfflinePlayer

### ISSUE THREAD

**Issue by CodeCrafter47** [EssentialsX/Essentials#201]
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer cannot be cast to com.earth2me.essentials.OfflinePlayer
    at com.earth2me.essentials.Essentials.getOfflineUser(Essentials.java:551)
    at com.earth2me.essentials.Essentials.getUser(Essentials.java:534)
    at com.earth2me.essentials.api.Economy.getUserByName(Economy.java:67)
    at com.earth2me.essentials.api.Economy.getMoneyExact(Economy.java:85)
    at com.earth2me.essentials.api.Economy.getMoney(Economy.java:81)
    at net.milkbowl.vault.economy.plugins.Economy_Essentials.getBalance(Economy_Essentials.java:78)
    at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20)

**Comment by Kakifrucht** [comment]
Version of Vault you are using?

**Comment by CodeCrafter47** [comment]
Can't give you that one.

I recently added an automatic bug reporting system to my plugin which is how I got this StackTrace.

**Comment by FlippantCactus** [comment]
You can just do /ver <Vault> in game... A good bug reporting system would capture the whole log, filter out crap and pastebin it.

**Comment by CodeCrafter47** [comment]
Well then my bug reporting system is good I guess. If this is not helpful I'll just close it.

**Comment by FlippantCactus** [comment]
We just need versions of plugins to help

**Comment by CodeCrafter47** [comment]
I guess I can close this.
