### ISSUE TITLE
EssentialSpawn pls help

### ISSUE THREAD

**Issue by iloverussia** [EssentialsX/Essentials#2014]
Guys all hello, do not judge strictly for my post in a broken language, I'm writing here through an interpreter, because I'm Russian.
Please edit EssentialSpawn, I have Spigot 1.12 and EssentialsX, but it does not have EssentialSpawn and the old one gives an error on the second start after the spawn point assignment (can not overwrite spawn.yml) I ask you to edit this plugin, we all really need it!
Many thanks to you for your work! The plugin is just great!
Once again for those who did not understand what I wrote :) - when I install the EssentialSpawn plugin, I start the server, I go to it install the spawn point - I die and I appear at the spawn point.
I reboot the server and in the console gives an error (can not overwrite spawn.yml) and the server does not work :(

**Comment by iloverussia** [comment]
`[23:09:26] [Craft Scheduler Thread - 5/WARN]: [Essentials] Plugin Essentials v2.0.1-b488 generated an exception while executing task 19
org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:com.earth2me.essentials.settings.Spawns; exception=java.lang.NoSuchFieldException: typeDefinitions
in 'reader', line 1, column 1:
spawns: 
^

at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:313) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:467) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:41) ~[?:?]
at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:33) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: org.yaml.snakeyaml.error.YAMLException: java.lang.NoSuchFieldException: typeDefinitions
at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.constructJavaBean2ndStep(BukkitConstructor.java:231) ~[?:?]
at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:217) ~[?:?]
at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
... 13 more
Caused by: java.lang.NoSuchFieldException: typeDefinitions
at java.lang.Class.getDeclaredField(Class.java:2070) ~[?:1.8.0_131]
at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.constructJavaBean2ndStep(BukkitConstructor.java:224) ~[?:?]
at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:217) ~[?:?]
at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308) ~[minecraft_server.jar:git-Spigot-c3093ef-7e94e65]
... 13 more`

**Comment by Xeyame** [comment]
deleting the /plugins/Essentials/spawn.yml should solve this. This deletes all your Essentials spawn locations, but it doesn't look like you have any (as you are trying to set one). Delete the file while the server is not running.

**Comment by iloverussia** [comment]
The thing is that I delete it and while spawn.yml is not in the folder with the plugin essentailsX the server runs without problems ... the spawn point is set and everything is going to spawn well ... as soon as I restart the server it swears that it can not overwrite spawn.yml

**Comment by LaxWasHere** [comment]
The EssentialsX build you are using is outdated. Please go to https://ci.ender.zone/job/EssentialsX/ and download the latest build.

**Comment by iloverussia** [comment]
thank you! ... I'll come home at night to try to establish

**Comment by iloverussia** [comment]
Thank you very much!!!! I suffered 3 days with this problem, all plugins for spawn tried on dev.bukkit .... and nothing happened ... cool :)
