### ISSUE TITLE
Not used in the version 1.13

### ISSUE THREAD

**Issue by NyanMeow** [EssentialsX/Essentials#2074]
[20:59:37] [Server thread/INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[20:59:37] [Server thread/ERROR]: java.lang.NumberFormatException: For input string: "stone"
[20:59:37] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "stone"
[20:59:37] [Server thread/WARN]: 	at java.lang.NumberFormatException.forInputString(Unknown Source)
[20:59:37] [Server thread/WARN]: 	at java.lang.Integer.parseInt(Unknown Source)
[20:59:37] [Server thread/WARN]: 	at java.lang.Integer.parseInt(Unknown Source)
[20:59:37] [Server thread/WARN]: 	at com.earth2me.essentials.ItemDb.reloadConfig(ItemDb.java:80)
[20:59:37] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.reload(Essentials.java:346)
[20:59:37] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:231)
[20:59:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:59:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[20:59:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[20:59:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:424)
[20:59:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:338)
[20:59:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:523)
[20:59:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:485)
[20:59:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:384)
[20:59:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[20:59:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:647)
[20:59:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by mdcfe** [comment]
1.13 materials are not supported by EssentialsX at all. Revert your server to 1.12.2 until EssentialsX supports 1.13.

Edit: see the status update [here](https://github.com/EssentialsX/Essentials/issues/2086#issuecomment-408167473).
