### ISSUE TITLE
TAB Error

### ISSUE THREAD

**Issue by xbette** [EssentialsX/Essentials#2108]
### Information

Full output of `/ess version`: I cant do a /ess version, that fails But im running the Essentials v2.15.0.18

```
[21:48:06] [Server thread/ERROR]: Exception when Bette_ attempted to tab complete essentials re
org.bukkit.command.CommandException: Unhandled exception during tab completion for command "/essentials re" in plugin Essentials v2.15.0.18
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:144) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at org.bukkit.command.Command.tabComplete(Command.java:90) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:217) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.tabCompleteCommand(CraftServer.java:1640) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.tabComplete(CraftServer.java:1612) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at org.bukkit.craftbukkit.v1_13_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:49) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:68) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:372) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:503) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at net.minecraft.server.v1_13_R1.PacketPlayInTabComplete.a(SourceFile:36) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at net.minecraft.server.v1_13_R1.PacketPlayInTabComplete.a(SourceFile:9) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NullPointerException
	at com.earth2me.essentials.Essentials.onTabCompleteEssentials(Essentials.java:367) ~[?:?]
	at com.earth2me.essentials.Essentials.onTabComplete(Essentials.java:358) ~[?:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:135) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
	... 19 more
```

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://gist.github.com/xbette/504fb55d7c93e45ace55a32cae022a78

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): https://gist.github.com/xbette/e0d42b09df91e9588f6e189a875e1589

### Details

When i do /essentials and press TAB i get the above error.

**Comment by Xeyame** [comment]
For me it works fine, however im running v2.15.0.**17** and paper instead of spigot.

**Comment by mdcfe** [comment]
Thanjs for submitting the report - I'll take a look at this soon.

**Comment by mdcfe** [comment]
Is this still an issue?

**Comment by seema84** [comment]
no problem in dev-39.182
i think you can close it
