### ISSUE TITLE
EssentialsXMPP

### ISSUE THREAD

**Issue by NoopyyGaming** [EssentialsX/Essentials#2156]
Hey man,

when i logged in, i get this in console :

 > [11:46:47 WARN]: [Essentials] Task #46 for Essentials v2.15.0.45 generated an exception
java.lang.NullPointerException
at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:148) ~[?:?]
at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?]
at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$1.run(EssentialsXMPPPlayerListener.java:31) ~[?:?]
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-c6871e2-0cd0397]
at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [server.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [server.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [server.jar:git-Spigot-c6871e2-0cd0397]
at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [server.jar:git-Spigot-c6871e2-0cd0397]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by mdcfe** [comment]
Are you using XMPP? If not, remove the EssentialsXXMPP jar from `plugins/`.

**Comment by NoopyyGaming** [comment]
Done, but it seems that EssentialsX is doing something to the plugin SilkSpawners, because when i place a spawner, i get : Skipping BlockEntity with ID. I've asked the creator, he told me that it comes from EssentialsX.

**Comment by mdcfe** [comment]
EssentialsX fixes Minecraft's broken spawner placement if a player has the permission `essentials.spawnerconvert.<MOB>`. The message is from Minecraft, you can ignore it.

**Comment by NoopyyGaming** [comment]
Okey, but i don't like to see warning message like this
