### ISSUE TITLE
Essentials Stopped Working

### ISSUE THREAD

**Issue by ThatMagic** [EssentialsX/Essentials#222]
Hello, this exception just started popping up after restarting it.
org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b196 generated an exception while executing task 100

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.NullPointerException

at org.anjocaido.groupmanager.dataholder.WorldDataHolder.getUser(WorldDataHolder.java:122)

at org.anjocaido.groupmanager.dataholder.OverloadedWorldHolder.getUser(OverloadedWorldHolder.java:53)

at org.anjocaido.groupmanager.permissions.AnjoPermissionsHandler.getGroup(AnjoPermissionsHandler.java:94)

at net.milkbowl.vault.permission.plugins.Permission_GroupManager.getPrimaryGroup(Permission_GroupManager.java:332)

at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:726)

at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:738)

at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33)

at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:26)

at com.earth2me.essentials.User.getGroup(User.java:529)

at com.earth2me.essentials.textreader.TextInput.<init>(TextInput.java:28)

at com.earth2me.essentials.EssentialsPlayerListener.delayedJoin(EssentialsPlayerListener.java:195)

at com.earth2me.essentials.EssentialsPlayerListener$1.run(EssentialsPlayerListener.java:166)

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)

at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)

**Comment by drtshock** [comment]
Looks like a group manager issue.
