### ISSUE TITLE
1.13.2 on startup error

### ISSUE THREAD

**Issue by BaxAndrei** [EssentialsX/Essentials#2281]
```[18:52:12] [Craft Scheduler Thread - 47/WARN]: [Essentials] Plugin Essentials v2.15.0.1 generated an exception while executing task 80
java.lang.NoSuchMethodError: com.earth2me.essentials.storage.BukkitConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
	at com.earth2me.essentials.storage.BukkitConstructor.access$600(BukkitConstructor.java:19) ~[?:?]
	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:184) ~[?:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:136) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:214) ~[?:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:283) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:246) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:214) ~[?:?]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:467) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:41) ~[?:?]
	at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-a1f2566-97b0057]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-a1f2566-97b0057]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_171]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]```

**Comment by BaxAndrei** [comment]
deleted essentials folder, problem solved

**Comment by BaxAndrei** [comment]
Error is back

**Comment by mdcfe** [comment]
Please [fill out the appropriate template](https://github.com/EssentialsX/Essentials/issues/new/choose).
