### ISSUE TITLE
[Essentials] Plugin Essentials v2.15.0.1 generated an exception while executing task 15

### ISSUE THREAD

**Issue by bluebit27** [EssentialsX/Essentials#2283]
java.lang.NoSuchMethodError: com.earth2me.essentials.storage.BukkitConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
	at com.earth2me.essentials.storage.BukkitConstructor.access$600(BukkitConstructor.java:19) ~[?:?]
	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:184) ~[?:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:136) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:214) ~[?:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:283) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:246) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:214) ~[?:?]
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:467) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:41) ~[?:?]
	at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:33) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-a1ba5fe-3359cb1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by mdcfe** [comment]
You are running an unsupported version of EssentialsX.

For 1.13 support, please use the [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental).
