### ISSUE TITLE
1.13: /setworth still uses data values

### ISSUE THREAD

**Issue by mdcfe** [EssentialsX/Essentials#2295]
*Originally reported by Luisthegeek#7529 on Discord.*

### Information

**Full output of `/ess version`**:

```
Server Version: 1.13.2-R0.1-SNAPSHOT git-Paper-474 (MC: 1.13.2) 
EssentialsX version: dev-39.182 
LuckPerms version: 4.3.17 
Vault Version: 1.7.1-b91 
EssentialsXChat Version: dev-39.182 
EssentialsXSpawn version: dev-39.182
```

**Server log**: 
```java
08.12 04:15:54 [Server] INFO Error calling the command /setworth 
08.12 04:15:54 [Server] INFO java.lang.IllegalArgumentException: Cannot get data class of Modern Material 
08.12 04:15:54 [Server] INFO at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at org.bukkit.Material.getData(Material.java:3089) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at com.earth2me.essentials.Worth.setPrice(Worth.java:108) ~[?:?] 
08.12 04:15:54 [Server] INFO at com.earth2me.essentials.commands.Commandsetworth.run(Commandsetworth.java:34) ~[?:?] 
08.12 04:15:54 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) ~[?:?] 
08.12 04:15:54 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:530) ~[?:?] 
08.12 04:15:54 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:443) ~[?:?] 
08.12 04:15:54 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-474] 08.12 04:15:54 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1799) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1602) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-474] 
08.12 04:15:54 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131] 
08.12 04:15:54 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
```

**EssentialsX config**: 

### Details

**Description**  
`/setworth` fails with "`Error: Cannot get data class of Modern Material`"

**Steps to reproduce**  
1. Hold an item and run `/setworth`.
2. ???
3. Profit! (?)

**Expected behavior**  
`/setworth` should work without error, setting the item name in the `worth.yml`.

**Comment by mdcfe** [comment]
Fixed in 44301fae4f0978ec6188ff0e15d32b3d39a4a6c5.
