### ISSUE TITLE
Essentials 2.16.0.1 not working on spigot 1.13.2

### ISSUE THREAD

**Issue by compieter-gh** [EssentialsX/Essentials#2346]
[22:23:23] [Server thread/INFO]: [Essentials] Enabling Essentials v2.16.0.1
[22:23:23] [Server thread/ERROR]: java.lang.ExceptionInInitializerError
[22:23:23] [Server thread/WARN]: java.lang.ExceptionInInitializerError
[22:23:23] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:175)
[22:23:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[22:23:23] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[22:23:23] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[22:23:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434)
[22:23:23] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348)
[22:23:23] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579)
[22:23:23] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541)
[22:23:23] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419)
[22:23:23] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[22:23:23] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697)
[22:23:23] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:23:23] [Server thread/WARN]: Caused by: java.lang.NumberFormatException: For input string: ""
[22:23:23] [Server thread/WARN]: 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[22:23:23] [Server thread/WARN]: 	at java.lang.Integer.parseInt(Integer.java:592)
[22:23:23] [Server thread/WARN]: 	at java.lang.Integer.parseInt(Integer.java:615)
[22:23:23] [Server thread/WARN]: 	at com.earth2me.essentials.utils.VersionUtil$BukkitVersion.fromString(VersionUtil.java:52)
[22:23:23] [Server thread/WARN]: 	at com.earth2me.essentials.utils.VersionUtil.<clinit>(VersionUtil.java:15)
[22:23:23] [Server thread/WARN]: 	... 12 more
[22:23:23] [Server thread/ERROR]: Error occurred while enabling Essentials v2.16.0.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.earth2me.essentials.Essentials.onDisable(Essentials.java:348) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[Spigot.jar:git-Spigot-8ede039-d0a9130]
	at com.earth2me.essentials.Essentials.handleCrash(Essentials.java:708) ~[?:?]
	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:280) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[Spigot.jar:git-Spigot-8ede039-d0a9130]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [Spigot.jar:git-Spigot-8ede039-d0a9130]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

latest spigot 1.13.2 build and latest essentialsx 2.16.0.1

**Comment by SlimeDog** [comment]
Same...with Spigot 1.13.2 latest and any of
- update of EssentialsX-2.16-pre4.9
- new installation of EssentialsX-2.16.0.0
- new installation of EssentialsX-2.16.0.1
```
[13:43:50] [Server thread/ERROR]: java.lang.ExceptionInInitializerError
[13:43:50] [Server thread/WARN]: java.lang.ExceptionInInitializerError
[13:43:50] [Server thread/WARN]: 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:175)
[13:43:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[13:43:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[13:43:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[13:43:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434)
[13:43:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348)
[13:43:50] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579)
[13:43:50] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541)
[13:43:50] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419)
[13:43:50] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[13:43:50] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697)
[13:43:50] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[13:43:50] [Server thread/WARN]: Caused by: java.lang.NumberFormatException: For input string: ""
[13:43:50] [Server thread/WARN]: 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[13:43:50] [Server thread/WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:662)
[13:43:50] [Server thread/WARN]: 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
[13:43:50] [Server thread/WARN]: 	at com.earth2me.essentials.utils.VersionUtil$BukkitVersion.fromString(VersionUtil.java:52)
[13:43:50] [Server thread/WARN]: 	at com.earth2me.essentials.utils.VersionUtil.<clinit>(VersionUtil.java:15)
[13:43:50] [Server thread/WARN]: 	... 12 more
[13:43:50] [Server thread/ERROR]: Error occurred while enabling Essentials v2.16.0.1 (Is it up to date?)
```

**Comment by baticag** [comment]
Same problem with PaperSpigot 1.13.2
https://pastebin.com/t7wN0YQ8
This server is running Paper version git-Paper-488 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Comment by drtshock** [comment]
Resolved https://github.com/EssentialsX/Essentials/commit/da89efb79fae45c55277a5066d042c50b1b86e41

https://ci.ender.zone/job/EssentialsX/667/
