### ISSUE TITLE
NoSuchMethodError: org.bukkit.UnsafeValues.fromLegacy

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#2352]
EssentialsX dev 668

```
[18:47:24] [Server thread/ERROR]: [Essentials] Command i failed:
java.lang.NoSuchMethodError: org.bukkit.UnsafeValues.fromLegacy(Lorg/bukkit/material/MaterialData;)Lorg/bukkit/Material;
	at com.earth2me.essentials.utils.MaterialUtil.lambda$convertFromLegacy$1(MaterialUtil.java:109) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_192]
	at com.earth2me.essentials.utils.MaterialUtil.convertFromLegacy(MaterialUtil.java:109) ~[?:?]
	at com.earth2me.essentials.api.IItemDb.getFromLegacy(IItemDb.java:154) ~[?:?]
	at com.earth2me.essentials.items.LegacyItemDb.get(LegacyItemDb.java:159) ~[?:?]
	at com.earth2me.essentials.commands.Commanditem.run(Commanditem.java:29) ~[?:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:534) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:447) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1478) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1283) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1595]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1595]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
```

**Comment by mdcfe** [comment]
I've pushed fd01b75c33ca13354226f0d52cc2cb0eaebb16aa - could you update to [2.16.0.7 or later](https://ci.ender.zone/job/EssentialsX) and see if this is resolved?

**Comment by mdcfe** [comment]
This appears to be resolved in the aforementioned versions.
