### ISSUE TITLE
java.lang.NoClassDefFoundError: com/earth2me/essentials/ItemDb

### ISSUE THREAD

**Issue by k-jiang** [EssentialsX/Essentials#2396]
EssentialsX throws `java.lang.NoClassDefFoundError: com/earth2me/essentials/ItemDb` during server startup:
```
[04:09:39 WARN]: java.lang.NoClassDefFoundError: com/earth2me/essentials/ItemDb
[04:09:39 WARN]:        at java.lang.ClassLoader.defineClass1(Native Method)
[04:09:39 WARN]:        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[04:09:39 WARN]:        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[04:09:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:130)
[04:09:39 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:194)
[04:09:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
[04:09:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80)
[04:09:39 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[04:09:39 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[04:09:39 WARN]:        at com.elmakers.mine.bukkit.magic.MagicController$3.run(MagicController.java:1074)
[04:09:39 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[04:09:39 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[04:09:39 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[04:09:39 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[04:09:39 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[04:09:39 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[04:09:39 WARN]:        at java.lang.Thread.run(Thread.java:748)
[04:09:39 WARN]: Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.ItemDb
[04:09:39 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[04:09:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134)
[04:09:39 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80)
[04:09:39 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[04:09:39 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[04:09:39 WARN]:        ... 17 more
```
This exception occured right after `[04:09:36]: Done (46.763s)! For help, type "help"`

Server info:
```
[04:17:19 INFO]: CONSOLE issued server command: /ess version
[04:17:19 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-f56e2e7-b634e05 (MC: 1.13.2)
[04:17:19 INFO]: EssentialsX version: 2.16.0.32
[04:17:19 INFO]: Vault version: 1.7.1-b91
[04:17:19 INFO]: EssentialsXProtect version: 2.16.0.32
[04:17:19 INFO]: EssentialsXChat version: 2.16.0.32
[04:17:19 INFO]: EssentialsXGeoIP version: 2.16.0.32
[04:17:19 INFO]: EssentialsXAntiBuild version: 2.16.0.32
[04:17:19 INFO]: EssentialsXSpawn version: 2.16.0.32
```
EssentialsX is obtained from https://ci.ender.zone/job/EssentialsX/ (build 691)

If you need more info please let me know.

**Comment by triagonal** [comment]
After testing this, I can confirm that this error does not occur on a clean 1.13.2 spigot install with just EssentialsX installed.

```
[15:22:44 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-f56e2e7-b634e05 (MC: 1.13.2)
[15:22:44 INFO]: EssentialsX version: 2.16.0.32
[15:22:44 INFO]: EssentialsXProtect version: 2.16.0.32
[15:22:45 INFO]: EssentialsXSpawn version: 2.16.0.32
[15:22:45 INFO]: EssentialsXChat version: 2.16.0.32
[15:22:45 INFO]: EssentialsXGeoIP version: 2.16.0.32
[15:22:45 INFO]: EssentialsXAntiBuild version: 2.16.0.32
```

As far as I can tell from your stacktrace, this error is caused by another plugin called Magic. It seems that Magic is not compatible with the current version of EssentialsX, as it is still attempting to use classes that have been removed in recent versions of EssentialsX.

**Comment by k-jiang** [comment]
You are probably correct. It looks like a compatibility issue due to some API changes. I just post the issue to MagicPlugin team. Waiting for response...

**Comment by triagonal** [comment]
The latest version of Magic (6.9.20) is now compatible with EssentialsX.
