### ISSUE TITLE
Essentials v2.16.0.3 generated an exception on login and logut

### ISSUE THREAD

**Issue by Ann-Helen** [EssentialsX/Essentials#2426]
### Information

**Server log:** [Essentials] Task #2270 for Essentials v2.16.0.3 generated an exception
java.lang.NullPointerException: null
        at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:144) ~[?:?]
        at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:109) ~[?:?]
        at com.earth2me.essentials.xmpp.EssentialsXMPPPlayerListener$2.run(EssentialsXMPPPlayerListener.java:51) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

### Help request

**Problem**
I just get this exception thrown when a player logs in or logs out. That's it, really, haven't found it actually affecting anything except clogging the logs and console.

**What I have tried**
Nothing, I don't have anything to try. This seems a simple nullPointerException(?).

[config.txt](https://github.com/EssentialsX/Essentials/files/2871885/config.txt)
[latest.log](https://github.com/EssentialsX/Essentials/files/2871882/latest.log)

**Comment by mdcfe** [comment]
Are you using XMPP? If not, remove the `EssentialsXXMPP` jar.

**Comment by mdcfe** [comment]
Closing due to lack of response.
