### ISSUE TITLE
Console said to post this to a developer

### ISSUE THREAD

**Issue by brobie1kanobi** [EssentialsX/Essentials#2436]
2019-02-24 20-29
=============================== GM ERROR LOG ===============================
= ERROR REPORT START - GMBuildVer (Phoenix) =

java.lang.IllegalArgumentException: The following file couldn't pass on Parser.
plugins/GroupManager/worlds/lobby (mgw battle arena)/groups.yml
	at org.anjocaido.groupmanager.dataholder.WorldDataHolder.loadGroups(WorldDataHolder.java:590)
	at org.anjocaido.groupmanager.dataholder.WorldDataHolder.loadGroups(WorldDataHolder.java:510)
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.loadWorld(WorldsHolder.java:678)
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.loadWorld(WorldsHolder.java:640)
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.initialWorldLoading(WorldsHolder.java:110)
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.initialLoad(WorldsHolder.java:100)
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.resetWorldsHolder(WorldsHolder.java:92)
	at org.anjocaido.groupmanager.dataholder.worlds.WorldsHolder.<init>(WorldsHolder.java:59)
	at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:179)
	at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:103)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:423)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:349)
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:571)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:533)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:411)
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:270)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:676)
	at java.lang.Thread.run(Thread.java:748)
Caused by: while parsing a block mapping
 in 'reader', line 12, column 3:
      Default:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 60, column 4:
       Member:
       ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:467)
	at org.anjocaido.groupmanager.dataholder.WorldDataHolder.loadGroups(WorldDataHolder.java:585)
	... 20 more

============================================================================

## Any help will be appreciated!

Running on Craftbukkit 1.13.2 
If other info is needed I will gladly give it.

**Comment by mdcfe** [comment]
GroupManager is an unmaintained and unsupported plugin, and is not part of Essentials**X**.

If you're having issue using GroupManager alongside EssentialsX, we recommend switching to [LuckPerms](https://luckperms.github.io).
