### ISSUE TITLE
I keep getting errors i do not know about.

### ISSUE THREAD

**Issue by Joseph0430** [EssentialsX/Essentials#2532]
it says the error code 
`[06:30:24] [User Authenticator #1/INFO]: UUID of player Joseph0430 is 92f925a1-0568-4852-a748-7af9d9c83dc8
[06:30:25] [Server thread/INFO]: Joseph0430[/85.203.46.209:57650] logged in with entity id 292 at ([Imperialcity v14.1]489740.3958874545, 64.0, 276994.25874583074)
[06:30:25] [Server thread/WARN]: [Essentials] Task #30 for Essentials v2.16.1.0 generated an exception
java.lang.NullPointerException: null
at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:146) ~[?:?]
at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[06:30:25] [Server thread/INFO]: Joseph0430 re-joined the hellhole.
[06:30:50] [Server thread/INFO]: Joseph0430 lost connection: Timed out
[06:30:50] [Server thread/INFO]: Joseph0430 escaped the hellhole.
[06:30:50] [Server thread/WARN]: [Essentials] Task #324 for Essentials v2.16.1.0 generated an exception
java.lang.NullPointerException: null
at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:142) ~[?:?]
at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [minecraft_server.jar:git-Spigot-1a3504a-dfa7583]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`
all the time i join, please help!

**Comment by mdcfe** [comment]
Are you using XMPP?

**Comment by Joseph0430** [comment]
yes. EssentialsXMPP

**Comment by mdcfe** [comment]
Are you actually **using** XMPP? You haven't set EssentialsX XMPP up. If you don't know what it does, you don't need it.
