### ISSUE TITLE
1.14.1 login console eror

### ISSUE THREAD

**Issue by successed** [EssentialsX/Essentials#2561]
[23:35:37] [Craft Scheduler Thread - 25/WARN]: [Essentials] Plugin Essentials v2.16.1.150 generated an exception while executing task 1240
java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
        at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
        at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener.delayedJoin(EssentialsPlayerListener.java:221) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener$1.run(EssentialsPlayerListener.java:198) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[paperclip.jar:git-Spigot-03bd4b0-17da342]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [paperclip.jar:git-Spigot-03bd4b0-17da342]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by mdcfe** [comment]
Duplicate of #2545. Please search before opening issues.
