### ISSUE TITLE
Could not pass event PlayerChangedWorldEvent to Essentials v2.16.1.167 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by Cuprin** [EssentialsX/Essentials#2579]
```
[18:47:55] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to Essentials v2.16.1.167
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[core.jar:git-Spigot-baafee9-043d31d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[core.jar:git-Spigot-baafee9-043d31d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [core.jar:git-Spigot-baafee9-043d31d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:872) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2020) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:373) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:236) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:345) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2217) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:147) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:397) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.PlayerList.disconnect(PlayerList.java:387) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1383) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.NetworkManager.handleDisconnection(NetworkManager.java:328) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:143) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1080) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [core.jar:git-Spigot-baafee9-043d31d]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_212]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_212]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:1.8.0_212]
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(SourceFile:132) ~[core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:204) ~[core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkFutureMainThread(ChunkProviderServer.java:144) ~[core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:91) ~[core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:212) ~[core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(SourceFile:105) ~[core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:207) ~[core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.World.getType(World.java:548) ~[core.jar:git-Spigot-baafee9-043d31d]
	at net.minecraft.server.v1_14_R1.EntityHuman.getBed(EntityHuman.java:1328) ~[core.jar:git-Spigot-baafee9-043d31d]
	at org.bukkit.craftbukkit.v1_14_R1.entity.CraftHumanEntity.getBedSpawnLocation(CraftHumanEntity.java:150) ~[core.jar:git-Spigot-baafee9-043d31d]
	at com.earth2me.essentials.EssentialsPlayerListener.updateCompass(EssentialsPlayerListener.java:369) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChangedWorld(EssentialsPlayerListener.java:582) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[core.jar:git-Spigot-baafee9-043d31d]
	... 20 more
```

**Comment by Jowcey** [comment]
This is easily to replicate, if a player goes through a portal, then 1 second later another player goes through, theres a very big chance the second player will get an "Internal Server Error" with the console spitting out this error. If the "second player" is a mob or any other entity it will actually cause the server to crash

**Comment by alessiettojr** [comment]
how do you avoid this?

**Comment by pop4959** [comment]
Please update to the latest version of Essentials, and if this is still a problem, please re-create the issue and fill out the issue template in its entirety. This looks like it might not directly be caused by Essentials, so updating your server software may also fix the issue.
