### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by successed** [EssentialsX/Essentials#2612]
[15:32:53 ERROR]: Cound not schedule mailbox
java.util.concurrent.RejectedExecutionException: null
        at java.util.concurrent.ForkJoinPool.externalSubmit(ForkJoinPool.java:2328) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2419) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648) ~[?:1.8.0_212]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.f(SourceFile:112) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:101) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.a(SourceFile:141) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.a(SourceFile:149) ~[patched_1.14.2.jar:git-Paper-97]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_212]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_212]
        at net.minecraft.server.v1_14_R1.Mailbox$1.a(SourceFile:32) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.e(SourceFile:83) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.a(SourceFile:123) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.ThreadedMailbox.run(SourceFile:91) ~[patched_1.14.2.jar:git-Paper-97]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_212]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_212]

**Comment by mdcfe** [comment]
This does not appear to be an EssentialsX issue. Please report this to your server software's support team.
