### ISSUE TITLE
AsyncPlayerChatEvent error console spam

### ISSUE THREAD

**Issue by noikonoikola** [EssentialsX/Essentials#2616]
[14:58:55] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.0
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1592) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1530) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
at com.earth2me.essentials.User.updateActivity(User.java:557) ~[?:?]
at com.earth2me.essentials.User.updateActivityOnInteract(User.java:577) ~[?:?]
at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:104) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
... 11 more
**-----------------------------------------------

This error always occurs when the player is in AFK and writes something to the chat.
How do I fix it? and
How do I get a player to leave AFK when he send a message in the conversation?

-----------------------------------------------**

**Comment by mdcfe** [comment]
You're running an outdated build on 1.14+. Download the [latest build](https://essentialsx.github.io) for 1.14.2 support.

**Comment by noikonoikola** [comment]
Thank you! It fixed my problem.
