### ISSUE TITLE
/Spawnmob is not working

### ISSUE THREAD

**Issue by VirtualBum** [EssentialsX/Essentials#262]
[08:21:11 INFO]: VirtualBum issued server command: /spawnmob zombie 2
[08:21:11 ERROR]: Command spawnmob failed:
java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getTargetBlock(Ljava/util/Set;I)Lorg/bukkit/block/Block;
        at com.earth2me.essentials.utils.LocationUtil.getTarget(LocationUtil.java:199) ~[EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.SpawnMob.spawnmob(SpawnMob.java:70) ~[EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.Commandspawnmob.run(Commandspawnmob.java:45) ~[EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:433) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:343) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:685) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [Spigot1.8.8.jar:git-Spigot-952179b-2173630]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]

This is the console output for any \spawnmob command. This one is for zombie

**Comment by SupaHam** [comment]
Please reply with the exact output of /version.

**Comment by VirtualBum** [comment]
[12:43:23 INFO]: This server is running CraftBukkit version git-Spigot-952179b-2173630 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[12:43:23 INFO]: Checking version, please wait...
[12:43:25 INFO]: You are 263 version(s) behind

**Comment by SupaHam** [comment]
You'll want to update your Spigot then. :)

**Comment by VirtualBum** [comment]
Thanks, Will try that first

**Comment by VirtualBum** [comment]
All fixed with the new version. Thanks!

[13:16:14 INFO]: This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[13:16:14 INFO]: Checking version, please wait...
[13:16:16 INFO]: You are 1 version(s) behind
