### ISSUE TITLE
Failed to load with Paper 1.14.3 build 109: java.lang.IllegalArgumentException: 1.14.3-SNAPSHOT is not in valid version

### ISSUE THREAD

**Issue by xsun2001** [EssentialsX/Essentials#2623]
### Information

**Full output of `/ess version`**:

```
EssentialsX isn't loaded.
```

**Server log**: https://gist.github.com/xsun2001/4f8a5d5c2e472f32f5a58eb7687160b3
**EssentialsX config**: https://gist.github.com/xsun2001/2b8869871497ea9423a071ec4343daa4
**Java version**:
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

### Details

**Description**  
Failed to load with Paper 1.14.3 build 109

```
[12:07:06 ERROR]: Error occurred while enabling Essentials v2.16.1.215 (Is it up to date?)
java.lang.IllegalArgumentException: 1.14.3-SNAPSHOT is not in valid version format. e.g. 1.8.8-R0.1
        at com.earth2me.essentials.utils.VersionUtil$BukkitVersion.fromString(VersionUtil.java:56) ~[?:?]
        at com.earth2me.essentials.utils.VersionUtil.getServerBukkitVersion(VersionUtil.java:33) ~[?:?]
        at com.earth2me.essentials.utils.VersionUtil.isServerSupported(VersionUtil.java:39) ~[?:?]
        at com.earth2me.essentials.Essentials.onEnable(Essentials.java:175) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.3.jar:git-Paper-109]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.3.jar:git-Paper-109]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.3.jar:git-Paper-109]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.3.jar:git-Paper-109]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.3.jar:git-Paper-109]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.3.jar:git-Paper-109]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.3.jar:git-Paper-109]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.3.jar:git-Paper-109]
        at java.lang.Thread.run(Thread.java:835) [?:?]
```

It is similar with #2621 , but in my case, I simply cannot load this plugin.

**Steps to reproduce**  
Install EssentialsX in Paper build 109.

**Comment by T1MOXA** [comment]
The same problem.

**Comment by xsun2001** [comment]
Oh... Sorry for my carelessness. They are exactly the same. I will close this issue.
