### ISSUE TITLE
WARN]: [Essentials] Task #23

### ISSUE THREAD

**Issue by VapeKid123** [EssentialsX/Essentials#2773]
Hi, I tried absolutely everything I knew and I failed to do anything to get rid of this problem, can you help me please?

 WARN]: [Essentials] Task #23 for Essentials v2.17.1.0 generated an exception
java.lang.NullPointerException
        at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:146) ~[?:?]
        at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]

**Comment by mdcfe** [comment]
Are you using XMPP? If not, delete EssentialsXXMPP.

**Comment by pop4959** [comment]
As md mentioned above, if you aren't using EssentialsXMPP (especially if you don't know what XMPP means), then remove it. If you're still having issues let us know.
