### ISSUE TITLE
Could not find template custom_items.yml

### ISSUE THREAD

**Issue by wizdude** [EssentialsX/Essentials#2899]
i've been setting up a new paper 1.15.1 server over the past few days and i installed EssentialsX and EssentialsXspawn version 2.17.1.40. after adding in the EssentialsXspawn i receive a file not found every time i start the server.

[22:06:52 INFO]: [Essentials] Enabling Essentials v2.17.1.40
[22:06:52 INFO]: [Essentials] Creating config from template: /root/down/paper15/plugins/Essentials/config.yml
[22:06:52 INFO]: [Essentials] Creating config from template: /root/down/paper15/plugins/Essentials/kits.yml
[22:06:52 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[22:06:52 INFO]: [Essentials] No kits found to migrate.
[22:06:52 INFO]: [Essentials] Starting Essentials ban format conversion
[22:06:52 INFO]: [Essentials] Starting usermap repair
[22:06:52 WARN]: [Essentials] Missing userdata folder, aborting
[22:06:52 INFO]: [Essentials] Creating config from template: /root/down/paper15/plugins/Essentials/worth.yml
[22:06:52 INFO]: [Essentials] Creating empty config: /root/down/paper15/plugins/Essentials/upgrades-done.yml
[22:06:52 INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[22:06:52 INFO]: [Essentials] Using 1.13+ flat spawn egg provider as spawn egg provider.
[22:06:52 INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[22:06:52 INFO]: [Essentials] Loaded 20977 items from items.json.
[22:06:52 INFO]: [Essentials] Creating config from template: /root/down/paper15/plugins/Essentials/custom_items.yml
[22:06:52 ERROR]: [Essentials] Could not find template custom_items.yml
[22:06:52 ERROR]: [Essentials] /root/down/paper15/plugins/Essentials/custom_items.yml (No such file or directory)
java.io.FileNotFoundException: /root/down/paper15/plugins/Essentials/custom_items.yml (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_222]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[?:1.8.0_222]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[?:1.8.0_222]
        at com.earth2me.essentials.EssentialsConf.load(EssentialsConf.java:100) ~[?:?]
        at com.earth2me.essentials.items.CustomItemResolver.reloadConfig(CustomItemResolver.java:43) ~[?:?]
        at com.earth2me.essentials.Essentials.reload(Essentials.java:381) ~[?:?]
        at com.earth2me.essentials.Essentials.onEnable(Essentials.java:262) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-27]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-27]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-27]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-27]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-27]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:481) ~[patched_1.15.1.jar:git-Paper-27]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.15.1.jar:git-Paper-27]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-27]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
[22:06:52 WARN]: [Essentials] No aliases found in custom_items.yml.
[22:06:53 INFO]: [Essentials] Using locale en_AU
[22:06:53 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[22:06:53 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.

downgrading to 2.17.1.38 for both has removed this error.

**Comment by SlimeDog** [comment]
The error is that build 40 introduced custom_items.yml, but doesn't create it. The error may be safely ignored, but should be fixed.

**Comment by pop4959** [comment]
Should be fixed relatively quickly, for now just ignore the error or use build 39 until this issue is resolved. You may also create the file yourself manually if you wish.

**Comment by pop4959** [comment]
The file is currently supposed to look something like this: <https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/custom_items.yml>

**Comment by SlimeDog** [comment]
> Should be fixed relatively quickly, for now just ignore the error or use build 39 until this issue is resolved. You may also create the file yourself manually if you wish.

I oopied it from the unzipped JAR (I almost always unzip JARs to see the contents and changes.)

**Comment by pop4959** [comment]
Should be fixed in the latest build.
