### ISSUE TITLE
Spamming errors in console

### ISSUE THREAD

**Issue by BillZhucn** [EssentialsX/Essentials#2932]
### Information

Full output of `/ess version`:

07.01 17:18:17 [server] INFO Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-31 (MC: 1.15.1)
07.01 17:18:17 [server] INFO EssentialsX version: 2.17.1.0
07.01 17:18:17 [server] INFO Vault version: 1.7.2-b107
07.01 17:18:17 [server] INFO EssentialsXGeoIP version: 2.17.1.0
07.01 17:18:17 [server] INFO EssentialsXChat version: 2.17.1.0
07.01 17:18:17 [server] INFO GroupManager version: 3.1
07.01 17:18:17 [server] INFO EssentialsXAntiBuild version: 2.17.1.0
07.01 17:18:17 [server] INFO EssentialsXSpawn version: 2.17.1.0
07.01 17:18:17 [server] INFO EssentialsXProtect version: 2.17.1.0

**Server log:** 
I'm not accessible to this link.
[latest.log](https://github.com/EssentialsX/Essentials/files/4029873/latest.log)

**EssentialsX config** 

### Help request

**Problem**

See "screenshot". The console is always spamming ess errors.
**What I have tried**

I just do not know how to solve) So I just reboot the server but that does not help
**Screenshots**

```
[00:01:16] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to GroupManager v3.1
java.lang.NullPointerException: null
[00:01:16] [Server thread/ERROR]: Could not pass event PlayerChangedWorldEvent to Essentials v2.17.1.0
java.lang.NullPointerException: null
[00:01:21] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:01:21] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:01:21] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:01:22] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:01:30] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 10024ms or 200 ticks behind
[00:01:45] [Server thread/INFO]: LXZG issued server command: /back
[00:01:45] [Server thread/INFO]: CONSOLE issued server command: /list 
[00:01:45] [Server thread/INFO]: 当前有 5 个玩家在线,最大在线人数为 35 个玩家.
[00:01:45] [Server thread/INFO]: 错误:null
[00:02:20] [Server thread/INFO]: CONSOLE issued server command: /list 
[00:02:20] [Server thread/INFO]: 当前有 5 个玩家在线,最大在线人数为 35 个玩家.
[00:02:20] [Server thread/INFO]: error:null
[00:02:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:23] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:24] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:24] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:25] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:26] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:30] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:30] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:30] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:31] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:32] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:36] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 5024ms or 100 ticks behind
[00:02:37] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:38] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:38] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:39] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:40] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:40] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:41] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:44] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:45] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:45] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:02:55] [Server thread/INFO]: CONSOLE issued server command: /list 
[00:02:55] [Server thread/INFO]: 当前有 5 个玩家在线,最大在线人数为 35 个玩家.
[00:02:55] [Server thread/INFO]: 错误:null
[00:03:30] [Server thread/INFO]: CONSOLE issued server command: /list 
[00:03:30] [Server thread/INFO]: 当前有 5 个玩家在线,最大在线人数为 35 个玩家.
[00:03:30] [Server thread/INFO]: 错误:null
[00:03:34] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:03:35] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:03:35] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:03:36] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:04:04] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:04:04] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:04:05] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:04:05] [Server thread/INFO]: CONSOLE issued server command: /list 
[00:04:05] [Server thread/INFO]: 当前有 5 个玩家在线,最大在线人数为 35 个玩家.
[00:04:05] [Server thread/INFO]: 错误:null
[00:04:06] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
[00:04:06] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to EssentialsAntiBuild v2.17.1.0
java.lang.NullPointerException: null
```
```
[17:13:00] [Craft Scheduler Thread - 1387/WARN]: [Essentials] Plugin Essentials v2.17.1.0 generated an exception while executing task 5154
java.lang.NullPointerException: null
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.delayedJoin(EssentialsGeoIPPlayerListener.java:80) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.lambda$onPlayerJoin$0(EssentialsGeoIPPlayerListener.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-31]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.1.jar:git-Paper-31]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.1.jar:git-Paper-31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by pop4959** [comment]
Have you tried running the server with only EssentialsX and a compatible permission plugin installed (ideally not GroupManager, as that plugin is severely outdated) to check if it is a plugin conflict?

If you have, can you type `/essentials verbose` and show us the full errors from the console?
