### ISSUE TITLE
Error /nick 

### ISSUE THREAD

**Issue by Lyrians** [EssentialsX/Essentials#2970]
I don't know why, but from one second to another, this happened when trying to change the nick

```
23.01 13:50:58 [Server] INFO java.lang.Exception: Tienes que activar el cambio de nick en la configuración del plugin Essentials.
23.01 13:50:58 [Server] INFO at com.earth2me.essentials.commands.Commandnick.run(Commandnick.java:29) ~[?:?]
23.01 13:50:58 [Server] INFO at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:161) ~[?:?]
23.01 13:50:58 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:559) ~[?:?]
23.01 13:50:58 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:470) ~[?:?]
23.01 13:50:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1012) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-156]
23.01 13:50:58 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-156]
```

**Comment by pop4959** [comment]
Please make a new issue and follow the issue template. We cannot effectively help you if it is ignored.
