### ISSUE TITLE
Command fireball giving error  

### ISSUE THREAD

**Issue by paint2005** [EssentialsX/Essentials#3016]
/fireball is giving error in console and it wont summon a fireball.
<img width="1150" alt="Screen Shot 2020-02-18 at 1 15 38 AM" src="https://user-images.githubusercontent.com/47665139/74709660-bbea1280-51ed-11ea-818c-c9e13d948e5c.png">
this is the error...
https://pastebin.com/J85x9dJ5

**Comment by triagonal** [comment]
I can reproduce this bug on the following:
```
[17:33:27 INFO]: CONSOLE issued server command: /ess version
[17:33:27 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[17:33:27 INFO]: EssentialsX version: 2.17.1.61
[17:33:27 INFO]: Vault is not installed. Chat and permissions may not work.
```

config: https://gist.github.com/triagonal/a3fa35bbcded1e508cc244f5913f0740 (default)
server startup: https://gist.github.com/triagonal/389f120fedc976b7ba4b8e0aef786da7

When running `/fireball` for the first time (from either the console or ingame), this error appears:
```
[17:32:49 INFO]: HelloHarry issued server command: /fireball
[17:32:49 ERROR]: Command fireball failed:
java.lang.NoClassDefFoundError: org/bukkit/entity/DragonFireball
        at com.earth2me.essentials.commands.Commandfireball.<clinit>(Commandfireball.java:22) ~[EssentialsX-2.17.1.61.jar:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:529) [EssentialsX-2.17.1.61.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:470) [EssentialsX-2.17.1.61.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.DragonFireball
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
        ... 24 more
```

On any subsequent run, this (slightly different) error appears instead:
```
[17:33:11 INFO]: HelloHarry issued server command: /fireball
[17:33:11 ERROR]: Command fireball failed:
java.lang.NoClassDefFoundError: Could not initialize class com.earth2me.essentials.commands.Commandfireball
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:529) [EssentialsX-2.17.1.61.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:470) [EssentialsX-2.17.1.61.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_241]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
```

**Comment by paint2005** [comment]
```> [02:43:56 INFO]: Aaimal issued server command: /fireball
> [02:43:56 ERROR]: Command fireball failed:
java.lang.NoClassDefFoundError: Could not initialize class com.earth2me.essentials.commands.Commandfireball
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:529) [EssentialsX-2.17.2.0.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:470) [EssentialsX-2.17.2.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```

**Comment by paint2005** [comment]
> [02:32:43 INFO]: Aaimal issued server command: /fireball
> [02:32:43 ERROR]: Command fireball failed:
java.lang.NoClassDefFoundError: org/bukkit/entity/SplashPotion
at com.earth2me.essentials.commands.Commandfireball.<clinit>(Commandfireball.java:31) ~[EssentialsX-2.17.2.0.jar:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:529) [EssentialsX-2.17.2.0.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:470) [EssentialsX-2.17.2.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.SplashPotion
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 24 more

**Comment by paint2005** [comment]
```> [02:32:43 INFO]: Aaimal issued server command: /fireball
> [02:32:43 ERROR]: Command fireball failed:
java.lang.NoClassDefFoundError: org/bukkit/entity/SplashPotion
at com.earth2me.essentials.commands.Commandfireball.<clinit>(Commandfireball.java:31) ~[EssentialsX-2.17.2.0.jar:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_212]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:529) [EssentialsX-2.17.2.0.jar:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:470) [EssentialsX-2.17.2.0.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:667) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.SplashPotion
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 24 more```

**Comment by paint2005** [comment]
<img width="958" alt="Screen Shot 2020-02-23 at 9 49 00 PM" src="https://user-images.githubusercontent.com/47665139/75126101-706cb400-5686-11ea-9c2e-213dabc97665.png">
/fireball is still giving me error.

**Comment by triagonal** [comment]
I can confirm that this issue still persists on the following versions:
```
[20:43:41 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[20:43:41 INFO]: EssentialsX version: 2.17.2.1
[20:43:41 INFO]: Vault is not installed. Chat and permissions may not work.
```
The stacktrace now indicates that the plugin cannot find the `SplashPotion` class instead of the original `DragonFireball` class:
https://gist.github.com/triagonal/78fcb62e4dbf8b90074cb063b7c947b8

**Comment by JadssDev** [comment]
Still Replicatable in version 2.17.2.1
