### ISSUE TITLE
Just updated EssentialsX got this error and can't join.

### ISSUE THREAD

**Issue by xLegend** [EssentialsX/Essentials#306]
[11:39:29 INFO]: UUID of player xLeGeNdZxASH is 2609fa06-991a-43c2-a64c-097e9d035f57
[11:39:29 WARN]: Failed to handle packet for /"my ip here"
net.minecraft.server.v1_8_R3.ReportedException: Sending packet
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:908) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:171) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:813) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
Caused by: java.lang.LinkageError: com/comphenix/protocol/events/PacketContainer
        at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:277) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:417) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:84) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.handleScheduled(NettyChannelInjector.java:383) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$6.onMessageScheduled(NettyChannelInjector.java:351) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:894) ~[spigot.jar:git-Spigot-74e8786-a3cb1bc]
        ... 10 more
Can anyone help and tell me how I can fix this?

**Comment by vemacs** [comment]
This has nothing to do with EssentialsX, it's a (not-consistently-reproducible) issue with the Bukkit classloader. Restart your server.

**Comment by xLegend** [comment]
Thanks I already restarted again and it worked, I just thought it was EssX since it broke after i updated, great plugin btw cx
