### ISSUE TITLE
config.yml.broken.1585167146454

### ISSUE THREAD

**Issue by Eth-1** [EssentialsX/Essentials#3092]
### Information

Full output of `/ess version`:
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-144 (MC: 1.15.2)
[16:36:00 INFO]: EssentialsX version: 2.17.2.0
[16:36:00 INFO]: LuckPerms version: 5.0.72
[16:36:00 INFO]: EssentialsXChat version: 2.17.2.0
[16:36:00 INFO]: EssentialsXGeoIP version: 2.17.2.0
[16:36:00 INFO]: EssentialsXAntiBuild version: 2.17.2.0
[16:36:00 INFO]: EssentialsXSpawn version: 2.17.2.0
[16:36:00 INFO]: EssentialsXXMPP version: 2.17.2.0
[16:36:00 INFO]: EssentialsXProtect version: 2.17.2.0

**Server log:** 
https://mclo.gs/C2tGDwV
**EssentialsX config** 

### Help request

**Problem**

**config.yml.broken.1585167146454**
EssentialsX does not save my configuration for the config.yml file.
And when the first person joined the server the log says;
_[16:18:35 WARN]: [Essentials] Task #286 for Essentials v2.17.2.0 generated an exception
java.lang.NullPointerException: null
at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:150) ~[?:?]
at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[minecraft_server.jar:git-Paper-144]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[minecraft_server.jar:git-Paper-144]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[minecraft_server.jar:git-Paper-144]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[minecraft_server.jar:git-Paper-144]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[minecraft_server.jar:git-Paper-144]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[minecraft_server.jar:git-Paper-144]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[16:18:35 INFO]: [Essentials] Creating empty config: /aternos/server/plugins/Essentials/userdata/0e96f8b2-bceb-4e01-8b43-e148a4db7200.yml_
**What I have tried**

I have tried reloading the plugin restartuing server etc.
**Screenshots**

**Comment by pop4959** [comment]
config.yml.broken means you have failed to properly configure Essentials. This is usually due to incorrect formatting in the file (such as tabs instead of spaces, incorrect spacing, invalid characters, etc). If you're stuck, start over and change only ***one*** thing at a time, to make sure you figure out what you're doing wrong.

The exception from XMPPManager means that you have EssentialsXXMPP installed, but you have not configured it correctly. Do so, or remove the plugin if you aren't using it.
