### ISSUE TITLE
NullPointerException: null on convertIgnoreList storage to UUID-based

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#3223]
Essentials dev 894.

Caused by this commit? https://github.com/EssentialsX/Essentials/commit/1bc1f646fd7d242cd202e5598a0f662b05e6ae9e

Downgrading to dev 890, start-up is fine.

```
[04:45:37] [Server thread/INFO]: [Essentials] Enabling Essentials v2.17.2.74
[04:45:37] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[04:45:37] [Server thread/INFO]: [Essentials] No kits found to migrate.
[04:45:38] [Server thread/INFO]: [Essentials] File: plugins/Essentials/userdata/9455b4aa-eee1-4d11-84d4-fc644ff64062.yml
[04:45:38] [Server thread/ERROR]: Error occurred while enabling Essentials v2.17.2.74 (Is it up to date?)
java.lang.NullPointerException: null
	at com.earth2me.essentials.EssentialsUpgrade.convertIgnoreList(EssentialsUpgrade.java:68) ~[?:?]
	at com.earth2me.essentials.EssentialsUpgrade.afterSettings(EssentialsUpgrade.java:757) ~[?:?]
	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:221) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-245]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-245]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-245]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) ~[patched_1.15.2.jar:git-Paper-245]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) ~[patched_1.15.2.jar:git-Paper-245]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-245]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-245]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:895) ~[patched_1.15.2.jar:git-Paper-245]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[04:45:38] [Server thread/INFO]: [Essentials] Disabling Essentials v2.17.2.74
```

**Comment by JRoy** [comment]
Pushing a fix in about ~10 minutes
