### ISSUE TITLE
Error with geoip on player login

### ISSUE THREAD

**Issue by FabioZumbi12** [EssentialsX/Essentials#3322]
### Information

**Full output of `/ess version`**:

```
[04:18:33 INFO]: CONSOLE issued server command: /ess version
[04:18:33 INFO]: Server versão: 1.15.2-R0.1-SNAPSHOT git-Paper-304 (MC: 1.15.2)
[04:18:33 INFO]: EssentialsX versão: 2.17.2.99
[04:18:33 INFO]: PlaceholderAPI versão: 2.10.5
[04:18:33 INFO]: LuckPerms versão: 5.0.72
[04:18:33 INFO]: Vault versão: 1.7.2-b107
[04:18:33 INFO]: Citizens versão: 2.0.26-SNAPSHOT (build 1846)
[04:18:33 INFO]: EssentialsXGeoIP versão: 2.17.2.99
[04:18:33 INFO]: EssentialsXSpawn versão: 2.17.2.99
[04:18:33 INFO]: ChestShop versão: 3.10.1 (build 174)
```

**Server log**: https://gist.github.com/FabioZumbi12/c54d46b8ba1a48d91f925455343b4c9d

**EssentialsX config**: https://gist.github.com/FabioZumbi12/7b73ff1c66dc78c4d3cc08d26ad04d19

### Details

**Description**  
The stack trace drops on every player login

**Steps to reproduce**  
Just on player login

**Expected behavior**  
No errors on login

**Screenshots**  
No print, only the error log (present on latest.log multiple times):
```
[04:13:20] [Craft Scheduler Thread - 916/WARN]: [Essentials] Plugin Essentials v2.17.2.99 generated an exception while executing task 46805
java.lang.AbstractMethodError: com.fasterxml.jackson.databind.ext.Java7Support.getDeserializerForJavaNioFilePath(Ljava/lang/Class;)Lcom/fasterxml/jackson/databind/JsonDeserializer;
	at com.fasterxml.jackson.databind.ext.OptionalHandlerFactory.findDeserializer(OptionalHandlerFactory.java:122) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findOptionalStdDeserializer(BasicDeserializerFactory.java:1589) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.findDefaultDeserializer(BasicDeserializerFactory.java:1812) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.findStdDeserializer(BeanDeserializerFactory.java:161) ~[?:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:125) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[?:?]
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[?:?]
	at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:477) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1938) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:677) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader.forType(ObjectReader.java:697) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:982) ~[?:?]
	at com.fasterxml.jackson.databind.ObjectReader.treeToValue(ObjectReader.java:1530) ~[?:?]
	at com.maxmind.geoip2.DatabaseReader.get(DatabaseReader.java:193) ~[?:?]
	at com.maxmind.geoip2.DatabaseReader.country(DatabaseReader.java:227) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.delayedJoin(EssentialsGeoIPPlayerListener.java:80) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.lambda$onPlayerJoin$0(EssentialsGeoIPPlayerListener.java:48) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-304]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-304]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-304]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by pop4959** [comment]
Do you have GeoIP properly configured? If not, do so or remove the plugin. If yes, it's possible that your GeoIP database is corrupted. Try deleting it and let the plugin re-download it on restart.
