### ISSUE TITLE
Error occurred while enabling Essentials v2.17.2.99

### ISSUE THREAD

**Issue by RalphORama** [EssentialsX/Essentials#3330]
### Information

**Full output of `/ess version`**:  Cannot use command because plugin fails to enable.

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: https://pastebin.com/dJ5506DG

**EssentialsX config**: https://pastebin.com/URk6i6vc

### Details

**Description**  

After upgrading to EssentialsX v2.17.2.99, the plugin no longer starts correctly.  I get the following error in console:

```
[06:24:00 ERROR]: Error occurred while enabling Essentials v2.17.2.99 (Is it up to date?)
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 885233 path $.eccomspphinmobspawner
at com.google.gson.internal.Streams.parse(Streams.java:60) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[patched_1.15.2.jar:git-Paper-312]
at com.earth2me.essentials.items.FlatItemDb.loadJSON(FlatItemDb.java:75) ~[?:?]
at com.earth2me.essentials.items.FlatItemDb.rebuild(FlatItemDb.java:62) ~[?:?]
at com.earth2me.essentials.items.FlatItemDb.reloadConfig(FlatItemDb.java:51) ~[?:?]
at com.earth2me.essentials.Essentials.reload(Essentials.java:406) ~[?:?]
at com.earth2me.essentials.Essentials.onEnable(Essentials.java:266) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-312]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-312]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-312]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-312]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-312]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-312]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-312]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-312]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 885233 path $.eccomspphinmobspawner
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:530) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[patched_1.15.2.jar:git-Paper-312]
at com.google.gson.internal.Streams.parse(Streams.java:48) ~[patched_1.15.2.jar:git-Paper-312]
... 17 more
[06:24:00 INFO]: [Essentials] Disabling Essentials v2.17.2.99
```

**Steps to reproduce**  

1. Install PaperMC version git-Paper-312 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
2. Install EssentialsX v2.17.2.99
3. The above error occurs

**Expected behavior**  

No error occurs

**Screenshots**  

N/A

**Comment by RalphORama** [comment]
Looks like `items.json` was corrupted.  I deleted the file and restarted my server, which fixed the issue.
