### ISSUE TITLE
Essentials making synchronized database lookup

### ISSUE THREAD

**Issue by NubeBuster** [EssentialsX/Essentials#3363]
[20:09:10 WARN]: [Essentials] Task #159091 for Essentials v2.17.2.99 generated an exception
java.lang.RuntimeException: The operation to load user data for 'd6988abb-0d7e-4a65-93ca-5a61855a16a0' was cancelled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to
load data for offline players from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:166) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userGetPrimaryGroup(LuckPermsVaultPermission.java:271) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPrimaryGroup(AbstractVaultPermission.java:385) ~[?:?]
        at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]
        at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]
        at com.earth2me.essentials.User.getGroup(User.java:705) ~[?:?]
        at com.earth2me.essentials.textreader.TextInput.<init>(TextInput.java:29) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask$DelayMotdTask.run(EssentialsPlayerListener.java:371) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener$1DelayJoinTask.run(EssentialsPlayerListener.java:312) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-341]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1256) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1173) ~[patched_1.15.2.jar:git-Paper-341]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-341]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by JRoy** [comment]
Please reopen your issue after properly following the issue template. You've given no information on how to reproduce this as well as no plugin versions.
