### ISSUE TITLE
Essentials Chat is not working

### ISSUE THREAD

**Issue by Industrial1107** [EssentialsX/Essentials#3393]
Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
	at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:121) ~[?:?]
	at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getUser(Permission_PermissionsEx.java:243) ~[?:?]
	at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getPrimaryGroup(Permission_PermissionsEx.java:264) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getGroup(AbstractVaultHandler.java:33) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getGroup(PermissionsHandler.java:28) ~[?:?]
	at com.earth2me.essentials.User.getGroup(User.java:687) ~[?:?]
	at com.earth2me.essentials.chat.EssentialsChatPlayerListenerLowest.onPlayerChat(EssentialsChatPlayerListenerLowest.java:41) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	... 11 more
[12:49:35 ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.17.2.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
	at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:121) ~[?:?]
	at net.milkbowl.vault.chat.plugins.Chat_PermissionsEx.getUser(Chat_PermissionsEx.java:108) ~[?:?]
	at net.milkbowl.vault.chat.plugins.Chat_PermissionsEx.getPlayerPrefix(Chat_PermissionsEx.java:292) ~[?:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91) ~[?:?]
	at com.earth2me.essentials.perm.impl.AbstractVaultHandler.getPrefix(AbstractVaultHandler.java:48) ~[?:?]
	at com.earth2me.essentials.perm.PermissionsHandler.getPrefix(PermissionsHandler.java:73) ~[?:?]
	at com.earth2me.essentials.User.getNick(User.java:356) ~[?:?]
	at com.earth2me.essentials.User.getNick(User.java:325) ~[?:?]
	at com.earth2me.essentials.User.setDisplayNick(User.java:385) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:121) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24]
	... 11 more

**Comment by mdcfe** [comment]
In the future, please fill out the support template.

In this case it appears PEX didn't load properly - this isn't an EssentialsX issue. We don't support PEX 1.x (and you won't get much help anywhere else either) - we strongly recommend importing your permissions setup into [LuckPerms](https://luckperms.net).
