### ISSUE TITLE
Spigot 1.16.1: NullPointerException on plugin enable

### ISSUE THREAD

**Issue by BenWoodworth** [EssentialsX/Essentials#3413]
### Information

**Full output of `/ess version`**:

```
Server version: 1.16.1-R0.1-SNAPSHOT git-Spigot-758abbe-8dc1da1 (MC: 1.16.1)
EssentialsX version: 2.17.2.0
LuckPerms version: 5.0.72
Vault is not installed. Chat and permissions may not work.
You are running an unsupported server version!
```

**Server log**: https://gist.github.com/BenWoodworth/d25de113978e94f98489d106fdf80991

**EssentialsX config**: https://gist.github.com/BenWoodworth/989d73554a003e2b50f68af2ccd8bd4e

### Details

**Description**  
```
[16:28:11] [Server thread/ERROR]: Error occurred while enabling Essentials v2.17.2.0 (Is it up to date?)
java.lang.NullPointerException: null
	at net.ess3.providers.ProviderFactory.getProvider(ProviderFactory.java:25) ~[?:?]
	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:249) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:489) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:403) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:439) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:811) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:165) ~[spigot-1.16.1.jar:git-Spigot-758abbe-8dc1da1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Comment by BenWoodworth** [comment]
Just checked the commits and it looks like this is being taken care of :)

**Comment by triagonal** [comment]
Download the newest build at https://essentialsx.net/downloads.html for a version that works on 1.16. Keep in mind that this build does not yet include 1.16 features (new items, mobs, RGB colors, etc). Follow the EssentialsX #updates channel on the [MOSS discord](https://discord.gg/PHpuzZS) for 1.16 related announcements.
