### ISSUE TITLE
Error: Unknown item name: minecraft:stone

### ISSUE THREAD

**Issue by endigma** [EssentialsX/Essentials#3564]
# Information

Full output of `/ess version`:

```
[02:10:57 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-384 (MC: 1.15.2)
[02:10:57 INFO]: EssentialsX version: 2.18.0.0
[02:10:57 INFO]: LuckPerms version: 5.1.26
[02:10:57 INFO]: Vault version: 1.7.2-b107
[02:10:57 INFO]: EssentialsXChat version: 2.18.0.0
```

**Server log:** 
I've deliberately included only the problem area, I'm reasonably confident this error is not elsewhere in the log, as there is not so much as an EssentialsX related warning in the entire log. 
```log
[02:13:44 INFO]: endigma_ issued server command: /i minecraft:stone
[02:13:44 INFO]: [Essentials] checking if endigma_ has essentials.mail - true
[02:13:44 INFO]: [Essentials] checking if endigma_ has essentials.item - true
[02:13:44 INFO]: [Essentials] checking if endigma_ can afford charge.
[02:13:44 INFO]: [Essentials] calculated command (item) cost for endigma_ as 0
[02:13:44 INFO]: [Essentials] Trying to deserialize item 'minecraft:stone' with resolver 'essentials:custom_items'...
[02:13:44 INFO]: [Essentials] Error calling the command /i
java.lang.Exception: §4Unknown item name: minecraft:stone.
        at com.earth2me.essentials.items.FlatItemDb.get(FlatItemDb.java:117) ~[?:?]
        at com.earth2me.essentials.items.AbstractItemDb.get(AbstractItemDb.java:87) ~[?:?]
        at com.earth2me.essentials.commands.Commanditem.run(Commanditem.java:29) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:168) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:615) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:525) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-384]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-384]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-384]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[02:13:44 WARN]: java.lang.Exception: Unknown item name: minecraft:stone.
[02:13:44 WARN]:        at com.earth2me.essentials.items.FlatItemDb.get(FlatItemDb.java:117)
[02:13:44 WARN]:        at com.earth2me.essentials.items.AbstractItemDb.get(AbstractItemDb.java:87)
[02:13:44 WARN]:        at com.earth2me.essentials.commands.Commanditem.run(Commanditem.java:29)
[02:13:44 WARN]:        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:168)
[02:13:44 WARN]:        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:615)
[02:13:44 WARN]:        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:525)
[02:13:44 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:13:44 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[02:13:44 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060)
[02:13:44 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975)
[02:13:44 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**EssentialsX config** 
Impertinent

### Help request

**Problem**
Verbose item namings such as  `minecraft:stone` return failures inside (`/`i, `/item`, `/give`) or any other item related commands after upgrading from EssentialsX v17 to v18

Using the sort of incorrect shorthand item names still works, i.e. `/i stone` but using the full names or IDs resolves to nothing.x

**What I have tried**
- Regenerate items.json
- Update PaperMC
- Search for fix on the web

**Comment by pop4959** [comment]
Unable to replicate this behavior on either 2.17.2 or 2.18.0. Regardless of whether it did work before, however, the system was not designed to use `minecraft:` prefixed item names. If you wish to use those, use `/minecraft:give` instead. Essentials requires that items are typed in the standard format as presented in the [Bukkit Material API](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html).
