### ISSUE TITLE
Bug with MMOCORE? 

### ISSUE THREAD

**Issue by jajamic** [EssentialsX/Essentials#3591]
### Information

**Full output of `/ess version`**: 2.18.0.18
Server 1.15.2 - R0.1-SNAPSHOT git-Paper-385

```
No command just when my player spawn I have this error. I m using MMOCORE I think it s that.
```

**Server log**: (fuull logs : https://pastebin.com/bTybreuf
```
[00:33:27] [Server thread/INFO]: [Essentials] Found new UUID for TatuVNR. Replacing 5dc26acf-4af4-327c-a353-20b2bc07bb3a with a3b7a405-623c-42b9-b42e-06f4a5a408a8
[00:33:27] [Server thread/WARN]: java.lang.IllegalArgumentException: Health must be between 0 and 13.0, but was 18.0. (attribute base value: 20.0, player: TatuVNR)
[00:33:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112)
[00:33:27] [Server thread/WARN]: 	at net.craftersland.data.bridge.events.handlers.HealthDataHandler$1.run(HealthDataHandler.java:68)
[00:33:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[00:33:27] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[00:33:27] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1265)
[00:33:27] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[00:33:27] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182)
[00:33:27] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971)
[00:33:27] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**EssentialsX config**: 

### Details

**Description**  
I see just that when a player connect in MyLog.

**Comment by JRoy** [comment]
Not remotely related to Essentials
