### ISSUE TITLE
Respawn Bug - After death the player is teleported to the wrong place and this appears in the console:

### ISSUE THREAD

**Issue by XANT3R** [EssentialsX/Essentials#3617]
After death the player is teleported to the wrong place and this appears in the console:

```
[17:33:44] [Server thread/INFO]: sonjax1999 was slain by Hoglin
[17:33:49] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to EssentialsSpawn v2.18.0.18
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftPlayer.getBedSpawnLocation(CraftPlayer.java:884) ~[patched_1.16.1.jar:git-Paper-131]
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.onPlayerRespawn(EssentialsSpawnPlayerListener.java:52) ~[?:?]
	at com.earth2me.essentials.spawn.EssentialsSpawn.lambda$onEnable$0(EssentialsSpawn.java:44) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:806) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:715) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2186) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PacketPlayInClientCommand.a(SourceFile:30) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[17:34:07] [Server thread/INFO]: sonjax1999 issued server command: /home home
```

This bug may also be affected by the situation that some time ago I moved players from a damaged map to a new one. They may have kept the bed on this damaged map. However userdata does not indicate this because there is only one home, and that is in the correct world. I haven't seen a fix to that in the development version, so I suppose no one caught this bug. Spawn is in world nether.

**Comment by JRoy** [comment]
Please fill out the issue template and resubmit your issue.
