### ISSUE TITLE
Could not pass event PlayerChangedWorldEvent to Essentials v2.18.1.13

### ISSUE THREAD

**Issue by sphings79** [EssentialsX/Essentials#3689]
On Paper 1.15.2 latest:

[12:33:03 ERROR]: Could not pass event PlayerChangedWorldEvent to Essentials v2.18.1.13
java.lang.NullPointerException: null
        at com.earth2me.essentials.paperlib.features.asyncchunks.AsyncChunksPaper_15.getChunkAtAsync(AsyncChunksPaper_15.java:11) ~[?:?]
        at com.earth2me.essentials.paperlib.environments.Environment.getChunkAtAsync(Environment.java:84) ~[?:?]
        at com.earth2me.essentials.paperlib.PaperLib.getChunkAtAsync(PaperLib.java:146) ~[?:?]
        at com.earth2me.essentials.paperlib.features.bedspawnlocation.BedSpawnLocationPaper.getBedSpawnLocationAsync(BedSpawnLocationPaper.java:17) ~[?:?]
        at com.earth2me.essentials.paperlib.environments.Environment.getBedSpawnLocationAsync(Environment.java:104) ~[?:?]
        at com.earth2me.essentials.paperlib.PaperLib.getBedSpawnLocationAsync(PaperLib.java:201) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener.updateCompass(EssentialsPlayerListener.java:412) ~[?:?]
        at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChangedWorld(EssentialsPlayerListener.java:637) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor153.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-387]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.PlayerList.moveToWorld(PlayerList.java:817) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleport(CraftPlayer.java:807) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.entity.Entity.lambda$teleportAsync$0(Entity.java:177) ~[patched_1.15.2.jar:git-Paper-387]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
        at org.bukkit.entity.Entity.teleportAsync(Entity.java:177) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.teleportAsync(CraftPlayer.java:745) ~[patched_1.15.2.jar:git-Paper-387]
        at com.earth2me.essentials.paperlib.features.asyncteleport.AsyncTeleportPaper_13.teleportAsync(AsyncTeleportPaper_13.java:13) ~[?:?]
        at com.earth2me.essentials.paperlib.environments.Environment.teleport(Environment.java:92) ~[?:?]
        at com.earth2me.essentials.paperlib.PaperLib.teleportAsync(PaperLib.java:87) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.lambda$nowAsync$3(AsyncTeleport.java:216) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.execute(IAsyncTaskHandler.java:89) ~[patched_1.15.2.jar:git-Paper-387]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1069) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1057) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1104) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1085) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1075) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1267) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by pop4959** [comment]
Please provide all of the information requested in the issue template. Error prints on their own are often not enough.

**Comment by JRoy** [comment]
Confirmed. Pending https://github.com/PaperMC/PaperLib/pull/31 being merged for a fix.
