### ISSUE TITLE
WTF?

### ISSUE THREAD

**Issue by muskin-a** [EssentialsX/Essentials#3835]
[02:07:51] [Server thread/ERROR] [net.minecraft.network.NetHandlerPlayServer]: null
 org.bukkit.command.CommandException: Unhandled exception executing command 'gamemode' in plugin Essentials v2.18.2.0
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[PluginCommand.class:9e0b1b1]
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[SimpleCommandMap.class:9e0b1b1]
 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) ~[CraftServer.class:9e0b1b1]
 at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1615) [pa.class:?]
 at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1450) [pa.class:?]
 at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:50) [la.class:?]
 at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:11) [la.class:?]
 at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_231]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_231]
 at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
 at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:924) [MinecraftServer.class:?]
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) [nz.class:?]
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861) [MinecraftServer.class:?]
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
 at com.earth2me.essentials.Essentials.onCommand(Essentials.java:569) ~[?:?]
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:9e0b1b1]
 ... 15 more
gamemode 1 Dullahan
[02:08:32] [Server thread/INFO] []: java.lang.NullPointerException
[02:08:32] [Server thread/WARN] [Minecraft]: Unexpected exception while parsing console command "gamemode 1 Dullahan"
 org.bukkit.command.CommandException: Unhandled exception executing command 'gamemode' in plugin Essentials v2.18.2.0
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[PluginCommand.class:9e0b1b1]
 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[SimpleCommandMap.class:9e0b1b1]
 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:688) ~[CraftServer.class:9e0b1b1]
 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:673) [CraftServer.class:9e0b1b1]
 at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:499) [nz.class:?]
 at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:457) [nz.class:?]
 at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861) [MinecraftServer.class:?]
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733) [MinecraftServer.class:?]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.NullPointerException
 at com.earth2me.essentials.Essentials.onCommand(Essentials.java:569) ~[?:?]
 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:9e0b1b1]
 ... 8 more

**Comment by Chew** [comment]
Missing template. Please fill out a new issue, filling out the template completely.
