### ISSUE TITLE
I actually don't understand what is going on rn...

### ISSUE THREAD

**Issue by trustmebro** [EssentialsX/Essentials#389]
So basically, I've been trying to get a server up and running (from my computer, not that website hosting stuff) and I need essentials, and I tried getting the normal 1.8 essentials from jenkins, but that doesnt work, and then I install this, it does the same thing.

[17:56:12 ERROR]: Could not load 'plugins/EssentialsX-2.0.1 (2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/earth2me/essentials/Essentials : Unsupported major.minor version 51.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit.jar:git-Bukkit-b105298]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit.jar:git-Bukkit-b105298]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Bukkit-b105298]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-b105298]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-b105298]
    at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-b105298]
    at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-b105298]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [craftbukkit.jar:git-Bukkit-b105298]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503) [craftbukkit.jar:git-Bukkit-b105298]
    at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
Caused by: java.lang.UnsupportedClassVersionError: com/earth2me/essentials/Essentials : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[craftbukkit.jar:git-Bukkit-b105298]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-b105298]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
    at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
    at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:40) ~[craftbukkit.jar:git-Bukkit-b105298]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit.jar:git-Bukkit-b105298]
    ... 9 more

**Comment by SupaHam** [comment]
You need to update to Java 7.
