### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by sk1pdxdxdx** [EssentialsX/Essentials#3921]
I have a big problem 

[14:44:14] [Server thread/ERROR]: Could not pass event PlayerRespawnEvent to EssentialsSpawn v2.18.2.0
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerRespawnEvent.isAnchorSpawn()Z
	at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.onPlayerRespawn(EssentialsSpawnPlayerListener.java:45) ~[?:?]
	at com.earth2me.essentials.spawn.EssentialsSpawn.lambda$onEnable$0(EssentialsSpawn.java:43) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-21]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-21]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:794) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerList.moveToWorld(PlayerList.java:704) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2182) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PacketPlayInClientCommand.a(SourceFile:30) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PacketPlayInClientCommand.a(SourceFile:8) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004) ~[patched_1.16.1.jar:git-Paper-21]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-21]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by triagonal** [comment]
EssentialsX does not support 1.16.1, please update to 1.16.4 and the latest version of Paper [here](https://papermc.io/downloads).
