### ISSUE TITLE
EssentialsXMPP - Console warning spam, not connecting to XMPP

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4101]
### Type of bug

Error in console, Other unexpected behaviour

### `/ess version` output

[20:52:17 INFO]: CONSOLE issued server command: /ess version
[20:52:17 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
[20:52:17 INFO]: EssentialsX version: 2.18.2.0
[20:52:17 INFO]: LuckPerms version: 5.3.15
[20:52:17 INFO]: Vault version: 1.7.3-b131
[20:52:17 INFO]: EssentialsXChat version: 2.18.2.0
[20:52:17 INFO]: EssentialsXXMPP version: 2.18.2.0

### Server startup log

https://gist.github.com/crispy-cat/ed80ed56e97a383916c6b2dfc06ce1f8

### EssentialsX config files

Essentials: https://gist.github.com/crispy-cat/70d5ce0e6954eaf5f881d2e262cb4aaa; EssentialsXMPP: https://gist.github.com/crispy-cat/5babd426a7f40c4b107e7d2f8b01f6e6

### Bug description

Rather than connecting to the XMPP server and accepting commands, it spams the console with:

[20:52:18 WARN]: stream:error (text)
[20:52:18 WARN]: 	at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:260)
[20:52:18 WARN]: 	at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:43)
[20:52:18 WARN]: 	at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:70)

### Steps to reproduce

1. Have a server with EssentialsXMPP
3. ???
4. no profit :(

### Expected behaviour

Sending commands from XMPP should run them 

### Actual behaviour

Spams console

**Comment by Laarryy** [comment]
Hey. That error suggests perhaps that you're trying to log in more than once with the same credentials. To quote [some random resource I found on the internet on this error](https://discourse.igniterealtime.org/t/smack-exception-stream-error-text/71142) 

> Check to see if the same user is trying to log in... more than once using the same resource name. If userX is logging into the MUC mychat@conference.server/resource1 more than once, you will get that message.

**Comment by pop4959** [comment]
Closing since there has been no further response to this issue. I've also tested on my end and I do not see this error when correctly setting up an XMPP connection.
