### ISSUE TITLE
Problem with Chat

### ISSUE THREAD

**Issue by crazyRM** [EssentialsX/Essentials#4165]
### Type of bug

Error in console, Other unexpected behaviour

### `/ess version` output

Fresh install and i get this when talking (using luckperms btw)

### Server startup log

.

### EssentialsX config files

.

### Error log (if applicable)

[03:27:52] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to EssentialsChat v2.19.0-dev+122-23a497a org.bukkit.event.EventException: null         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:3079-Spigot-9fb885e-7df5e6f]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3079-Spigot-9fb885e-7df5e6f]         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) [server.jar:3079-Spigot-9fb885e-7df5e6f]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) [server.jar:3079-Spigot-9fb885e-7df5e6f]         at net.minecraft.server.v1_16_R3.PlayerConnection.chat(PlayerConnection.java:1857) [server.jar:3079-Spigot-9fb885e-7df5e6f]         at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1795) [server.jar:3079-Spigot-9fb885e-7df5e6f]         at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1733) [server.jar:3079-Spigot-9fb885e-7df5e6f]         at net.minecraft.server.v1_16_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:44) [server.jar:3079-Spigot-9fb885e-7df5e6f]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]         at java.lang.Thread.run(Thread.java:834) [?:?] Caused by: java.lang.NoSuchMethodError: 'boolean com.earth2me.essentials.User.isToggleShout()'         at com.earth2me.essentials.chat.EssentialsChatPlayer.getChatType(EssentialsChatPlayer.java:39) ~[?:?]         at com.earth2me.essentials.chat.EssentialsChatPlayerListenerLowest.onPlayerChat(EssentialsChatPlayerListenerLowest.java:36) ~[?:?]         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]         at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:3079-Spigot-9fb885e-7df5e6f]         ... 12 more [03:27:52] [Server thread/INFO]: <[Admin] Crazy_RM> xd

### Bug description

i get this problem when talking in chat

### Steps to reproduce

fresh install?

### Expected behaviour

error

### Actual behaviour

error

**Comment by triagonal** [comment]
Please fill out the issue form completely when you submit bug reports, we need the information to properly diagnose your issue.

From what I can tell, you're likely using mismatched versions of the EssentialsX and EssentialsXChat plugins. Please delete the EssentialsX plugin and all EssentialsX add-ons from your `/plugins` folder and download new copies from https://essentialsx.net/downloads.html.

**Comment by triagonal** [comment]
Closing - no response from OP. If you're still having problems, please reply to this issue with a completely filled out issue form so we can look into this further.
