### ISSUE TITLE
Entering the wrong /home name returns 'Error: null' instead of 'invalidHomeName'

### ISSUE THREAD

**Issue by baailey** [EssentialsX/Essentials#4233]
### Type of bug

Other unexpected behaviour

### `/ess version` output

14.06 15:53:05 [Server] INFO Server version: 1.16.5-R0.1-SNAPSHOT git-Airplane-"fad74c2" (MC: 1.16.5)
14.06 15:53:05 [Server] INFO Brand version: Airplane
14.06 15:53:05 [Server] INFO EssentialsX version: 2.19.0-dev+160-c43af5d
14.06 15:53:05 [Server] INFO Vault version: 1.7.3-b131
14.06 15:53:05 [Server] INFO Fetching version information...
14.06 15:53:05 [Server] INFO You're running the latest EssentialsX dev build!

### Server startup log

https://gist.github.com/baailey/a3e84df8f2946b4ff745ae3eb9e952d9

### EssentialsX config files

https://gist.github.com/baailey/b56181455fd36d11e6074c77b63cd272

### Bug description

When using the /home [home] command to teleport to one of your many homes, the error message 'Error: null' will appear if you enter the wrong home name.

### Steps to reproduce

1. Set multiple homes
2. Use /home and intentionally write the name of a home that doesn't exist

### Expected behaviour

The 'invalidHomeName' message should appear saying "Invalid home name!"

### Actual behaviour

The wrong error message appears when writing the wrong home name.

https://gfycat.com/InsidiousFrightenedDevilfish

**Comment by triagonal** [comment]
Confirmed on:
```
[02:27:52 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-777 (MC: 1.16.5)
[02:27:52 INFO]: Brand version: Paper
[02:27:52 INFO]: EssentialsX version: 2.19.0-dev+160-c43af5d
```
It should be noted that the previous behaviour was to list all existing homes rather than use the `invalidHomeName` message, but it's a bug either way.

Stacktrace:
```
[02:28:35 WARN]: java.lang.NullPointerException
[02:28:35 WARN]:        at com.earth2me.essentials.UserData.getHome(UserData.java:158)
[02:28:35 WARN]:        at com.earth2me.essentials.commands.Commandhome.goHome(Commandhome.java:127)
[02:28:35 WARN]:        at com.earth2me.essentials.commands.Commandhome.run(Commandhome.java:68)
[02:28:35 WARN]:        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:232)
[02:28:35 WARN]:        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:749)
[02:28:35 WARN]:        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:652)
[02:28:35 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
						...
```
