### ISSUE TITLE
EssentialsX 2.18.2 Not a JSON Object

### ISSUE THREAD

**Issue by CodexApple** [EssentialsX/Essentials#4255]
### Type of bug

Compatibility issue

### `/ess version` output

> ess version
[01:31:42 WARN]: Unexpected exception while parsing console command "ess version"
org.bukkit.command.CommandException: Cannot execute command 'ess' in plugin Essentials v2.18.2.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-778]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:788) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:437) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-778]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-778]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Server startup log

https://paste.gg/p/anonymous/c2f4300a1375487791f71bc848fa533a

### EssentialsX config files

default config.yml

### Error log (if applicable)

https://paste.gg/p/anonymous/c2f4300a1375487791f71bc848fa533a

### Bug description

Just downloaded Paper 1.16.5 Build 778 running Java 16

### Steps to reproduce

Download a copy of Paper 1.16.5, run it in localhost
Download a copy of EssentialsX 2.18.2, placed it on Plugins folder

### Expected behaviour

Everything should run normally without an error

### Actual behaviour

There as a huge spammed error

![image](https://user-images.githubusercontent.com/41129289/122683380-523ea600-d231-11eb-8d1d-52f5e5006aa6.png)

**Comment by Chew** [comment]
Your items.Json file is corrupt

**Comment by CodexApple** [comment]
> Your items.Json file is corrupt

Yeah, and that doesn't help me since the JSON corruption lies at the start of EssentialsX I haven't changed nor touched anything literally just put the file inside the plugins folder.

**Comment by CodexApple** [comment]
Tried deleting the JSON file but still persist

**Comment by mdcfe** [comment]
Cannot replicate on a fresh download of Paper 1.16.5 build 778 and EssentialsX 2.18.2.

Could you run `java -version` in a command prompt (you appear to be on Windows) and post the output?

In addition, could you try the following:
- Stop your server
- Delete both the EssentialsX jar *and* the `items.json` file
- Redownload EssentialsX from [the website](https://essentialsx.net/downloads.html?branch=stable)
- Restart your server

**Comment by CodexApple** [comment]
![image](https://user-images.githubusercontent.com/41129289/122900165-06017c00-d37f-11eb-9006-46619fe5fb96.png)

I did what you've said and I'm still having the error however, after adding Vault and LuckPerms the problem goes away, I guess for now it can be fixed? I'll try experimenting for more incase I'll try compiling and create about it.

**Comment by pop4959** [comment]
Unable to replicate on my end either, using the *exact* same JVM version, Paper version, and EssentialsX version. The error printed also comes from the Gson library while parsing itemdb. The only thing I can think of is that either your items.json file is invalid, or perhaps you have a corrupt EssentialsX or Paper jar (in which case redownloading may help).

Will close this issue for now but if you do find further information which shows this to be a bug we can re-open it.
