### ISSUE TITLE
/itemdb with spawnegg return Error: null on line 3/3

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#4275]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[18:26:56] [Client thread/INFO]: [CHAT] Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsX version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] PermissionsEx version: 1.23.4
[18:26:56] [Client thread/INFO]: [CHAT] Vault version: 1.7.3-b131
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXProtect version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXSpawn version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXChat version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXGeoIP version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXAntiBuild version: 2.18.2.0

### Server startup log

nothing wrong with this

### EssentialsX config files

nothing wrong with this

### Error log (if applicable)

nothing wrong with this

### Bug description

/itemdb when handling spawn_egg will output with Error: null on line number 3

line 1 fine
line 2 fine
line 3 Error: null

### Steps to reproduce

1/ Give yourself /op
2/ Handling spawn_egg
3/ Use /itemdb

output
line 1 f

### Expected behaviour

It should return nothing but Error: null

### Actual behaviour

line 1 fine
line 2 fine
line 3 Error: null

**Comment by triagonal** [comment]
Confirmed on:

```
[04:25:13 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
[04:25:13 INFO]: Brand version: Paper
[04:25:13 INFO]: EssentialsX version: 2.19.0-dev+181-5c08a0e
```
Error:

![image](https://user-images.githubusercontent.com/10545540/124172749-8b0e3300-daed-11eb-8365-fb004338d8a3.png)

Stacktrace:

```
[04:24:57 WARN]: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "item" is null
[04:24:57 WARN]:        at com.earth2me.essentials.items.CustomItemResolver.getAliasesFor(CustomItemResolver.java:48)
[04:24:57 WARN]:        at com.earth2me.essentials.commands.Commanditemdb.run(Commanditemdb.java:58)
[04:24:57 WARN]:        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:168)
[04:24:57 WARN]:        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:163)
[04:24:57 WARN]:        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:762)
[04:24:57 WARN]:        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:665)
```
