### ISSUE TITLE
The permission essentials.nick.changecolors seems to not working properly

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#4289]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[INFO] Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)

[INFO] EssentialsX version: 2.18.2.0

[INFO] PermissionsEx version: 1.23.4

[INFO] Vault version: 1.7.3-b131

[INFO] EssentialsXProtect version: 2.18.2.0

[INFO] EssentialsXSpawn version: 2.18.2.0

[INFO] EssentialsXGeoIP version: 2.18.2.0

[INFO] EssentialsXChat version: 2.18.2.0

[INFO] EssentialsXAntiBuild version: 2.18.2.0

### Server startup log

nothing wrong with this

### EssentialsX config files

nothing wrong with this

### Error log (if applicable)

https://paste.gg/p/anonymous/7c3474907b9c47afa32121f84455c2c2

### Bug description

I don't know if it's a bug, but i can't find a way to use essentials.nick.changecolors permission to allow edit just color to a username.

### Steps to reproduce

Give yourself 
essentials.nick
essentials.nick.color
essentials.nick.changecolors

now enter /nick &a

Output &4Nicknames must be alphanumeric.

### Expected behaviour

Give yourself 
essentials.nick
essentials.nick.color
essentials.nick.changecolors

now enter /nick &a

output &6Your nickname is now "".

### Actual behaviour

Output &4Nicknames must be alphanumeric.

cannot use /nick "color"

**Comment by JRoy** [comment]
`essentials.nick.changecolors` is meant to be used by doing `/nick <color><username>` 

So if you wanted `&a` as your color and your username was `Notch`, you'd do `/nick &aNotch`

**Comment by ProblemsSender** [comment]
[INFO] dummy issued server command: /nick &asdjkhf

[INFO] [Essentials] checking if dummy has essentials.mail - false

[INFO] [Essentials] checking if dummy has essentials.nick - true

[INFO] [Essentials] checking if dummy can afford charge.

[INFO] [Essentials] calculated command (nick) cost for dummy as 0

[INFO] [Essentials] checking if dummy has essentials.nick.color - true

[INFO] [Essentials] checking if dummy has essentials.nick.format - false

[INFO] [Essentials] checking if dummy has essentials.nick.magic - false

[INFO] [Essentials] checking if dummy has essentials.nick.rgb - false

[INFO] [Essentials] checking if dummy has essentials.nick.changecolors - true

[INFO] [Essentials] checking if dummy has essentials.nick.changecolors.bypass - false

[INFO] [Essentials] Error calling the command /nick

java.lang.Exception: §4Nicknames can only have their colors changed.

at com.earth2me.essentials.commands.Commandnick.formatNickname(Commandnick.java:81) ~[?:?]

at com.earth2me.essentials.commands.Commandnick.run(Commandnick.java:36) ~[?:?]

at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:197) ~[?:?]

at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:660) ~[?:?]

at com.earth2me.essentials.Essentials.onCommand(Essentials.java:570) ~[?:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.12.2.jar:git-Paper-1618]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[patched_1.12.2.jar:git-Paper-1618]

at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$374/0x00000000c1440740.run(Unknown Source) ~[?:?]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_272]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_272]

at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]

at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]

at java.lang.Thread.run(Thread.java:823) [?:1.8.0_272]

[WARNING] java.lang.Exception: Nicknames can only have their colors changed.

[WARNING] at com.earth2me.essentials.commands.Commandnick.formatNickname(Commandnick.java:81)

[WARNING] at com.earth2me.essentials.commands.Commandnick.run(Commandnick.java:36)

[WARNING] at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:197)

[WARNING] at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:660)

[WARNING] at com.earth2me.essentials.Essentials.onCommand(Essentials.java:570)

[WARNING] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)

[WARNING] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)

[WARNING] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)

[WARNING] at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)

[WARNING] at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$$Lambda$374/0x00000000c1440740.run(Unknown Source)

[WARNING] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[WARNING] at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[WARNING] at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)

[WARNING] at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)

[WARNING] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)

[WARNING] at java.lang.Thread.run(Thread.java:823)

Am sorry, but I just tested it with your suggestion /nick "colorusername" by using /nick "&asdjkhf"
Now it's output with **Error: Nicknames can only have their colors changed.**

**Comment by ProblemsSender** [comment]
And for changing both the username, and the color. It requires essentials.nick.changecolors.bypass for that to be able to work. But I only want just essentials.nick.changecolors to work as it says in https://essinfo.xeya.me/permissions.html .

**Comment by JRoy** [comment]
> [INFO] dummy issued server command: /nick &asdjkhf

You'd need to do `/nick &adummy`

**Comment by ProblemsSender** [comment]
Can i use the command to another username with nick.others permissions? like /nick dummy &adummy ?

**Comment by ProblemsSender** [comment]
> > [INFO] dummy issued server command: /nick &asdjkhf
> 
> You'd need to do `/nick &adummy`

pls help me, i want to know how to give my helper the ability to change color for other usernames. i couldn't just use /nick dummy &adummy with nick.others and expecting it to change other username.
