### ISSUE TITLE
Using /tp <offlineUsername> without essentials.tpoffline result Error: null

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#4323]
### Type of bug

Other unexpected behaviour

### `/ess version` output

[18:26:56] [Client thread/INFO]: [CHAT] Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsX version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] PermissionsEx version: 1.23.4
[18:26:56] [Client thread/INFO]: [CHAT] Vault version: 1.7.3-b131
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXProtect version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXSpawn version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXChat version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXGeoIP version: 2.18.2.0
[18:26:56] [Client thread/INFO]: [CHAT] EssentialsXAntiBuild version: 2.18.2.0

### Server startup log

nothing wrong with this

### EssentialsX config files

nothing wrong with this

### Error log (if applicable)

nothing wrong with this

### Bug description

Instead of the result `Error: Player not found.`, it output `Error: null`

### Steps to reproduce

1/ Give yourself essentials.tp
2/ Use `/tp <offlineUsername>`

### Expected behaviour

Result `Error: Player not found.`

### Actual behaviour

Result `Error: null`

**Comment by triagonal** [comment]
Confirmed:
```
[22:38:03 INFO]: Server version: 1.17-R0.1-SNAPSHOT git-Paper-74 (MC: 1.17)
[22:38:03 INFO]: Brand version: Paper
[22:38:03 INFO]: EssentialsX version: 2.19.0-dev+196-33ca3b2
[22:38:03 INFO]: LuckPerms version: 5.3.48
[22:38:03 INFO]: Vault version: 1.7.3-b131
```

Stacktrace:
```
[22:37:36 INFO]: [Essentials] Error calling the command /tp
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getLocation()" because the return value of "org.bukkit.Server.getPlayerExact(String)" is null
        at com.earth2me.essentials.PlayerTarget.getLocation(PlayerTarget.java:16) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.nowAsync(AsyncTeleport.java:185) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.teleport(AsyncTeleport.java:292) ~[?:?]
        at com.earth2me.essentials.AsyncTeleport.teleport(AsyncTeleport.java:237) ~[?:?]
        at com.earth2me.essentials.commands.Commandtp.run(Commandtp.java:45) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:163) ~[?:?]
		...
```
