### ISSUE TITLE
[Essentials] null

### ISSUE THREAD

**Issue by aleshkanet** [EssentialsX/Essentials#447]
When i try to get bow from kit, I'm getting WARN in console 

> [Essentials] null

**Comment by vemacs** [comment]
What is your server version, and what happens if you do the same thing with /ess debug enabled

**Comment by aleshkanet** [comment]
Latest Spigot 1.8.8 build.

```
[19:29:17] [Server thread/WARN]: [Essentials] null
[19:29:17] [Server thread/INFO]: Ошибка вызова команды /\ kit: test
java.lang.Exception: §4Этого набора не существует или не определены настройки.
    at com.earth2me.essentials.Kit.expandItems(Kit.java:248) ~[EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.Kit.expandItems(Kit.java:182) ~[EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.commands.Commandkit.giveKits(Commandkit.java:84) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.commands.Commandkit.run(Commandkit.java:34) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:438) [EssentialsX-2.0.1.jar:?]
    at com.earth2me.essentials.Essentials.onCommand(Essentials.java:348) [EssentialsX-2.0.1.jar:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NumberFormatException
    at java.math.BigDecimal.<init>(BigDecimal.java:494) ~[?:1.8.0_72]
    at java.math.BigDecimal.<init>(BigDecimal.java:383) ~[?:1.8.0_72]
    at java.math.BigDecimal.<init>(BigDecimal.java:806) ~[?:1.8.0_72]
    at com.earth2me.essentials.Kit.expandItems(Kit.java:194) ~[EssentialsX-2.0.1.jar:?]
    ... 22 more
```

on line 3: kit doesn't exist or ....

**Comment by vemacs** [comment]
This is a configuration issue. Can you pastebin the configuration for that specific kit?

**Comment by aleshkanet** [comment]
it's not my fault, I'm using createkit comand

```
  test:
    delay: -1
    items:
    - BOW 1
```

**Comment by aleshkanet** [comment]
@vemacs what i doing wrong?
