### ISSUE TITLE
group manager error on load

### ISSUE THREAD

**Issue by saturnux** [EssentialsX/Essentials#461]
on last build (spigot & essentialsx ) on startuo i have : 

`[11:07:16 ERROR]: Could not load 'plugins/EssentialsXGroupManager-2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
    at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-87e2f47-ef13ca4]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
    ... 6 more
`
i'm on java 7

**Comment by whoshenry** [comment]
I get the same thing.

**Comment by Primorior** [comment]
Getting same...

**Comment by shadymac** [comment]
Same here.... Identical..

**Comment by lilacorn** [comment]
I believe i have same problem too. the /pl does not show GroupManager in the list, new folder of groupmanager does not get created in the FTP(after backup downloaded) and no one can do any commands. i have tried /manuadd or whatever group managers commands it will tell you there is no such command or so.
pastebin:
http://pastebin.com/ap1QkWVF
Screenshot of no folder:
https://snapr.pw/i/322e4bd3ca.png

**Comment by lol768** [comment]
@drtshock

```
➜  ~  unzip -l ~/Downloads/EssentialsXGroupManager-2.0.1.jar | grep plugin.yml | wc
      0       0       0
```

**Comment by drtshock** [comment]
rip. must not have included the plugin.yml. will fix.

**Comment by drtshock** [comment]
Fixed https://github.com/drtshock/Essentials/commit/a5686a17e2fb717f01e096903a369cd0b6ea271e
