### ISSUE TITLE
/mail send to offline player doesn't work

### ISSUE THREAD

**Issue by blha303** [EssentialsX/Essentials#464]
Reported by Paint in IRC, confirmed by me. Tested using a random player from another server.

```
[21:30:36 INFO]: blha303 issued server command: /mail send Khearn hi
[21:30:36 INFO]: [Essentials] checking if blha303 has essentials.mail - true
[21:30:36 INFO]: [Essentials] checking if blha303 can afford charge.
[21:30:36 INFO]: [Essentials] calculated command (mail) cost for blha303 as 0
[21:30:36 INFO]: [Essentials] checking if blha303 has essentials.mail.send - true
[21:30:36 INFO]: Error calling the command /mail
com.earth2me.essentials.commands.PlayerNotFoundException: º4Player not found.
        at com.earth2me.essentials.commands.EssentialsCommand.getPlayer(EssentialsCommand.java:139) ~[EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.getPlayer(EssentialsCommand.java:86) ~[EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.Commandmail.run(Commandmail.java:52) ~[EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:438) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:348) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot-1.9.jar:git-Spigot-604e046-69e196f]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
[21:30:36 WARN]: com.earth2me.essentials.commands.PlayerNotFoundException: º4Player not found.
[21:30:36 WARN]:        at com.earth2me.essentials.commands.EssentialsCommand.getPlayer(EssentialsCommand.java:139)
[21:30:36 WARN]:        at com.earth2me.essentials.commands.EssentialsCommand.getPlayer(EssentialsCommand.java:86)
[21:30:36 WARN]:        at com.earth2me.essentials.commands.Commandmail.run(Commandmail.java:52)
[21:30:36 WARN]:        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146)
[21:30:36 WARN]:        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:438)
[21:30:36 WARN]:        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:348)
[21:30:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[21:30:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:30:36 WARN]:        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1302)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1137)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:30:36 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:30:36 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:716)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655)
[21:30:36 WARN]:        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554)
[21:30:36 WARN]:        at java.lang.Thread.run(Unknown Source)
[21:31:13 INFO]: blha303 issued server command: /mail send blha303 test
[21:31:13 INFO]: [Essentials] checking if blha303 has essentials.mail - true
[21:31:13 INFO]: [Essentials] checking if blha303 can afford charge.
[21:31:13 INFO]: [Essentials] calculated command (mail) cost for blha303 as 0
[21:31:13 INFO]: [Essentials] checking if blha303 has essentials.mail.send - true
[21:31:13 INFO]: [Essentials] attempting to charge user blha303
[21:31:13 INFO]: [Essentials] calculated command (mail) cost for blha303 as 0
[21:31:13 INFO]: [Essentials] charge user blha303 completed
```

**Comment by Paintsplatters** [comment]
Whatever some one did. this issue is fixed in build 304. not sure the lowest build its fixed in tho.

**Comment by mdcfe** [comment]
Closing due to inactivity. If this is still a problem, please open a new issue.
