### ISSUE TITLE
EssentialsXDiscord won't load

### ISSUE THREAD

**Issue by ccattell** [EssentialsX/Essentials#4702]
### Type of bug

Error in console

### `/ess dump all` output

 https://essentialsx.net/dump.html?id=0d812d4d803e4e509a74d647f6ed18c8

### Error log (if applicable)

[00:39:59] [Server thread/ERROR]: Could not load 'plugins/EssentialsXDiscord-2.19.3-dev+1-05ce11f.jar' in folder 'plugins' org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?] 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?] 	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:415) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:231) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7] 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3368-Spigot-8965a50-2a2caa7] 	at java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.util.zip.ZipException: zip END header not found 	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?] 	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?] 	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?] 	at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?] 	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?] 	at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?] 	at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?] 	at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?] 	at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?] 	at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?] 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:166) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?] 	... 6 more

### Bug description

EssentialsXDiscord won't load

### Steps to reproduce

load server

### Expected behaviour

EssentialsXDiscord loads

### Actual behaviour

EssentialsXDiscord won't load

**Comment by Chew** [comment]
Corrupted jar, please redownload: https://essentialsx.net/downloads.html
