### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by JetString** [EssentialsX/Essentials#4710]
### Type of bug

Error in console

### `/ess dump all` output

[01:05:10 ERROR]: Could not pass event PlayerAdvancementDoneEvent to EssentialsDiscord v2.19.2 java.lang.NoSuchMethodError: 'net.kyori.adventure.text.serializer.plain.PlainComponentSerializer org.bukkit.UnsafeValues.plainComponentSerializer()'         at net.ess3.provider.providers.PaperAdvancementListenerProvider.onAdvancement(PaperAdvancementListenerProvider.java:17) ~[EssentialsX-2.19.2.jar:?]         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor721.execute(Unknown Source) ~[?:?]         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-99]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]         at net.minecraft.server.PlayerAdvancements.award(PlayerAdvancements.java:297) ~[?:?]         at net.minecraft.advancements.CriterionTrigger$Listener.run(CriterionTrigger.java:35) ~[?:?]         at net.minecraft.advancements.critereon.SimpleCriterionTrigger.trigger(SimpleCriterionTrigger.java:73) ~[?:?]         at net.minecraft.advancements.critereon.InventoryChangeTrigger.lambda$trigger$0(InventoryChangeTrigger.java:55) ~[?:?]         at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(InventoryChangeTrigger.java:51) ~[?:?]         at net.minecraft.server.level.ServerPlayer$2.slotChanged(ServerPlayer.java:308) ~[?:?]         at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:297) ~[?:?]         at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:234) ~[?:?]         at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:633) ~[?:?]         at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1128) ~[?:?]         at net.minecraft.world.level.Level.guardEntityTick(Level.java:970) ~[?:?]         at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:670) ~[?:?]         at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[paper-1.18.1.jar:git-Paper-99]         at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:650) ~[?:?]         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[paper-1.18.1.jar:git-Paper-99]         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-99]         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-99]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-99]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-99]         at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Error log (if applicable)

https://paste.gg/p/anonymous/f7417bfae16149f689c930163f44fd7c

### Bug description

playing in mob arenas will cause the error to pop up

### Steps to reproduce

join a mob arena

### Expected behaviour

there should be no error log

### Actual behaviour

there is an error log

**Comment by JRoy** [comment]
Update Paper.
