### ISSUE TITLE
Error occurs after updating EssentialsX version 2.18 to 2.19.

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4853]
### Type of bug

Error in console

### `/ess dump all` output

.

### Bug description

>> When setting (modifying) the balance of a specific player, the following error is output and then a crash occurs.
[03:28:20] [Server thread/INFO]: ERROR: Cannot invoke "com.earth2me.essentials.User.setMoney(java.math.BigDecimal, net.ess3.api.events.UserBalanceUpdateEvent$Cause)" because "player" is null

>> When connecting to the player or using the /baltop command, the server crashes with a lot of errors like the one below.
[03:20:36] [Craft Scheduler Thread - 52 - Essentials/ERROR]: [Essentials] Error while reading user config: [ignore, 0] of type java.util.List<java.util.UUID>: Failed to coerce input value of type class java.lang.String to UUID
com.earth2me.essentials.libs.configurate.serialize.CoercionFailedException: [ignore, 0] of type java.util.List<java.util.UUID>: Failed to coerce input value of type class java.lang.String to UUID
at com.earth2me.essentials.libs.configurate.serialize.UuidSerializer.deserialize(UuidSerializer.java:52) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.libs.configurate.serialize.UuidSerializer.deserialize(UuidSerializer.java:23) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.libs.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.libs.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:58) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.libs.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.libs.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.libs.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.libs.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.libs.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.UserData.reloadConfig(UserData.java:86) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.UserData.<init>(UserData.java:59) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.User.<init>(User.java:97) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.UserMap.load(UserMap.java:180) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.UserMap.load(UserMap.java:30) ~[EssentialsX-2.19.4.jar:?]
at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[guava-31.0.1-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[guava-31.0.1-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[guava-31.0.1-jre.jar:?]
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[guava-31.0.1-jre.jar:?]
at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[guava-31.0.1-jre.jar:?]
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[guava-31.0.1-jre.jar:?]
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[guava-31.0.1-jre.jar:?]
at com.earth2me.essentials.UserMap.getUser(UserMap.java:129) ~[EssentialsX-2.19.4.jar:?]
at com.earth2me.essentials.BalanceTopImpl.calculateBalanceTopMap(BalanceTopImpl.java:32) ~[EssentialsX-2.19.4.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-247]
at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-247]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-247]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce

.

### Expected behaviour

.

### Actual behaviour

.

**Comment by pop4959** [comment]
If you are still experiencing this problem please create a new issue including all of the information requested in the template, including dump output.
