### ISSUE TITLE
warn: no such method

### ISSUE THREAD

**Issue by HouYanShen** [EssentialsX/Essentials#4967]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=51d6b89e2d4944ddbb6c2fdb45d3872d

### Bug description

spigot1.19
EssentialsX-2.19.4

[03:09:54 WARN]: java.lang.NoSuchMethodException: no such method: net.minecraft.server.MinecraftServer.v()boolean/invokeVirtual
[03:09:54 WARN]: 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
[03:09:54 WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
[03:09:54 WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3647)
[03:09:54 WARN]: 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2673)
[03:09:54 WARN]: 	at net.ess3.nms.refl.providers.ReflServerStateProvider.<init>(ReflServerStateProvider.java:20)
[03:09:54 WARN]: 	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:382)
[03:09:54 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[03:09:54 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[03:09:54 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[03:09:54 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:520)
[03:09:54 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:434)
[03:09:54 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582)
[03:09:54 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401)
[03:09:54 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255)
[03:09:54 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966)
[03:09:54 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291)
[03:09:54 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:09:54 WARN]: Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.server.MinecraftServer.v()'
[03:09:54 WARN]: 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[03:09:54 WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
[03:09:54 WARN]: 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
[03:09:54 WARN]: 	... 15 more
[03:09:54 INFO]: Loaded 36926 items from items.json.

### Steps to reproduce

Start server

### Expected behaviour

No error report

### Actual behaviour

error

**Comment by JRoy** [comment]
Update to the latest dev build
