### ISSUE TITLE
Problem with command

### ISSUE THREAD

**Issue by rayzens1** [EssentialsX/Essentials#4977]
### Type of bug

Error in console

### `/ess dump all` output

[14:15:43 WARN]: Unexpected exception while parsing console command "ess dump all" org.bukkit.command.CommandException: Unhandled exception executing command 'ess' in plugin Essentials v2.19.5-dev+24-a60f3c0 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[SimpleCommandMap.class:?] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:738) [CraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:504) [nz.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462) [nz.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332] Caused by: java.lang.NullPointerException at com.earth2me.essentials.Essentials.onCommand(Essentials.java:713) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?] ... 8 more

### Bug description

When i do one of essential command like "/back" "/gmc" etc...

i have :

[14:12:55 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fly' in plugin Essentials v2.19.5-dev+24-a60f3c0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[SimpleCommandMap.class:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1590) ~[pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1429) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_332]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_332]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: java.lang.NullPointerException
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:713) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
... 15 more

### Steps to reproduce

By executing a command

### Expected behaviour

Work

### Actual behaviour

Every command do an internal error and do an error in the console

Like "/back" "/gmc"

error:

[14:12:55 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'fly' in plugin Essentials v2.19.5-dev+24-a60f3c0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[PluginCommand.class:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[SimpleCommandMap.class:?]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[CraftServer.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1590) ~[pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1429) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:46) ~[la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(CPacketChatMessage.java:9) ~[la.class:?]
at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_332]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_332]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: java.lang.NullPointerException
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:713) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:43) ~[PluginCommand.class:?]
... 15 more

**Comment by mdcfe** [comment]
Please paste your `latest.log` file on https://gist.github.com and then post the link here.
