### ISSUE TITLE
 java.lang.NoSuchFieldError: ENTITY_ENDERMAN_TELEPORT

### ISSUE THREAD

**Issue by servicomcr** [EssentialsX/Essentials#5005]
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=abe0b2235cdf4d4cbce4946ca627c7da

### Error log (if applicable)

https://pastebin.com/Xx5RDpWx

### Bug description

[23:51:32] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Jhimizx issued server command: /home

[23:51:39] [Server thread/WARN] [me.downthepark.sethome.SetHome]: [SetHome] Task #57426 for SetHome v5.1.2 generated an exception
 java.lang.NoSuchFieldError: ENTITY_ENDERMAN_TELEPORT
        at me.downthepark.sethome.SetHome.sendPlayerHome(SetHome.java:127) ~[?:?]
        at me.downthepark.sethome.SetHome.lambda$onCommand$0(SetHome.java:77) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:65) ~[CraftTask.class:1.12.2-9a3e486d]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:429) [CraftScheduler.class:1.12.2-9a3e486d]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:853) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:673) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[23:51:39] [Server thread/ERROR] [global]: TIMING_STACK_CORRUPTION - Report this to the plugin SetHome(Look for errors above this in the logs) (TimingIdentifier{id=SetHome:Task: me.downthepark.sethome.SetHome$$Lambda$4097/1495232334 (Single)} did not stopTiming)
 java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:113) [TimingHandler.class:1.12.2-9a3e486d]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:801) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:673) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

### Steps to reproduce

[23:51:32] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: Jhimizx issued server command: /home

[00:16:43] [Server thread/INFO] [Minecraft]: CONSOLE issued server command: /ess dump all
[00:16:43] [Server thread/INFO] []: Creating server dump...
[00:16:43] [pool-20-thread-1/INFO] []: Created server dump: https://essentialsx.net/dump.html?id=abe0b2235cdf4d4cbce4946ca627c7da
[00:16:43] [pool-20-thread-1/INFO] []: If you want to delete this dump at a later date, use the following deletion key: 275e2196-ccd4-4450-92c9-d64dbd075127

### Expected behaviour

Esta pasando cuando el usuario el /home y no tiene el permiso 

This when the user stops /home and does not have the permission

### Actual behaviour

Esta pasando cuando el usuario el /home y no tiene el permiso 

This when the user stops /home and does not have the permission

**Comment by pop4959** [comment]
That error is not from Essentials and you are running an unsupported server software.
