### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rejomy** [EssentialsX/Essentials#5218]
### Type of bug

Error in console

### `/ess dump all` output

no

### Error log (if applicable)

2

### Bug description

[09:35:38 ERROR]: Could not pass event PlayerDeathEvent to Essentials v2.20.0-dev+38-b323860
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at me.rejomy.container.handlers.EntityDamageEvent.onDamage(EntityDamageEvent.java:63) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:539) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1118) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:862) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:750) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:803) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityLiving.e(EntityLiving.java:955) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityHuman.e(EntityHuman.java:1459) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.Block.fallOn(Block.java:650) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.Entity.a(Entity.java:849) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityLiving.a(EntityLiving.java:167) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:638) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:459) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:8) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_301]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_301]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:741) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:680) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:583) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractList.remove(AbstractList.java:161) ~[?:1.8.0_301]
        at java.util.AbstractList$Itr.remove(AbstractList.java:374) ~[?:1.8.0_301]
        at java.util.AbstractList.removeRange(AbstractList.java:571) ~[?:1.8.0_301]
        at java.util.AbstractList.clear(AbstractList.java:234) ~[?:1.8.0_301]
        at com.earth2me.essentials.EssentialsEntityListener.onPlayerDeathInvEvent(EssentialsEntityListener.java:195) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor432.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        ... 40 more

### Steps to reproduce

2

### Expected behaviour

2

### Actual behaviour

2

**Comment by pop4959** [comment]
You didn't fill out the issue template. Also it looks like this error is caused by plugin `me.rejomy.container` according to your stack trace. It's calling an event incorrectly. You'll want to report this to them instead.
