### ISSUE TITLE
EssentialsX crashing my server

### ISSUE THREAD

**Issue by nightmarefoxy9000** [EssentialsX/Essentials#5471]
### Type of bug

Error in console

### `/ess dump all` output

can even start server now

### Error log (if applicable)

https://paste.gg

### Bug description

This is the log I get when I Start the papermc but I got the log's in ssh

> 2023-08-07 02:09:08,822 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:804)
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:902)
        at org.bukkit.craftbukkit.v1_19_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28)

2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
        at net.minecraft.server.dedicated.DedicatedServer.t(Dedi2023-08-07 02:09:08,824 Server thread WARN org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging StatusMessage: org.apache.logging.log4j.spi.AbstractLogger caught java.lang.ThreadDeath logging SimpleMessage: An exception occurred processing Appender Async java.lang.ThreadDeath
        at java.base/java.lang.Thread.stop(Thread.java:942)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:930)
[02:09:08 ERROR]: Error occurred (in the plugin loader) while enabling Essentials v2.20.1 (Is it up to date?)
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Thread.java:942) ~[?:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:930) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:804) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:902) ~[paper-1.19.4.jar:git-Paper-510]
        at org.bukkit.craftbukkit.v1_19_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[paper-1.19.4.jar:git-Paper-510]
[02:09:08 ERROR]: Main thread terminated by WatchDog due to hard crash
java.lang.ThreadDeath: null
        at java.lang.Thread.stop(Thread.java:942) ~[?:?]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:930) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:804) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:902) ~[paper-1.19.4.jar:git-Paper-510]
        at org.bukkit.craftbukkit.v1_19_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[paper-1.19.4.jar:git-Paper-510]
[02:09:08 INFO]: Stopping server
[02:09:08 INFO]: [Essentials] Disabling Essentials v2.20.1
[02:09:08 ERROR]: Error occurred (in the plugin loader) while disabling Essentials v2.20.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.ess3.provider.ServerStateProvider.isStopping()" because the return value of "com.earth2me.essentials.Essentials.getServerStateProvider()" is null
        at com.earth2me.essentials.Essentials.onDisable(Essentials.java:561) ~[EssentialsX-2.20.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[paper-1.19.4.jar:git-Paper-510]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:151) ~[paper-1.19.4.jar:git-Paper-510]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.19.4.jar:git-Paper-510]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.disablePlugins(CraftServer.java:486) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:947) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:804) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:902) ~[paper-1.19.4.jar:git-Paper-510]
        at org.bukkit.craftbukkit.v1_19_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[paper-1.19.4.jar:git-Paper-510]
[02:09:08 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.11.3
[02:09:08 INFO]: [ProtocolLib] Disabling ProtocolLib v5.1.0
[02:09:08 INFO]: [floodgate] Disabling floodgate v2.2.2-SNAPSHOT (b59-2278589)
[02:09:08 INFO]: [Vault] Disabling Vault v1.7.3-b131
[02:09:09 INFO]: [LuckPerms] Disabling LuckPerms v5.4.40
[02:09:09 INFO]: [LuckPerms] Starting shutdown process...
[02:09:09 INFO]: [LuckPerms] Closing storage...
[02:09:09 INFO]: [LuckPerms] Goodbye!
[02:09:09 INFO]: Saving players
[02:09:09 WARN]: Asynchronous Save Players! Blocking thread until it returns 
java.lang.IllegalStateException: null
        at io.papermc.paper.util.MCUtil.ensureMain(MCUtil.java:362) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:1201) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.players.PlayerList.saveAll(PlayerList.java:1197) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:958) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:804) ~[paper-1.19.4.jar:git-Paper-510]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:902) ~[paper-1.19.4.jar:git-Paper-510]
        at org.bukkit.craftbukkit.v1_19_R3.util.ServerShutdownThread.run(ServerShutdownThread.java:28) ~[paper-1.19.4.jar:git-Paper-510]
[02:11:19 WARN]: [PlaceholderAPI] Failed to download expansion information
java.net.ConnectException: Connection timed out
        at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
        at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at java.net.Socket.connect(Socket.java:583) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:532) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:637) ~[?:?]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:280) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:385) ~[?:?]
        at sun.net.www.http.HttpClient.New(HttpClient.java:407) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at java.net.URL.openStream(URL.java:1161) ~[?:?]
        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:68) ~[guava-31.1-jre.jar:?]
        at com.google.common.io.ByteSource.read(ByteSource.java:296) ~[guava-31.1-jre.jar:?]
        at com.google.common.io.ByteSource$AsCharSource.read(ByteSource.java:486) ~[guava-31.1-jre.jar:?]
        at com.google.common.io.Resources.toString(Resources.java:107) ~[guava-31.1-jre.jar:?]
        at me.clip.placeholderapi.expansion.manager.CloudExpansionManager.lambda$fetch$4(CloudExpansionManager.java:182) ~[PlaceholderAPI-2.11.3.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce

All I did was put the plugin in the plugin folder

### Expected behaviour

Should just start

### Actual behaviour

When I start it all it does is crash

**Comment by nightmarefoxy9000** [comment]
This is a new server All I did was add plugin's in it and it crash's now

**Comment by nightmarefoxy9000** [comment]
I gave the log's to chatGPT and it told me that EssentialsX cuz a crash

**Comment by mbax** [comment]
Share the full log on paste.gg, and don't trust ChatGPT because it's not really ready yet for that sort of thing.

**Comment by nightmarefoxy9000** [comment]
no not that It is 4.0 and I cant get anthing but that log It is all it give's me before crashing ubuntu I dont know what to do

**Comment by mbax** [comment]
If Ubuntu itself is crashing, this sounds like a much bigger issue than EssentialsX. If you truly cannot open up the log file and copy/paste the log file contents because the entire operating system crashes, you need to sort out that Ubuntu install first.

**Comment by nightmarefoxy9000** [comment]
I am kind of new to doing this how would I do that

**Comment by mbax** [comment]
This is EssentialsX help, not Ubuntu help. Good luck! 🙂

**Comment by nightmarefoxy9000** [comment]
No I dont know what is going on plz help

**Comment by mbax** [comment]
We can't investigate a potential crash bug if we don't have the log. Get that, then share it here. *Potentially* someone could help on our Discord with getting that file, but this github issue is not a place for Ubuntu support.

**Comment by nightmarefoxy9000** [comment]
I just looked in the crash folder where it is supposed to be and it is empty

**Comment by mbax** [comment]
I'm looking for the full file `logs/latest.log` not a crash log

**Comment by nightmarefoxy9000** [comment]
![image](https://github.com/EssentialsX/Essentials/assets/53234219/35928fbd-8c1d-450b-8354-84836f769edc)
These are all I see

**Comment by nightmarefoxy9000** [comment]
Ok I Got it and I read thru it where It shows's power button I am not sure how that is There is no power button on the server I use a screw driver
[syslog.txt](https://github.com/EssentialsX/Essentials/files/12271790/syslog.txt)

**Comment by MindStudioOfficial** [comment]
> I'm looking for the full file `logs/latest.log` not a crash log

they mean that you should provide the log file of the minecraft server located in your minecraft servers directory.

e.g.: `<pathtoyourmcserver>/logs/latest.log`

not any system log
