### ISSUE TITLE
Essentials Spawn loading issue after server restart

### ISSUE THREAD

**Issue by pjindras** [EssentialsX/Essentials#5568]
### Type of bug

Compatibility issue, Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=1ef15ececbc54aaa9754a90ec7716cc8

### Error log (if applicable)

https://pastebin.com/f92a8PC1

### Bug description

https://pastebin.com/f92a8PC1

Essentials loads succesfully, but essentials spawn isnt loaded, I tryed to change version to lastest dev buld, but the problem is the same. Using purpur 1.20.1

### Steps to reproduce

Download essentials with ess spawn and restart server

### Expected behaviour

plugin load

### Actual behaviour

error and plugin wasnt loaded

**Comment by LaxWasHere** [comment]
We need the output of the `/ess dump all`, thanks!

**Comment by pjindras** [comment]
Hello, ok, https://essentialsx.net/dump.html?id=607d0a6f70154e3e81c27503cec6ee51

**Comment by LaxWasHere** [comment]
Your dump shows EssentialsX Spawn is working just fine. If it happens again, please provide another full dump.

**Comment by pjindras** [comment]
@LaxWasHere it works, but after I loaded the plugin manually using Plugman. Every time, when I restart my server, the plugin cannot load and throws error https://pastebin.com/f92a8PC1

Than, I have to use plugman to load the plugin manually.

I dont know, what can cause the issue, but the version is the same and I think, the issue cannot by on my side, there is nothing wrong configured or installed.

Please check it.

Thank you.

**Comment by pjindras** [comment]
This is the error, 
`[10:21:22] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'EssentialsXSpawn-2.21.0-dev+19-3eceec8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: net/ess3/provider/LoggerProvider
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:127) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:524) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/ess3/provider/LoggerProvider
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.1.jar:git-Purpur-2062]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.ess3.provider.LoggerProvider
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Unknown Source) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:123) ~[purpur-1.20.1.jar:git-Purpur-2062]
	... 9 more`

I have to load it every time, because I have lot of players online and they need spawn.

**Comment by LaxWasHere** [comment]
We need a full dump after the restart where the error occurs and if possible, on paper.

**Comment by pjindras** [comment]
> We need a full dump after the restart where the error occurs and if possible, on paper.

https://essentialsx.net/dump.html?id=af75f212b3b545c9a370d8d2ccc72446

There it is, i cann refer on it in new issue, when this is already closed.
