### ISSUE TITLE
Plugin Essentials v2.20.1 generated an exception while executing task 39

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#5646]
### Type of bug

Error in console

### `/ess dump all` output

.

### Bug description

[Essentials] Plugin Essentials v2.20.1 generated an exception while executing task 39
java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
        at java.util.ArrayList.addAll(ArrayList.java:670) ~[?:?]
        at com.earth2me.essentials.perm.PermissionsHandler.getGroups(PermissionsHandler.java:54) ~[EssentialsX-2.20.1.jar:?]
        at net.essentialsx.discordlink.rolesync.RoleSyncManager.sync(RoleSyncManager.java:62) ~[EssentialsXDiscordLink-2.20.1.jar:?]
        at net.essentialsx.discordlink.rolesync.RoleSyncManager.lambda$new$0(RoleSyncManager.java:45) ~[EssentialsXDiscordLink-2.20.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-405]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-405]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
[22:28:38 WARN]: [Essentials] Plugin Essentials v2.20.1 generated an exception while executing task 39
java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
        at java.util.ArrayList.addAll(ArrayList.java:670) ~[?:?]

### Steps to reproduce

.

### Expected behaviour

.

### Actual behaviour

.

**Comment by LaxWasHere** [comment]
Please properly fill the form and provide a full dump.

**Comment by wbrous** [comment]
I got the same error but for when I tried to link my discord account.
