### ISSUE TITLE
This error occurred when I was using EssentialsX-2.21.0-dev+68-993d7ed, causing my server to not function properly. 

### ISSUE THREAD

**Issue by ChemChemcPanda** [EssentialsX/Essentials#5724]
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

[05:51:41 WARN]: [com.fastasyncworldedit.core.util.UpdateNotification] An update for FastAsyncWorldEdit is available. You are 22 build(s) out of date. You are running build 646, the latest version is build 668. Update at https://www.spigotmc.org/resources/13932/ [05:51:41 ERROR]: An unexpected error occurred while starting the plugin. Please check the console for more details. net.skinsrestorer.shadow.configme.exception.ConfigMeException: YAML error while trying to load file 'plugins/SkinsRestorer/config.yml'         at net.skinsrestorer.shadow.configme.resource.YamlFileReader.loadFile(YamlFileReader.java:193) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.configme.resource.YamlFileReader.<init>(YamlFileReader.java:63) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.configme.resource.YamlFileResource.createReader(YamlFileResource.java:57) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.configme.SettingsManagerImpl.loadFromResourceAndValidate(SettingsManagerImpl.java:88) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.configme.SettingsManagerImpl.<init>(SettingsManagerImpl.java:46) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.configme.SettingsManagerBuilder.create(SettingsManagerBuilder.java:138) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shared.plugin.SRPlugin.loadConfig(SRPlugin.java:208) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shared.plugin.SRPlugin.startup(SRPlugin.java:373) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shared.plugin.SRBootstrapper.startPlugin(SRBootstrapper.java:61) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.bukkit.SRBukkitBootstrap.onEnable(SRBukkitBootstrap.java:43) ~[SkinsRestorer.jar:?]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at java.lang.Thread.run(Thread.java:840) ~[?:?] Caused by: net.skinsrestorer.shadow.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:6hFbcAoCMfLj8Dl.RIuD20; exception=Class not found: 6hFbcAoCMfLj8Dl.RIuD20  in 'reader', line 55, column 15:         password: !!6hFbcAoCMfLj8Dl.RIuD20                   ^         at net.skinsrestorer.shadow.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:364) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:581) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:213) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:557) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:600) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:581) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:213) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:557) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:600) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:207) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:191) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.Yaml.loadFromReader(Yaml.java:477) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.Yaml.load(Yaml.java:430) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.configme.resource.YamlFileReader.loadFile(YamlFileReader.java:186) ~[SkinsRestorer.jar:?]         ... 19 more Caused by: net.skinsrestorer.shadow.snakeyaml.error.YAMLException: Class not found: 6hFbcAoCMfLj8Dl.RIuD20         at net.skinsrestorer.shadow.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:685) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:349) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:358) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:581) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:213) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:557) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:600) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:581) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:213) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:557) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:600) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:207) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:191) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.Yaml.loadFromReader(Yaml.java:477) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.snakeyaml.Yaml.load(Yaml.java:430) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.configme.resource.YamlFileReader.loadFile(YamlFileReader.java:186) ~[SkinsRestorer.jar:?]         ... 19 more [05:51:41 WARN]: Updater was not initialized, a error occurred while starting the plugin. Forcing updater to initialize. [05:51:41 ERROR]: An unexpected error occurred while initializing the updater. Please check the console for more details. net.skinsrestorer.shadow.injector.exceptions.InjectorException: Did not find instantiation method for 'interface net.skinsrestorer.shadow.configme.SettingsManager'. This class cannot be instantiated; please check the class or your handlers.         at net.skinsrestorer.shadow.injector.InjectorImpl.findResolutionOrFail(InjectorImpl.java:243) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.resolveContext(InjectorImpl.java:153) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.resolveContext(InjectorImpl.java:158) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.resolveContext(InjectorImpl.java:158) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.resolveDependencies(InjectorImpl.java:186) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.resolveContext(InjectorImpl.java:158) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.resolve(InjectorImpl.java:133) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shadow.injector.InjectorImpl.getSingleton(InjectorImpl.java:72) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shared.plugin.SRPlugin.initUpdateCheck(SRPlugin.java:328) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.shared.plugin.SRBootstrapper.startPlugin(SRBootstrapper.java:73) ~[SkinsRestorer.jar:?]         at net.skinsrestorer.bukkit.SRBukkitBootstrap.onEnable(SRBukkitBootstrap.java:43) ~[SkinsRestorer.jar:?]         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:276) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-44]         at java.lang.Thread.run(Thread.java:840) ~[?:?]

### Error log (if applicable)

https://paste.gg/p/anonymous/fe1de46c78034ab08f70d64f62439f42

### Bug description

I'm not sure I just updated the plugin version and that was it.

### Steps to reproduce

Shut down the server -> Change plug-in version -> Start the server

### Expected behaviour

working normally

### Actual behaviour

e

**Comment by Evidentsinger14** [comment]
This isn’t an EssentialsX error.
