### ISSUE TITLE
Essentials doesn't enable on 1.20.5

### ISSUE THREAD

**Issue by Budderman18** [EssentialsX/Essentials#5779]
### Type of bug

Compatibility issue

### `/ess dump all` output

obviously cant do this when the plugin doesnt enable

### Error log (if applicable)

https://paste.gg/p/anonymous/db7ba7252f5641728c4650195b54765c

### Bug description

Plugin fails to startup. For some reason it also thinks /reload is being done and not a normal startup, not sure if thats an underlining cause.

### Steps to reproduce

1. start server on paper 1.20.5 with essentials
2. plugin disables when trying to enable

### Expected behaviour

plugin enables like normal

### Actual behaviour

do you really need this section when "bug description" should be describing this?

### Additional Information

the error it fails to start on so the log doesnt have to be viewed:
[Essentials] Enabling Essentials v2.21.0-dev+80-549283a
[00:04:40] [Server thread/WARN]: [Essentials] Beginning Adventure locale file conversion.
[00:04:40] [Server thread/ERROR]: [Essentials] You are running an unsupported server version!
[00:04:40] [Server thread/WARN]: [Essentials] Version mismatch! Please update EssentialsWarpGUI to the same version.
[00:04:40] [Server thread/TRACE]: [Essentials] Skipping item spawn blacklist read; item DB not yet loaded.
[00:04:41] [Server thread/INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[00:04:41] [Server thread/INFO]: [Essentials] No kits found to migrate.
[00:04:41] [Server thread/TRACE]: [Essentials] Skipping item spawn blacklist read; item DB not yet loaded.
[00:04:41] [Server thread/ERROR]: [Essentials] There's a good chance you're reloading your server right now. If that's the case, why do you hate yourself? Expect no support from the EssentialsX team when using /reload.
[00:04:41] [Server thread/ERROR]: Error occurred while enabling Essentials v2.21.0-dev+80-549283a (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.earth2me.essentials.Backup.setPendingShutdown(boolean)" because the return value of "com.earth2me.essentials.Essentials.getBackup()" is null
	at EssentialsX-2.21.0-dev+80-549283a.jar/com.earth2me.essentials.Essentials.onDisable(Essentials.java:604) ~[EssentialsX-2.21.0-dev+80-549283a.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
	at EssentialsX-2.21.0-dev+80-549283a.jar/com.earth2me.essentials.Essentials.handleCrash(Essentials.java:1136) ~[EssentialsX-2.21.0-dev+80-549283a.jar:?]
	at EssentialsX-2.21.0-dev+80-549283a.jar/com.earth2me.essentials.Essentials.onEnable(Essentials.java:534) ~[EssentialsX-2.21.0-dev+80-549283a.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.5.jar:git-Paper-21]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.5.jar:git-Paper-21]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.5.jar:git-Paper-21]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.5.jar:git-Paper-21]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.5.jar:git-Paper-21]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.5.jar:git-Paper-21]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.5.jar:git-Paper-21]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.5.jar:git-Paper-21]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.5.jar:git-Paper-21]

**Comment by JRoy** [comment]
This is known, work is bring done on the MC/1.20.5 branch for this update.
