### ISSUE TITLE
This plugin doesn't work in Spigot 1.20.6

### ISSUE THREAD

**Issue by kbcrtc** [EssentialsX/Essentials#5789]
### Type of bug

Error in console

### `/ess dump all` output

Some errors appears, and it outputs nothing.

### Bug description

I tried to run the plugin in Spigot 1.20.6, but an error occurred and it doesn’t work at all.

### Steps to reproduce

Run the plugin in Spigot 1.20.6 and Paper 1.20.6.

### Expected behaviour

This plugin starts normally.

### Actual behaviour

The plugin is closed and cannot function properly, with some errors occurring.

### Additional Information

[10:55:15] [Server thread/INFO]: [Essentials] Enabling Essentials v2.21.0-dev+81-cde7184
[10:55:15] [Server thread/ERROR]: You are running an unsupported server version!
[10:55:16] [Server thread/INFO]: Attempting to convert old kits in config.yml to new kits.yml
[10:55:16] [Server thread/INFO]: No kits found to migrate.
[10:55:16] [Server thread/WARN]: java.lang.NoSuchMethodException: no such method: net.minecraft.server.MinecraftServer.v()boolean/invokeVirtual
[10:55:16] [Server thread/WARN]:        at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:915)
[10:55:16] [Server thread/WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
[10:55:16] [Server thread/WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3750)
[10:55:16] [Server thread/WARN]:        at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2767)
[10:55:16] [Server thread/WARN]:        at net.ess3.nms.refl.providers.ReflServerStateProvider.<init>(ReflServerStateProvider.java:32)
[10:55:16] [Server thread/WARN]:        at com.earth2me.essentials.Essentials.onEnable(Essentials.java:419)
[10:55:16] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[10:55:16] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[10:55:16] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491)
[10:55:16] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:541)
[10:55:16] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:455)
[10:55:16] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634)
[10:55:16] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419)
[10:55:16] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265)
[10:55:16] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010)
[10:55:16] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311)
[10:55:16] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[10:55:16] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: 'boolean net.minecraft.server.MinecraftServer.v()'
[10:55:16] [Server thread/WARN]:        at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
[10:55:16] [Server thread/WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
[10:55:16] [Server thread/WARN]:        at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
[10:55:16] [Server thread/WARN]:        ... 15 more
[10:55:16] [Server thread/ERROR]: java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?]
        at java.base/java.lang.Class.getConstructor0(Class.java:3754) ~[?:?]
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]
        at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:212) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:120) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1226) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
        at com.earth2me.essentials.items.FlatItemDb.loadJSON(FlatItemDb.java:85) ~[?:?]
        at com.earth2me.essentials.items.FlatItemDb.rebuild(FlatItemDb.java:64) ~[?:?]
        at com.earth2me.essentials.items.FlatItemDb.reloadConfig(FlatItemDb.java:53) ~[?:?]
        at com.earth2me.essentials.Essentials.reload(Essentials.java:651) ~[?:?]
        at com.earth2me.essentials.Essentials.onEnable(Essentials.java:496) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:160) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 27 more
[10:55:16] [Server thread/ERROR]: There's a good chance you're reloading your server right now. If that's the case, why do you hate yourself? Expect no support from the EssentialsX team when using /reload.
[10:55:16] [Server thread/ERROR]: Error occurred while enabling Essentials v2.21.0-dev+81-cde7184 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.earth2me.essentials.Backup.setPendingShutdown(boolean)" because the return value of "com.earth2me.essentials.Essentials.getBackup()" is null
        at com.earth2me.essentials.Essentials.onDisable(Essentials.java:604) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:268) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at com.earth2me.essentials.Essentials.handleCrash(Essentials.java:1136) ~[?:?]
        at com.earth2me.essentials.Essentials.onEnable(Essentials.java:534) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:491) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugin(CraftServer.java:541) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.enablePlugins(CraftServer.java:455) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:634) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:265) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4141-Spigot-e2c1eee-66fd943]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by Evidentsinger14** [comment]
1.20.5/6 is not supported on current builds. Work is being done to get an update out as soon as possible.
