### ISSUE TITLE
Severe error report

### ISSUE THREAD

**Issue by OzzyPyro** [EssentialsX/Essentials#585]
This was generated tonight 
`2016-04-21 09-37
=============================== GM ERROR LOG ===============================
= ERROR REPORT START - Pre2.14.1.3 FINAL (Phoenix) =

java.lang.NullPointerException
    at org.anjocaido.groupmanager.GroupManager.onEnable(GroupManager.java:211)
    at org.anjocaido.groupmanager.GroupManager.onCommand(GroupManager.java:1827)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645)
    at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350)
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185)
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
    at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721)
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
    at java.lang.Thread.run(Thread.java:745)
# 

`

**Comment by drtshock** [comment]
Groupmanager isn't supported.
