### ISSUE TITLE
`tpahere` throws an index out of range exception.

### ISSUE THREAD

**Issue by OoLunar** [EssentialsX/Essentials#5982]
### Type of bug

Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=1181fbec6376412a98e1e0a5617f0ef6

### Bug description

When running `/tpahere`, the command responds with `Error: Index -1 out of bounds for length 0`. 

### Steps to reproduce

Run `/tpahere` against a nicknamed player.

### Expected behaviour

The player receives the TPA request and accepts it.

### Actual behaviour

```
[02:12:28 WARN]: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
[02:12:28 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
[02:12:28 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
[02:12:28 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
[02:12:28 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:385)
[02:12:28 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[02:12:28 WARN]:        at EssentialsX-2.21.0-dev+144-d31ff55.jar//com.earth2me.essentials.User.requestTeleport(User.java:371)
[02:12:28 WARN]:        at EssentialsX-2.21.0-dev+144-d31ff55.jar//com.earth2me.essentials.commands.Commandtpahere.run(Commandtpahere.java:47)
[02:12:28 WARN]:        at EssentialsX-2.21.0-dev+144-d31ff55.jar//com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:170)
[02:12:28 WARN]:        at EssentialsX-2.21.0-dev+144-d31ff55.jar//com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:896)
[02:12:28 WARN]:        at EssentialsX-2.21.0-dev+144-d31ff55.jar//com.earth2me.essentials.Essentials.onCommand(Essentials.java:795)
[02:12:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[02:12:28 WARN]:        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91)
[02:12:28 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[02:12:28 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31)
[02:12:28 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[02:12:28 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[02:12:28 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[02:12:28 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103)
[02:12:28 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443)
[02:12:28 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:350)
[02:12:28 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:337)
[02:12:28 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:332)
[02:12:28 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2219)
[02:12:28 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2193)
[02:12:28 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:12:28 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[02:12:28 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[02:12:28 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1542)
[02:12:28 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[02:12:28 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[02:12:28 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1519)
[02:12:28 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1512)
[02:12:28 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[02:12:28 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1471)
[02:12:28 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1593)
[02:12:28 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303)
[02:12:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[02:12:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by JRoy** [comment]
Please change `tpa-max-requests` to a non-zero value in your config.
