### ISSUE TITLE
Error when using /warp

### ISSUE THREAD

**Issue by FabioZumbi12** [EssentialsX/Essentials#647]
This is the error when using /warp (with debug on)

`[13:11:54 INFO]: Erro ao usar o comando /warp
java.lang.Exception: §4Voce nao tem permissao para usar esse warp.        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:109) ~[EssentialsX-2.0.1.jar:?]        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:46) ~[EssentialsX-2.0.1.jar:?]        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) ~[EssentialsX-2.0.1.jar:?]        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:467) [EssentialsX-2.0.1.jar:?]        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:377) [EssentialsX-2.0.1.jar:?]        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [patched_1.9.4.jar:git-Paper-756]        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) [patched_1.9.4.jar:git-Paper-756]        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:665) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1387) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1192) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-756]        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-756]        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-756]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

Is this only on debug or is a error?

**Comment by vemacs** [comment]
Not an error. Essentials passes permission fails through exceptions.
