### ISSUE TITLE
Error when someone joins

### ISSUE THREAD

**Issue by Yupie** [EssentialsX/Essentials#702]
I get this error whenever someone joins:

`[14:37:10] [Craft Scheduler Thread - 3968/WARN]: Exception in thread "Craft Scheduler Thread - 3968" 
[14:37:10] [Craft Scheduler Thread - 3968/WARN]: org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b354 generated an exception while executing task 75140
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.isSpawnOnJoin()Z
    at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75)
    at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:66)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
`

**Comment by SupaHam** [comment]
Please update EssentialsX. If you ever update other EssentialsX plugins you must always ensure EssentialsX is up to date.
