### ISSUE TITLE
BlockMultiPlaceEvent Error

### ISSUE THREAD

**Issue by Gladorme** [EssentialsX/Essentials#708]
`[10:57:18] [Server thread/ERROR]: Could not pass event BlockMultiPlaceEvent to Essentials v2.0.1-b361
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[openmod.jar:${spigot.desc}null]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[openmod.jar:${spigot.desc}null]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [openmod.jar:${spigot.desc}null]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [openmod.jar:${spigot.desc}null]
    at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callBlockMultiPlaceEvent(CraftEventFactory.java:119) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.ItemStack.placeItem(ItemStack.java:163) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:522) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:888) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:55) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.PacketPlayInUseItem.a(SourceFile:11) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [openmod.jar:${spigot.desc}null]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [openmod.jar:${spigot.desc}null]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [openmod.jar:${spigot.desc}null]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
    at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:124) ~[openmod.jar:${spigot.desc}null]
    at com.earth2me.essentials.utils.LocationUtil.convertBlockToItem(LocationUtil.java:88) ~[?:?]
    at com.earth2me.essentials.EssentialsBlockListener.onBlockPlace(EssentialsBlockListener.java:30) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[openmod.jar:${spigot.desc}null]
    ... 18 more`

**Comment by Gladorme** [comment]
[Pastebin](http://sanglad.fr/pastebin/?5e713f794ae4044d#EPSzSu+y9hNs6gv/bqQeC9P7uwl7Ks/f/4idMFhxObk=)

**Comment by SupaHam** [comment]
This is a problem with the server software which is known as openmod. Please resolve this issue with them first.

**Comment by Gladorme** [comment]
Hi @SupaHam it's called openmod, but this is spigot 1.9, we had just renamed it :)

**Comment by SupaHam** [comment]
What is happening exactly when this error occurs? Details please.

**Comment by drtshock** [comment]
Like Supaham initially said, this is a problem with openmond, not essentialsx.
