### ISSUE TITLE
Error when a player join.

### ISSUE THREAD

**Issue by danielgarciagarcia** [EssentialsX/Essentials#723]
When a player join the server, it appear this error.

```
[14:06:50 WARN]: Exception in thread "Craft Scheduler Thread - 22"
[14:06:50 WARN]: org.apache.commons.lang.UnhandledException: Plugin Essentials v2.0.1-b354 generated an exception while executing task 77
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.isSpawnOnJoin()Z
        at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener.delayedJoin(EssentialsSpawnPlayerListener.java:75)
        at com.earth2me.essentials.spawn.EssentialsSpawnPlayerListener$1.run(EssentialsSpawnPlayerListener.java:66)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by Kakifrucht** [comment]
Ensure that both EssentialsX and EssentialsXSpawn are up to date.

**Comment by danielgarciagarcia** [comment]
I've reinstall all the EssentialsX kit and now it seems to work properly. Thank you.
