### ISSUE TITLE
Installation Issues (java.util.zip.ZipException: zip file is empty)

### ISSUE THREAD

**Issue by benjamin-antupit** [EssentialsX/Essentials#924]
Hello people at EssentialsX!
I was trying to install EssentialsX, Protect, Spawn, Chat and AntiBuild on my Minecraft 10.2 server, but after I add the files to `/plugins/`,  the plugins do not create directories or config files, they just spit errors into the console log (below). Once the server starts and I run `/plugins` from in game, EssentialsX and the other parts do not show up in the list. I would be happy to try any solutions you might have and provide additional info. 

Console Log: 
`[10:36:32] [Server thread/INFO]: Starting minecraft server version 1.10.2
[10:36:32] [Server thread/INFO]: Loading properties
[10:36:32] [Server thread/INFO]: Default game type: SURVIVAL
[10:36:32] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-455072c-43ab266 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[10:36:32] [Server thread/INFO]: Debug logging is disabled
[10:36:32] [Server thread/INFO]: Server Ping Player Sample Count: 12
[10:36:32] [Server thread/INFO]: Using 4 threads for Netty based IO
[10:36:32] [Server thread/INFO]: Generating keypair
[10:36:32] [Server thread/INFO]: Starting Minecraft server on 104.128.52.106:25565
[10:36:32] [Server thread/INFO]: Using epoll channel type
[10:36:32] [Server thread/WARN]: Plugin `Ram_Monitor v1' uses the space-character (0x20) in its name `Ram Monitor' - this is discouraged
[10:36:32] [Server thread/ERROR]: Could not load 'plugins/EssentialsX.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-455072c-43ab266]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-455072c-43ab266]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-455072c-43ab266]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.util.zip.ZipException: zip file is empty
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_66]
at java.util.zip.ZipFile.(ZipFile.java:219) ~[?:1.8.0_66]
at java.util.zip.ZipFile.(ZipFile.java:149) ~[?:1.8.0_66]
at java.util.jar.JarFile.(JarFile.java:166) ~[?:1.8.0_66]
at java.util.jar.JarFile.(JarFile.java:130) ~[?:1.8.0_66]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-455072c-43ab266]
... 5 more
[10:36:32] [Server thread/ERROR]: Could not load 'plugins/EssentialsXAntiBuild-2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-455072c-43ab266]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-455072c-43ab266]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-455072c-43ab266]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.util.zip.ZipException: zip file is empty
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_66]
at java.util.zip.ZipFile.(ZipFile.java:219) ~[?:1.8.0_66]
at java.util.zip.ZipFile.(ZipFile.java:149) ~[?:1.8.0_66]
at java.util.jar.JarFile.(JarFile.java:166) ~[?:1.8.0_66]
at java.util.jar.JarFile.(JarFile.java:130) ~[?:1.8.0_66]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-455072c-43ab266]
... 5 more
[10:36:32] [Server thread/ERROR]: Could not load 'plugins/EssentialsXSpawn-2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-455072c-43ab266]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-455072c-43ab266]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-455072c-43ab266]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.util.zip.ZipException: zip file is empty
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_66]
at java.util.zip.ZipFile.(ZipFile.java:219) ~[?:1.8.0_66]
at java.util.zip.ZipFile.(ZipFile.java:149) ~[?:1.8.0_66]
at java.util.jar.JarFile.(JarFile.java:166) ~[?:1.8.0_66]
at java.util.jar.JarFile.(JarFile.java:130) ~[?:1.8.0_66]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-455072c-43ab266]
... 5 more
[10:36:32] [Server thread/ERROR]: Could not load 'plugins/EssentialsXChat-2.0.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Spigot-455072c-43ab266]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-455072c-43ab266]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugins(CraftServer.java:298) [spigot.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:203) [spigot.jar:git-Spigot-455072c-43ab266]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535) [spigot.jar:git-Spigot-455072c-43ab266]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.util.zip.ZipException: zip file is empty
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_66]
at java.util.zip.ZipFile.(ZipFile.java:219) ~[?:1.8.0_66]
at java.util.zip.ZipFile.(ZipFile.java:149) ~[?:1.8.0_66]
at java.util.jar.JarFile.(JarFile.java:166) ~[?:1.8.0_66]
at java.util.jar.JarFile.(JarFile.java:130) ~[?:1.8.0_66]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Spigot-455072c-43ab266]
... 5 more
[10:36:32] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[10:36:32] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.23.4
[10:36:32] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.3;7a097ca
[10:36:32] [Server thread/INFO]: [Ram_Monitor] Loading Ram_Monitor v1
[10:36:32] [Server thread/INFO]: [BuycraftX] Loading BuycraftX v10.1.3
[10:36:32] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49
[10:36:32] [Server thread/INFO]: [Multiverse-Core] Loading Multiverse-Core v2.5.0-SNAPSHOT-b722
[10:36:33] [Server thread/INFO]: [Multiverse-Portals] Loading Multiverse-Portals v2.5-b725
[10:36:33] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
[10:36:33] [Server thread/INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[10:36:33] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[10:36:33] [Server thread/INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[10:36:33] [Server thread/INFO]: [Vault] Enabled Version 1.5.6-b49
[10:36:33] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[10:36:33] [Server thread/INFO]: Preparing level "world"
[10:36:33] [Server thread/INFO]: -------- World Settings For [world] --------
[10:36:33] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:36:33] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:36:33] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:36:33] [Server thread/INFO]: Random Lighting Updates: false
[10:36:33] [Server thread/INFO]: Structure Info Saving: true
[10:36:33] [Server thread/INFO]: Cactus Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Cane Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Melon Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Sapling Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Wheat Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Vine Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Max Entity Collisions: 8
[10:36:33] [Server thread/INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[10:36:33] [Server thread/INFO]: Max TNT Explosions: 100
[10:36:33] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:36:33] [Server thread/INFO]: Mob Spawn Range: 4
[10:36:33] [Server thread/INFO]: Item Despawn Rate: 6000
[10:36:33] [Server thread/INFO]: Item Merge Radius: 2.5
[10:36:33] [Server thread/INFO]: Arrow Despawn Rate: 1200
[10:36:33] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:36:33] [Server thread/INFO]: View Distance: 10
[10:36:33] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[10:36:33] [Server thread/INFO]: Experience Merge Radius: 3.0
[10:36:33] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[10:36:33] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[10:36:33] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:36:33] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:36:33] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:36:33] [Server thread/INFO]: Random Lighting Updates: false
[10:36:33] [Server thread/INFO]: Structure Info Saving: true
[10:36:33] [Server thread/INFO]: Cactus Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Cane Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Melon Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Sapling Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Wheat Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Vine Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Max Entity Collisions: 8
[10:36:33] [Server thread/INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[10:36:33] [Server thread/INFO]: Max TNT Explosions: 100
[10:36:33] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:36:33] [Server thread/INFO]: Mob Spawn Range: 4
[10:36:33] [Server thread/INFO]: Item Despawn Rate: 6000
[10:36:33] [Server thread/INFO]: Item Merge Radius: 2.5
[10:36:33] [Server thread/INFO]: Arrow Despawn Rate: 1200
[10:36:33] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:36:33] [Server thread/INFO]: View Distance: 10
[10:36:33] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[10:36:33] [Server thread/INFO]: Experience Merge Radius: 3.0
[10:36:33] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[10:36:33] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[10:36:33] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:36:33] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:36:33] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:36:33] [Server thread/INFO]: Random Lighting Updates: false
[10:36:33] [Server thread/INFO]: Structure Info Saving: true
[10:36:33] [Server thread/INFO]: Cactus Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Cane Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Melon Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Sapling Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Wheat Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Vine Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[10:36:33] [Server thread/INFO]: Max Entity Collisions: 8
[10:36:33] [Server thread/INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[10:36:33] [Server thread/INFO]: Max TNT Explosions: 100
[10:36:33] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:36:33] [Server thread/INFO]: Mob Spawn Range: 4
[10:36:33] [Server thread/INFO]: Item Despawn Rate: 6000
[10:36:33] [Server thread/INFO]: Item Merge Radius: 2.5
[10:36:33] [Server thread/INFO]: Arrow Despawn Rate: 1200
[10:36:33] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:36:33] [Server thread/INFO]: View Distance: 10
[10:36:33] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[10:36:33] [Server thread/INFO]: Experience Merge Radius: 3.0
[10:36:33] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[10:36:33] [Server thread/INFO]: Preparing start region for level 0 (Seed: -2315739566707206351)
[10:36:34] [Server thread/INFO]: Preparing spawn area: 80%
[10:36:34] [Server thread/INFO]: Preparing start region for level 1 (Seed: -2315739566707206351)
[10:36:34] [Server thread/INFO]: Preparing start region for level 2 (Seed: -2315739566707206351)
[10:36:35] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.23.4
[10:36:35] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[10:36:35] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[10:36:35] [Server thread/INFO]: [Vault][Permission] PermissionsEx hooked.
[10:36:35] [Server thread/INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[10:36:35] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.3;7a097ca
[10:36:35] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[10:36:35] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_10_R1 as the Bukkit adapter
[10:36:35] [Server thread/INFO]: [Ram_Monitor] Enabling Ram_Monitor v1
[10:36:35] [Server thread/INFO]: [Ram Monitor] Listening on 104.128.52.106:1304
[10:36:35] [Server thread/INFO]: [BuycraftX] Enabling BuycraftX v10.1.3
[10:36:35] [Server thread/INFO]: [BuycraftX] Validating your server key...
[10:36:35] [Thread-9/WARN]: [PermissionsEx] The updater could not find any files for the project id 31279
[10:36:36] [Server thread/INFO]: [BuycraftX] Fetching all server packages...
[10:36:36] [Server thread/INFO]: [Multiverse-Core] Enabling Multiverse-Core v2.5.0-SNAPSHOT-b722
[10:36:36] [Server thread/INFO]: -------- World Settings For [VoidTest] --------
[10:36:36] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:36:36] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:36:36] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:36:36] [Server thread/INFO]: Random Lighting Updates: false
[10:36:36] [Server thread/INFO]: Structure Info Saving: true
[10:36:36] [Server thread/INFO]: Cactus Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Cane Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Melon Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Sapling Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Wheat Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Vine Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Max Entity Collisions: 8
[10:36:36] [Server thread/INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[10:36:36] [Server thread/INFO]: Max TNT Explosions: 100
[10:36:36] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:36:36] [Server thread/INFO]: Mob Spawn Range: 4
[10:36:36] [Server thread/INFO]: Item Despawn Rate: 6000
[10:36:36] [Server thread/INFO]: Item Merge Radius: 2.5
[10:36:36] [Server thread/INFO]: Arrow Despawn Rate: 1200
[10:36:36] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:36:36] [Server thread/INFO]: View Distance: 10
[10:36:36] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[10:36:36] [Server thread/INFO]: Experience Merge Radius: 3.0
[10:36:36] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[10:36:36] [Server thread/INFO]: Preparing start region for level 3 (Seed: 313257464860989511)
[10:36:36] [Server thread/INFO]: -------- World Settings For [jail] --------
[10:36:36] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[10:36:36] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[10:36:36] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[10:36:36] [Server thread/INFO]: Random Lighting Updates: false
[10:36:36] [Server thread/INFO]: Structure Info Saving: true
[10:36:36] [Server thread/INFO]: Cactus Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Cane Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Melon Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Sapling Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Wheat Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Vine Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[10:36:36] [Server thread/INFO]: Max Entity Collisions: 8
[10:36:36] [Server thread/INFO]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[10:36:36] [Server thread/INFO]: Max TNT Explosions: 100
[10:36:36] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[10:36:36] [Server thread/INFO]: Mob Spawn Range: 4
[10:36:36] [Server thread/INFO]: Item Despawn Rate: 6000
[10:36:36] [Server thread/INFO]: Item Merge Radius: 2.5
[10:36:36] [Server thread/INFO]: Arrow Despawn Rate: 1200
[10:36:36] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[10:36:36] [Server thread/INFO]: View Distance: 10
[10:36:36] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[10:36:36] [Server thread/INFO]: Experience Merge Radius: 3.0
[10:36:36] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[10:36:36] [Server thread/INFO]: Preparing start region for level 4 (Seed: -5095183178097749649)
[10:36:37] [Server thread/INFO]: [Multiverse-Portals] Enabling Multiverse-Portals v2.5-b725
[10:36:37] [Server thread/INFO]: [Multiverse-Portals] - Version 2.5-b725 Enabled - By Rigby and fernferret
[10:36:37] [Server thread/INFO]: [MVPLogging] 2 - Portals(s) loaded
[10:36:37] [Server thread/INFO]: [Multiverse-Portals] Found WorldEdit. Using it for selections.
[10:36:37] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:36:37] [Server thread/INFO]: Done (4.342s)! For help, type "help" or "?"
[10:36:37] [Server thread/INFO]: Starting GS4 status listener
[10:36:37] [Server thread/INFO]: Starting remote control listener
[10:36:37] [Query Listener #1/INFO]: Query running on 104.128.52.106:26833
[10:36:37] [Server thread/WARN]: No rcon password set in '/home/domipaco/40691/server.properties', rcon disabled!
[10:36:37] [Craft Scheduler Thread - 4/INFO]: [Vault] Checking for Updates ... 
[10:36:37] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[10:36:37] [Craft Scheduler Thread - 4/INFO]: [Vault] No new version available
[10:36:38] [Craft Scheduler Thread - 1/INFO]: [BuycraftX] Fetching all due players...
[10:36:39] [Craft Scheduler Thread - 1/INFO]: [BuycraftX] Fetched due players (0 found).`

**Comment by mdcfe** [comment]
Try downloading the plugins again. Also, use a code block for the log (three `s both before and after the log).

**Comment by benjamin-antupit** [comment]
@md678685 I just tried deleting all the EssentialsX files and re-downloading the jar from [here](https://ci.drtshock.net/job/essentialsx/lastSuccessfulBuild/). I still got the same issue as above.

**Comment by mdcfe** [comment]
Could you possibly paste the md5sums and size of the jars? Also, have you tried updating your server jar?

**Comment by benjamin-antupit** [comment]
I just updated my server jar to this (the 1.10.2 version). Jar size was 20.1 MB. Sorry @md678685, but how do I find the md5sums?

**Comment by mdcfe** [comment]
`md5sum <name>` should work (unless you're on Windows, in which case I believe it's somewhere in the files' properties).
